-- 118b_f18_5_improvement_log_import_p10
-- F18.5(b) improvement log import, part 10 of 12: i100..i107 (8 items, 1 comments).
-- GENERATED by scripts/gen_improvement_log_import.py from 260920_lovable_improvement_log_export.json - do not edit by hand.
-- Text is dollar-quoted and must stay byte-for-byte; the DO block at the end rolls the part back if not.

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i100$il$, $il$URGENT for Brad: verify the Frank Pelzer conversation row written into Supabase by hand, before Oliver writes any more$il$, $il$Data & schema$il$, $il$Brad$il$, $il$blocker$il$, $il$open$il$, $il$Oliver$il$, '2026-09-17T13:50:00.000Z'::timestamptz, 0, '{}'::text[], '{}'::text[], null, null, true, false, $il${"Brad": "2026-09-18T10:34:27.904Z", "Oliver": "2026-09-17T15:24:32.368Z"}$il$::jsonb,
$il$URGENT, AND NOTHING ELSE GETS WRITTEN THIS WAY UNTIL BRAD HAS CONFIRMED IT.

On 17 September Oliver wrote a conversation row into Supabase directly through the MCP, rather than through Lovable. It is the InMail to Frank Pelzer, Head of Sales Partner Management (HQ), Vodafone Germany. It renders correctly on the Conversation tab. Rendering correctly is not the same as being right, and Oliver wants it checked before he does any more of them.

THE ROW
  Contact: Frank Pelzer, Vodafone Germany
  Channel: InMail, outbound, from Oliver
  Date: 17 September 2026
  Subject: Versicherungsabo fuer euren Refurbished Shop
  Body: the short German opener about the Recommerce Group refurbished range, the checkout walk, the free month and the monthly cancellable subscription.

WHAT BRAD NEEDS TO CONFIRM, IN THIS ORDER

1. IS IT IN THE RIGHT PLACE. Correct table, correct contact id, correct direction and channel, and every column a downstream read depends on populated rather than null. A row that displays can still be missing the fields nothing shows.

2. DOES EVERYTHING THAT COUNTS TOUCHES SEE IT. PART OF THIS IS ALREADY ANSWERED AND IT IS GOOD NEWS: the Outreach tab shows it as Initial message, InMail, SENT, sent by Oliver, Sent Thu 17 Sept 2026 15:00, under FIRST MESSAGE 1. So the row is visible to the outreach view and is counting as the first message in the sequence. What is still unchecked is the rest: the Sent tab and the volume figure. The sequence position, message N of M, on the next draft for this contact. The day seven reply check, which should now be scheduled off 17 September. The cooldown and the duplicate approach guard. If any of those still read as though nothing was sent, the row exists but does not work.

3. WILL THE NEXT SYNC DUPLICATE IT. This is the one I would check hardest. The row was minted by hand, so it carries no LinkedIn message identifier. i053 has just shown five touches on one contact written in four different id namespaces, with the same connection request recorded twice. A hand written InMail with no platform id is exactly the shape that gets inserted a second time when a sync or backfill next meets the real thing.

4. IS THE INMAIL CREDIT ACCOUNTED. The send spent a credit. If the credit count is derived from touch rows it should have moved; if it is held separately it has not.

5. WHAT THE CORRECT PROCEDURE IS FOR THE NEXT ONE. Oliver will have more of these while Send is broken, see i082. Either Brad confirms this shape and Oliver repeats it exactly, or Brad gives a different route. Guessing twice is how the thing this item exists to prevent happens.$il$,
$il$WHY THIS MATTERS MORE THAN A SINGLE ROW. This InMail may be the ONLY record of the message that will ever exist. LinkedIn's data export contains DMs and has never contained InMails, so there is no archive to recover it from, and the four hourly watcher has just been shown not to pick up even a native DM, see the Fairphone case on i048. If this row is wrong, it is not wrong until someone fixes it, it is simply gone.

IT IS ALSO THE FIRST LIVE USE OF THE NEW WRITE ROUTE, AND BRAD HAS NOT BEEN TOLD ABOUT IT. His standing rule from 8 September was view only through the MCP: Claude proposes, Lovable applies. That rule is now superseded at guard level 0, with every write logged and shown, but the telling has not happened. This row is the moment it has to, because Brad is about to be asked to verify a write he did not know the route for. Worth doing before he opens the item, not after.

WHAT WOULD MAKE THE WHOLE QUESTION GO AWAY. A supported way to log a message that was sent outside Lovable, from inside Lovable. That is i064, a message sent outside Lovable still gets a follow up, and it is exactly this need. If that existed, Oliver would not be writing rows by hand and none of the five checks above would be necessary. Worth saying plainly to Brad: the manual write is a symptom of a missing button.

ONE OBSERVATION ON THE MESSAGE ITSELF, not a defect. It went as an InMail with a subject line, which is correct per i026, and the German in it is clean, which is the standard i098 is asking the generator to reach. The contrast is worth noting: the hand written message is the one without errors.$il$);
insert into public.improvement_comments (team_id, improvement_id, who, at, text)
select i.team_id, i.id, $il$Claude$il$, '2026-09-17T15:00:00.000Z'::timestamptz,
$il$CHECK 2 HAS MOVED ON, ANOTHER PIECE ANSWERED. The Sent tab has gone from 846 to 847 and All from 1128 to 1129. Nothing has been sent through Lovable today because Send now is down, see i082, so the one new sent touch is the Frank Pelzer InMail written by hand. The row now counts in Sent and in All, on top of appearing on the Outreach tab as FIRST MESSAGE 1.

STILL UNCHECKED, and these are the ones that matter: whether the day seven reply check is scheduled off 17 September, whether the sequence position on the next draft for this contact reads correctly, whether the InMail credit moved, and whether a later sync will insert the same InMail a second time because this row carries no LinkedIn message id.$il$
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i100$il$;

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i101$il$, $il$A company is flagged as moved to Monday when it is not, and the flag offers no way to check it$il$, $il$Data & schema$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-17T14:40:00.000Z'::timestamptz, 1, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Vodafone Portugal carries the badge Already moved to Monday, with a Restore button. Oliver says there is no Vodafone Portugal in monday, and a check agrees with him.

WHAT I CHECKED. Searching monday items for Vodafone returns no Vodafone record of any kind. What it returns instead is Spusu, giffgaff, A1 Telekom Austria Group, Orange Polska, Fonua, medion and other telcos. So there is no Vodafone company on the board, and the search that found those is matching on similarity rather than on the literal name. That second part is the clue: name based matching between these two systems produces confident false positives, and this is one.

WHY IT IS WORSE THAN AN ORDINARY WRONG FIELD. A suppressed company is invisible work. A wrong status still shows up in a list and gets questioned eventually. A company marked as moved to monday drops out of the worklists on purpose, so nobody goes looking for it and nothing ever contradicts the flag. This particular record is P0, Telco, Portugal, refurbished yes, SIM-free yes, annual devices Large, owner Oliver, product line Pier Protect. That is a serious target that has been silently parked.

IT ALSO COMPOUNDS WITH i046. A company flagged as moved to monday is hidden from the company picker, which is what made spusu look missing. So a wrongly flagged company cannot be worked AND cannot be attached to a new contact, and neither failure announces itself.

WHAT IS NEEDED

1. SUPPRESSION IS KEYED ON A MONDAY ITEM ID, NEVER ON A NAME. Store the id of the monday item the company maps to. If there is no id, there is no suppression.

2. THE BADGE SHOWS ITS EVIDENCE. Name the monday item it claims to map to and link to it, so a wrong flag is falsifiable in one click. Today it asserts and offers no way to check.

3. RUN THE AUDIT. List every company currently flagged as moved to monday and reconcile it against the monday board by id. The number with no matching item is the size of this, and it decides whether this stays a must or becomes a blocker.

4. IF ANYTHING MATCHES BY NAME, STOP IT. At minimum require an exact match plus a confirmation. Prefix and similarity matching will hit every brand family in the lake: Vodafone Germany against Vodafone Portugal against Vodafone Group, and the same for every operator and retailer group.

5. RECORD WHO ARCHIVED IT, WHEN, AND WHY. A flag with no provenance cannot be unpicked. Same gap as i076.

RESTORE EXISTS, WHICH IS THE GOOD NEWS. This record can be fixed in one click. Do not restore in bulk until the audit says which ones are wrong, because some of them will be correct.$il$,
$il$THE RULE BEHIND THE SUPPRESSION IS RIGHT AND SHOULD SURVIVE THIS. A company being worked in monday must not also be worked in the lake, or two people approach the same account from two systems. That is a standing rule and it is not in question. What is in question is how a company is decided to be one of them.

THIS IS THE THIRD PROBLEM WITH THE SAME MECHANISM. i044 says the suppression is applied on some screens and not others. i046 says the company picker hides suppressed companies silently rather than showing them as suppressed. Now i101 says the flag itself can be wrong. Taken together the mechanism is unreliable in all three directions, which is an argument for rebuilding it once on an id rather than patching each symptom.

ON THE VODAFONE FAMILY SPECIFICALLY, and it connects to i099. The lake holds Vodafone Germany, Vodafone Portugal and at least one group level contact, Ben Beasley, filed under the German entity. If anything anywhere matches these by name, the three of them will keep colliding: in the suppression check, in duplicate detection, and in the group rollup. Deciding the Vodafone structure properly once, per i047 and i068, removes the ambiguity that the matching is currently guessing at.

A QUESTION WORTH ASKING BRAD. Where did this flag come from. If it was written by a one off import, the audit is a one time cleanup. If it is recomputed on a schedule, then restoring this record will not hold and it will be re-archived on the next run, which is the version that matters and needs finding before Oliver spends time on restores.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i102$il$, $il$The country is already in the contact header, it is the field that is empty$il$, $il$Data & schema$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-17T15:35:00.000Z'::timestamptz, 1, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Oliver asked for the lead's country to be shown at the top next to the name. IT ALREADY IS, and that is worth knowing before anything is built.

  Hartmut Baumann reads P675, Director Purchasing / Sales, P0, Germany
  Louis Salzman-Le Goff reads P657, Responsable Partenariats et Grands Comptes, P2, France
  Frederic Gandon reads P566, Co-fondateur Largo, P1, France
  Kristjan Nemvalts reads P694, Chief Executive Officer, Estonia

SO THE HEADER IS NOT THE PROBLEM, THE FIELD IS EMPTY. Dhananjay Choubey at Revent reads P303, Co-Founder, P3, and stops. The priority is there, the country is not, because there is no country on the record. The header is already doing what Oliver asked for and is simply being handed nothing.

THAT MAKES THIS A DATA COMPLETENESS ITEM, NOT A DISPLAY ONE, and it is worth more than the nice to have it came in as. Country is not decoration. It decides:
  Whether cold email is permitted at all. France, Belgium, Netherlands and Switzerland yes, Germany, Austria, Spain, Luxembourg, Italy and Czechia no. The hard block asked for in i089 cannot run on a blank.
  Whose territory the contact is in. UK is Jack's.
  Which language the draft is written in.
  Which country filter in i038 the contact appears under, so a blank country means the contact is invisible to every country view.

WHAT IS NEEDED
1. Count how many contacts have no country. That number decides whether this is a backfill or a handful.
2. Fill it from what is already known. The company has a country, the Sales Navigator profile has a location, and in this case the draft itself talks about the Saudi market. Inheriting the company's country as a default, marked as inherited rather than stated, would close most of it.
3. Refuse to write an email draft for a contact with no country, rather than guessing. A blank is not a permission.
4. Show the blank rather than hiding it. A header that simply stops gives no signal that something is missing; an explicit Country not set does.$il$,
$il$OLIVER SHOULD NOT HAVE HAD TO ASK FOR THIS, WHICH IS THE POINT. He looked at a contact, could not see a country, and reasonably concluded the header did not show one. The header does. Nothing on the card distinguishes this field is not displayed from this field is empty, and those need completely different actions. The same reasoning is in i085: an empty result has to say why it is empty.

TWO OTHER THINGS ON THIS CARD, NEITHER RAISED BY OLIVER.

THE TOUCH ID READS synthetic-cr-P303. That is a fifth id namespace on top of the four already recorded on i053, and this one is explicit about being generated rather than observed. The connection request it describes does appear to be real, it shows as sent on 30 August in the conversation below, so synthetic here probably means a placeholder id minted because the platform id was unknown. Worth confirming that, because if any synthetic row describes an event that did not happen, the touch history contains invented touches and every guard that reads it is wrong in the worst possible direction.

THE DRAFT SIGNS OFF Oli. That is i067 again and now a fourth sighting, on an English draft to a Saudi contact, which supports the note on i067 that the sign off varies by generation path rather than being one consistent mistake.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i103$il$, $il$Industry has no value for price comparison sites, and no rule for whether they are in scope$il$, $il$Data & schema$il$, $il$Both$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-17T15:50:00.000Z'::timestamptz, 1, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$The Industry list offers none, Mobile/Gadget Retail, Refurb / Recommerce, Telco, Manufacturer, Software, Telco Infrastructure, Industry Media, Influencer, Other. There is no value for a price comparison site, so Oliver has to pick something that is not true or fall back on Other.

THE COMPANY THAT SURFACED IT MAKES THE POINT. Vendre Mon Mobile compares what different buyers will pay for your old phone. It is currently filed as Mobile/Gadget Retail with Refurbished and SIM-free both blank and devices sold recorded as Small (TBC), because none of those questions have an answer for a business that does not sell devices.

ADDING THE VALUE IS THE EASY HALF. Price comparison, and probably buyback comparison as a separate value or as the same one, since a site comparing sale prices and a site comparing trade-in offers behave differently for us.

THE HARDER HALF IS WHAT THE CLASSIFICATION THEN MEANS, and it is the part worth deciding once rather than per company. A comparison site does not own a checkout. The attach model needs a checkout to attach to, so the standard proposition does not apply. Three possible answers and they lead to completely different work:
  Out of scope, with the reason recorded, per the rule that every company gets entered with why rather than deleted.
  In scope through a different route, a referral or affiliate relationship rather than an embedded one, which would be a separate proposition and a separate message.
  In scope only when they also run their own shop, which some of them do, in which case the question is about that shop and not about the comparison business.

UNTIL THAT IS SETTLED, THE FIELD CANNOT DO ITS JOB. The reason to classify a company is so the system knows what to do with it. A value that exists but carries no scope rule just moves the guessing from the field to the person reading it.

ALSO WORTH FIXING WHILE THE LIST IS OPEN: this record carries both an INDUSTRY dropdown reading Mobile/Gadget Retail and a CATEGORY field reading Refurbished Specialist. Two taxonomy fields on one company, overlapping, with no stated difference between them. That is i049 and i078, and adding values to one of them without settling which is which will make it worse.$il$,
$il$WHY I HAVE NOT JUST CALLED IT A NICE TO HAVE. Classification is what the scoring in i071 and the ICP gate read. A company in the wrong class is not mislabelled, it is mis-scored, and at the moment the only honest options for a comparison site are a wrong value or Other. Other is where things go to be forgotten.

THE B2C AND B2B RULE ALREADY HALF ANSWERS IT. The standing knock-out is that B2B only is out of scope and B2B led needs the consumer share verified first. A price comparison site is consumer facing but sells nothing, which the rule does not currently cover. It is a third case, consumer facing and not transacting, and it deserves its own answer rather than being squeezed into the existing two.

WORTH CHECKING HOW MANY THERE ARE BEFORE DECIDING. If the lake holds three comparison sites, the answer can be a judgement per company. If it holds thirty, it is a segment and needs a proposition or an exclusion rule. That count is cheap and should come before the debate.

ONE ARGUMENT FOR KEEPING THEM IN. A comparison site knows, at the moment of comparison, that somebody is about to buy or sell a device. That is the same trigger the attach model uses, reached one step earlier. Whether that is worth anything to Pier depends on whether they would pass a referral on and whether the economics survive a second party in the chain. Not obvious either way, which is exactly why it should be decided deliberately and written down rather than resolved company by company.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i104$il$, $il$A contact who has left the company is still attached to it, and the job change exists only as prose$il$, $il$Data & schema$il$, $il$Both$il$, $il$must$il$, $il$done$il$, $il$Oliver$il$, '2026-09-17T16:25:00.000Z'::timestamptz, 1, '{}'::text[], '{}'::text[], $il$Brad$il$, '2026-09-18T10:44:02.770Z'::timestamptz, false, false, $il${"Brad": "2026-09-18T10:43:41.854Z"}$il$::jsonb,
$il$Antonius Fromme has left freenet AG. The record still has him at freenet AG, and the system already knows he has gone.

LOOK AT WHERE THE KNOWLEDGE IS SITTING. His job title field reads Strategic Advisor / Start-up Investor (FORMER Chief Customer Experience Officer, freenet AG). His Next Action field reads JOB CHANGE + PITCH ALREADY SPENT, Oliver's 1-Sep thread paste shows his profile now reads Strategic Advisor, Start-up-Investor, Start-up-Builder. So the fact was noticed, written down twice in prose, and the one structured field that matters, the company he is attached to, still says freenet AG.

NOTHING READS PROSE. Every guard, every worklist and every draft reads the company link. So for the system he is still a freenet decision-maker, and the next message written to him will pitch freenet's checkout to someone who does not work there. That is the kind of mistake a recipient notices immediately.

WHAT IS NEEDED

1. A JOB CHANGE IS A STRUCTURED EVENT, not a note. Record that he left, roughly when, and where he is now, even if the answer is nowhere or unknown. The title field should hold his title, not the word FORMER.

2. THE COMPANY LINK HAS TO FOLLOW, which needs the move control in i099. Without it, knowing about a job change changes nothing, because there is no way to act on it.

3. THE OLD COMPANY LOSES COVERAGE AND SHOULD SAY SO. freenet AG has just lost a decision-maker and nothing surfaces that. The standing rule is that a company is not worked until its real decision-makers are covered, so a departure should put freenet back on the sourcing list rather than leaving it looking covered.

4. THE PERSON IS NOT LOST, HIS ROLE CHANGES. He is a first degree, accepted, C-suite contact where the pitch is already spent. That makes him a route to other people rather than a prospect, which is a different status and a different next action. Today the only vocabulary available is Contacted, which says nothing useful about any of this.

5. CATCH IT AUTOMATICALLY. Sales Navigator flags job changes natively, and the sync already reads these profiles. If the current employer on the profile does not match the linked company, flag the contact for review. That is the cheapest reliable detector available and it does not need anyone to remember.$il$,
$il$THE GENERAL CASE MATTERS MORE THAN THIS CONTACT. A lead book decays at roughly a fifth a year through job changes alone, and this one is 637 contacts sourced from May onwards. If nothing detects departures, the proportion of the book that is quietly wrong only grows, and it is invisible: a wrong employer looks exactly like a right one until somebody opens LinkedIn.

A JOB CHANGE IS ALSO A SIGNAL, NOT ONLY A CORRECTION. Somebody moving from one target company to another arrives as a warm first degree contact at a new account, which is the best cold start available. That is worth a trigger rather than a cleanup task. It does not apply here, because Fromme has moved to advising and investing rather than to another retailer, but the rule should be built for the case where it does.

WHERE THE PROSE IS DOING STRUCTURED WORK, AND IT KEEPS HAPPENING. FORMER in a job title. JOB CHANGE and PITCH ALREADY SPENT in a next action field. On Marcel de Groot, a channel closure in an outreach status. On Florian Pfeiffer, the source of a bad write in a next action field. Four different facts, all of them load bearing, all of them held as sentences that nothing can read. Worth Brad seeing them together, because the answer is the same each time: if something acts on it, it is a field.

ONE SMALLER THING ON THIS CARD. The next action date is 8 September, nine days ago, and nothing surfaces that it has passed. Same as Ben Beasley on i099, whose date is four months overdue. An overdue next action is the one thing a next action field exists to produce, and at the moment it simply sits there.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i105$il$, $il$Outreach shows research priority where it should show the lead score$il$, $il$Lovable UI$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-18T10:30:00.000Z'::timestamptz, 5, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$In the Outreach view the Companies column shows a P0, P1, P2 or P3 badge against every company. That is Research Priority, and it is the wrong number for this screen.

WHAT THIS SCREEN IS FOR. Oliver is deciding who to write to and in what order. The question is how valuable this company is to approach. Research priority answers a different question: how much research effort this company should get. Those are two different jobs and only one of them belongs here.

REPLACE IT WITH THE LEAD SCORE. The score from i071, the one that decides who the day's twenty connection requests go to, is the number that should sit in this column and drive the ordering. Research priority should come out of this view entirely.

THEN DECIDE WHERE RESEARCH PRIORITY DOES BELONG, once, rather than leaving it scattered. The honest answer is probably: on the company record itself, and in whatever view is used to choose what to research next. It does not belong in Outreach, it does not belong on a contact card, and it does not belong on a draft review card, because in none of those places is anyone deciding what to research. Worth a sweep of every screen it currently appears on, not just this one.

A NOTE ON THE VOCABULARY, because it will make this worse if left. P0, P1, P2, P3 does not say which end is good. It reads as a priority on a scale nobody has written down, and it is already being used in at least two senses in the app. i003 asks for P0, P1 and P3 to be replaced by a derived next step for exactly this reason. If the badge is going to change anyway, this is the moment to give both fields names that say what they mean: a score that is obviously a score, and a research stage that is obviously about research.$il$,
$il$THE PATTERN, AGAIN, AND THIS TIME IT IS ABOUT DISPLAY RATHER THAN SCHEMA. i041 had a header chip and a field disagreeing about status. i086 had condition and commercial model in one field. i093 had channel availability inside outreach status. i002 has two products with no field to tell them apart. Here both fields exist and are distinct, and the wrong one is on screen. That is a cheaper problem than the others and it should be a cheaper fix, but it produces the same outcome: a decision being made against a number that does not answer the question.

THIS DEPENDS ON i071 AND SHOULD NOT GO FIRST. There is no lead score to display until the scoring in i071 exists. The sensible order is score first, then swap the badge, then remove research priority from the views where it does not belong. Swapping the badge to an empty field would be worse than leaving it.

SOMETHING ELSE ON THE SAME SCREEN, NOT RAISED BY OLIVER, AND IT IS A REAL DEFECT. The Sent by facet reads Oliver Mueller 537, Oliver 226, Hector 2, plus fourteen more. Oliver Mueller and Oliver are the same person recorded under two different strings, splitting 763 touches across two labels. Any per sender count, and anything that filters by owner, is currently wrong by construction. Sender identity needs normalising to a person rather than a free text name, and the facet is the cheapest place to see how bad it is: fourteen more values behind those three.

WORTH CHECKING WHILE THERE. Hector appears as a sender with two touches. Hector Destailleur is a contact at Recommerce Group, not a colleague. If inbound replies are written with the contact as sent_by, that is defensible, but then the facet is mixing senders and repliers under one label and should say which it means.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i106$il$, $il$Pin the open task to the top of the record, tick it off there, and roll every task into a dated activity view$il$, $il$Lovable UI$il$, $il$Brad$il$, $il$nice$il$, $il$open$il$, $il$Oliver$il$, '2026-09-18T11:15:00.000Z'::timestamptz, 5, '{}'::text[], array[$il$i036$il$]::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Oliver likes how the refurbed deal works in monday and wants the same three things in Lovable.

1. THE OPEN TASK SITS AT THE TOP OF THE RECORD. Open a company or a contact and the first thing on the page is what needs doing here, not the history. Everything else is below it.

2. YOU TICK IT OFF IN PLACE. One control, on the record, no dialog. Done means done and the record moves on.

3. TASKS ROLL UP INTO AN ACTIVITY VIEW. One list across every company and contact, bucketed as today, tomorrow, this week, overdue. This is the part Lovable has no equivalent of, and it is how Oliver organises his day.

WHAT MONDAY ACTUALLY DOES, since it is worth copying rather than reinventing. The Activities board holds 696 rows, one per activity, each linked back to its deal, contact or company through a relation column. Each row carries:
  Activity Type: Task, Email, Call, Meeting, LinkedIn message, Email chaser, Sales Navigator chaser, Phone call
  Status: exactly two values, Open and Done
  Start time, which despite the name is the DUE date
  A separate Completed date, auto stamped the moment Status goes to Done
  Owner
  Draft, holding the pasteable message and nothing else
  Note, holding the context for the draft

THE TWO DATE SPLIT IS THE PART MOST SYSTEMS GET WRONG AND MONDAY GETS RIGHT. One field says when it is due, a second says when it actually happened, and the second is written by the system rather than by hand. monday's own column description spells it out: the completed date is the only field recording when work happened, the start time is the due date, do not edit by hand. Without that split there is no way to answer either what is late or what got done this week, because one field cannot mean both.

THE DRAFT AND NOTE SPLIT IS ALSO WORTH KEEPING. The draft column holds only the message, so it can be copied straight out. Everything about why it is worded that way lives in the note. Lovable already half has this in the draft plus narrative pairing on the review card.$il$,
$il$THIS IS THE SURFACE FOR i036, NOT A SEPARATE ENGINE. i036 already specifies the activity itself: two lanes, derived from the standard process or set by hand, the draft written on the day rather than when it is scheduled, guards re-checked at send time, and never leaving a record without a next action. What i036 does not say is where any of it appears. This item is that: pinned at the top of the record, tickable in place, and rolled up into a dated list. They should be built together, because i036 without a surface is a field nobody sees, and this without i036 is a list with nothing to put in it.

THE TICK BOX HAS A CONSEQUENCE, AND IT IS THE STANDING RULE. Completing an activity has to produce the next one. So the tick is not just a state change, it is the moment the next action gets set, and closing with nothing behind it should not be possible without explicitly choosing the six month check back or the opt out. That rule is already on i036; it lands here because here is where the tick lives.

WHAT THE ACTIVITY VIEW REPLACES. Today, the follow up engine is monday plus Make.com plus in-thread Outlook chasers. The activity view is the thing that makes that retirable, which is why it is worth more than the nice to have it came in as. Oliver's words were that he likes being able to organise himself like this, and at the moment he can only do it in monday, for the handful of accounts that have monday deals.

ONE DESIGN CHOICE TO MAKE EARLY. monday's Status has exactly two values, Open and Done, and that is a deliberate constraint rather than a limitation. Anything richer, in progress, blocked, waiting, turns the list into a second pipeline status and it will start disagreeing with the outreach status, which is the i041 and i093 failure again. Two values, and let the due date carry the urgency.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i107$il$, $il$Hold the first DM for seven days after a CR is accepted, so a post lands first. Brad to challenge$il$, $il$Outreach & drafting$il$, $il$Both$il$, $il$nice$il$, $il$open$il$, $il$Oliver$il$, '2026-09-18T11:40:00.000Z'::timestamptz, 6, '{}'::text[], array[$il$i097$il$]::text[], null, null, false, false, $il${}$il$::jsonb,
$il$OLIVER'S PROPOSAL, AND HE HAS ASKED BRAD TO CHALLENGE IT RATHER THAN BUILD IT.

When somebody accepts a connection request, hold the first DM for seven days instead of sending it straight away. The week gives Oliver time to publish a LinkedIn post that the new connection is exposed to, so the DM arrives as the second thing they have seen from Pier rather than the first.

WHAT THAT LOOKS LIKE IN THE QUEUE. The First message after CR accepted category splits in two:
  Waiting, accepted less than seven days ago, not draftable yet, with the date it becomes available shown on the row
  Ready, the wait is served, draft it

BUILD THE SPLIT AS A COMPUTED THING, NOT A STATUS SOMEBODY SETS. Ready is accepted_at plus N days, where N is a setting rather than a number in the code. If the answer turns out to be three days or fourteen, that should be a field to change, not a rebuild. The two categories are then just two sides of one date comparison.

IT BELONGS IN THE SEND QUEUE, i097. That item already introduces a queue with a release time per message. This is the same mechanism with the release time set from the accept date instead of from the daily allowance, so it should be one piece of machinery, not two.

EXCEPTIONS THAT SHOULD SKIP THE WAIT
  They message first. If they open the conversation, answer them, obviously.
  A dated reason exists. An event next week, a deadline they mentioned, a trade show.
  Possibly the top of the score list. Worth deciding whether a high value target waits like everyone else.

BRAD, THE ASK IS TO CHALLENGE THIS, NOT TO IMPLEMENT IT. Oliver wants the argument tested before it becomes a rule. The strongest objections are below, and he would rather they were put properly than agreed with.$il$,
$il$THE CASE FOR IT. Acceptance is a weak signal; somebody accepted a blank invitation, which under the standing rule carries no note at all. Arriving immediately with a pitch is the transactional move the blank connection request exists to avoid. A post in between makes the DM the second touch, and it gives the weekly posting habit a job, which makes the habit stick.

THE CASE AGAINST, AND IT IS NOT WEAK.

  IT ONLY WORKS IF A POST ACTUALLY GOES OUT. Weekly posting is intended rather than established. If no post lands inside the window, the wait is a week of delay that bought nothing, and it will keep buying nothing quietly.

  EXPOSURE IS NOT GUARANTEED AND NOT MEASURABLE HERE. A post reaching a specific new connection is a matter of LinkedIn's distribution, not of the connection existing. Nothing in Lovable can tell whether this person saw anything, so the premise of the delay can never be confirmed from the data. That is an uncomfortable thing to build a rule on.

  ACCEPTANCE IS THE MOMENT OF PEAK ATTENTION. They have just looked at the profile and decided yes. A message a day or two later rides that. A message seven days later arrives at somebody who has forgotten accepting, and the opener has to do more work.

  THE COST COMPOUNDS ACROSS THE BOOK. Every accept moves back a week, permanently, not once. With the daily allowance already rationed at twenty, see i072, deliberately slowing the only part of the funnel that is not rate limited is worth being sure about.

SO SETTLE IT WITH DATA, NOT ARGUMENT. There are 439 connection requests on record and accepts arrive steadily, so this is testable rather than debatable. Split accepts at random: half get the DM within a day, half wait seven, and compare reply rate over a few weeks. Whatever the result, it also produces the first measured number this engine has ever had about its own cadence, which is worth more than the delay question on its own. That argues for building the Waiting and Ready split now, because the split is what makes the test possible, and holding the seven days as a hypothesis until the numbers come back.

WORTH NOTING THE SPLIT IS USEFUL EVEN IF THE ANSWER IS NO. As soon as any delay exists, for any reason, the queue needs to distinguish not yet from ready. Today the category mixes both and Oliver cannot see which is which.$il$);

-- exactness gate: every item in this part must hash to the value computed from the source file
do $verify$
declare bad text;
begin
  select string_agg(e.item_key, ', ' order by e.item_key) into bad
  from (values
    ('i100', '0ad45013f7f7ff09efc194025d98e3c6', 1),
    ('i101', '7e9f82177e22b7b142f537eda44ca49b', 0),
    ('i102', 'd996c619bbf38bf332ec55d73a828ada', 0),
    ('i103', 'fe98a2610c6295e9dbfc5a65d0b7abfa', 0),
    ('i104', 'f2f4c3ae2f3989b9423941dfe7dba7dc', 0),
    ('i105', '5c479cfb55209ad9a2ef519749d03da8', 0),
    ('i106', 'fddc00a94b644afd6f75461bdee7f3cb', 0),
    ('i107', '8828b44c0b6a30839343def057789311', 0)
  ) as e(item_key, src_md5, n_comments)
  left join public.improvements i
    on i.item_key = e.item_key and i.team_id = (select id from public.teams limit 1)
  where i.id is null
     or e.src_md5 is distinct from md5(concat_ws(chr(31),
      i.title, i.category, i.owner, i.priority, i.status, coalesce(i.raised_by,''), i.detail, i.notes,
      coalesce(i.done_by,''), array_to_string(i.blocks,','), array_to_string(i.blocked_by,','),
      coalesce(i.build_wave::text,''), i.pinned::text, i.hidden::text,
      to_char(i.created_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), coalesce(to_char(i.done_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),''), i.seen_by::text,
      coalesce((select string_agg(concat_ws(chr(31), c.who, to_char(c.at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), c.text), chr(30) order by c.at)
                from public.improvement_comments c where c.improvement_id = i.id), '')));
  if bad is not null then
    raise exception 'F18.5 import: rows differ from the source export: %', bad;
  end if;
end
$verify$;
