-- 118b_f18_5_improvement_log_import
-- F18.5(b) improvement log import, part 1 of 12: i000..i025 (26 items, 2 comments).
-- GENERATED by scripts/gen_improvement_log_import.py from 260920_lovable_improvement_log_export.json - do not edit by hand.
-- Text is dollar-quoted and must stay byte-for-byte; the DO block at the end rolls the part back if not.

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i000$il$, $il$READ FIRST: suggested build order, because several of these block each other$il$, $il$Data & schema$il$, $il$Both$il$, $il$must$il$, $il$open$il$, $il$Claude$il$, '2026-09-01T00:00:00.000Z'::timestamptz, null, '{}'::text[], '{}'::text[], null, null, false, false, $il${"Oliver": "2026-09-09T11:28:43.974Z"}$il$::jsonb,
$il$Several of these block each other. Switch Group by to Build order, or just look at the list as it stands: items now nest under whatever unblocks them, so you can see at a glance that one job frees four others. Tick this off once the order is agreed. It is a plan, not a piece of build.$il$,
$il$Not an improvement, a sequencing note. There are 17 must haves and they are not independent, so working down the list in the order they were raised means building some of them twice. This is a suggested order, argue with it.

WAVE 0 - UNBLOCK
  i001 Supabase MCP connector via Paul. Gates the research agent entirely, and with it i008, i014, i025 and i029. Nothing in wave 3 or the agent side starts without it.

WAVE 1 - SCHEMA AND DATA TRUTH, before anything reads it
  i031 Split LinkedIn URL from Sales Nav URL, backfill, and make record-at-send a hard rule
  i002 product_line enum on companies AND contacts
  i006 Estimates structurally separate from stated figures, is_estimate flag
  i018 Widen the Reply Classification enum
  i010 Fix connection status mirroring
  WHY FIRST: everything downstream reads these. Getting them wrong now means a data migration later rather than an edit. i018 in particular is an enum decision, and it is the reason the success metric is currently unmeasurable, so it is cheap now and expensive after there is data in it.

WAVE 2 - THE GUARDS, all failing closed
  i005 Fail closed as the pattern for every guard, null blocks and never passes
  i004 Group level duplicate approach guard
  i030 A send derives status to Contacted, forward only, plus the reconciliation of the ten wrong rows
  WHY SECOND: outreach is happening now, and these are what stop it going wrong. i005 is the pattern the other two are built on, so it goes first within the wave.

WAVE 3 - THE DERIVED STATE LAYER
  i029 Research stage goes Outdated on age, and the research queue
  i025 Comments and instructions field feeding THE SAME queue, build one not two
  i003 next_step replacing P0/P1/P3
  WHY IN THIS ORDER: i003 derives from the states the other two create. Build next_step before Outdated exists and it has nothing to read. i025 and i029 are one piece of plumbing with two entry points, so do them together or the second one rebuilds the first.

WAVE 4 - DRAFTING QUALITY
  i007 Wire the four layer draft stack
  i026 Subject lines generated with the draft, including the message type matrix
  i008 Hold the four layers as versioned rows in Supabase, needs i001
  WHY HERE: the drafts already work well enough to send. This makes them right rather than makes them possible.

WAVE 5 - USABILITY, low risk and parallelisable, drop into any gap
  i028 Long text truncation, the biggest single readability win
  i032 Jump buttons to LinkedIn and Sales Nav, NEEDS i031 first or it is dead for a third of contacts
  i011 Source leads for these companies as a Today headline
  i009 Move to Monday button, retires a 70 pound a month tool
  i022 Inline editing, i023 column widths, i027 Countries multi select, i016 delete button, i024 link rot

WAVE 6 - NEW CAPABILITY
  i012 Funnel view
  i013 Campaigns, which is also where the revised cooldown lives
  i014 Buying signals, needs i001
  i015 Email and phone enrichment, needs i031 because it looks up on the /in/ URL

DUPLICATE TO CLOSE: i017 'LinkedIn button on the contact card' is now covered by i032, which does both surfaces and both URL types. Tick i017 off against i032 rather than building it twice.

THE THREE PARKED ITEMS are decisions and cautions rather than work: i019 do not automate LinkedIn deep links, i020 title matching alone picks the wrong people at scale, i021 calibrate the 1.5 percent conversion rate against a real partner. i021 is the highest value measurement available to us and only Oliver can trigger it, by asking one partner for their visits to orders ratio.$il$);
insert into public.improvement_comments (team_id, improvement_id, who, at, text)
select i.team_id, i.id, $il$Claude$il$, '2026-09-09T10:40:00.000Z'::timestamptz,
$il$Dated 1 September deliberately so it sorts to the top of Must have and gets read before the list is worked. It is a plan, not an improvement, so tick it off once the order is agreed rather than treating it as a piece of build.$il$
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i000$il$;

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i001$il$, $il$Connectors are added, but Oliver cannot log in$il$, $il$Integrations$il$, $il$Both$il$, $il$blocker$il$, $il$open$il$, $il$Oliver$il$, '2026-09-08T16:00:00.000Z'::timestamptz, 0, array[$il$i008$il$,$il$i014$il$,$il$i025$il$,$il$i029$il$]::text[], '{}'::text[], null, null, false, false, $il${"Brad": "2026-09-20T14:40:41.450Z", "Oliver": "2026-09-15T13:06:51.416Z"}$il$::jsonb,
$il$Moved on, still blocking. Paul has added the Supabase and Lovable connectors to Oliver's Claude, so the admin permission part is closed. Oliver now cannot log in, so the research agent still cannot reach Supabase and nothing downstream of this has been unblocked in practice.

Next step, agreed 9 September: Oliver and Brad walk through it on a screenshare rather than trading messages about it. There is a short list of the usual causes in the background below, worth having open during the call so it takes ten minutes rather than an hour.$il$,
$il$WHAT TO ESTABLISH FIRST, because these are four different failures wearing the same face:
1. Which login is actually failing. The connector's OAuth handshake to Supabase, the Lovable connector, or signing in to the Supabase dashboard directly in a browser. Try the plain dashboard login first, outside Claude. If that fails too, this is not a Claude problem at all and the call should be with Paul, not Brad.
2. Whether Oliver has a Supabase account WITH ACCESS TO THE PROJECT. Adding a connector to the workspace and being a member of the Supabase organisation are separate things. Paul may have done the first and not the second, which would look exactly like this.
3. Same question for Lovable: does Oliver hold a seat on the actual project, or only an account.
4. Which Claude surface is being used. A connector added org wide can still need enabling for the individual user, and claude.ai and Claude Code do not always present the same list.

TWO THINGS THAT CATCH PEOPLE OUT, worth checking before anything more elaborate:
A second signed in identity in the browser will silently capture an OAuth redirect, so the handshake completes against the wrong account and then denies access. Try it in a private window. Oliver has had a dotless alias account cause exactly this kind of confusion before.
If Pier uses Microsoft single sign on, Supabase has to be entered through the right identity provider. Signing in with email and password on an account that was created through SSO fails in a way that reads as a bad password.

WHAT TO CAPTURE ON THE CALL, so this item can be closed honestly: the exact error text, which of the four logins above it came from, and who owns the fix. If it turns out to be a Supabase org invite, that is Paul again and the item stays open until he has done it.

STILL THE SAME DEPENDENCY. This continues to gate i008, i014, i025 and i029. Nothing changes there until Oliver is actually signed in, so do not treat the connectors being present as this item being done.

HISTORY, the original block, now cleared: Oliver is a member, not an admin, of the Pier Claude team workspace, and only admins can add custom connectors. Paul owns the workspace and needed to add it org wide. Brad asked Paul, and Paul has done it.$il$);
insert into public.improvement_comments (team_id, improvement_id, who, at, text)
select i.team_id, i.id, $il$Claude$il$, '2026-09-09T12:01:47.000Z'::timestamptz,
$il$9 September: Paul has added both connectors, so the admin permission block is cleared. Replaced by a login failure. Kept as a blocker rather than ticked off, because the four items underneath it are still just as stuck. Screenshare with Brad is the agreed next step.$il$
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i001$il$;

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i002$il$, $il$Ticketplan and Pier Protect must be separable$il$, $il$Data & schema$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-08T16:01:00.000Z'::timestamptz, 1, array[$il$i039$il$]::text[], '{}'::text[], null, null, false, false, $il${"Oliver": "2026-09-09T11:29:08.359Z"}$il$::jsonb,
$il$Ticket.io landed in the Pier Protect lake and is a Ticketplan company. On 17 September Oliver hit it again: Veronika Pfeiffer is a Ticketplan contact sitting in the Pending Review queue in Pier Lead Lake, with a draft written for her, and nothing on the row says which product she belongs to. He only knows because he remembers.

WHAT IS NEEDED

1. A PRODUCT FIELD ON THE COMPANY, as an enum: Pier Protect, Ticketplan, Both, Other, Unknown. This is the company's home book. Contacts and touches inherit it, and a contact can override it, because one person at one company can be worked for the other product.

2. THE COMPANY HEADER SHOWS IT, next to the name, not buried in a field list. Oliver asked for this in those words: it has to be clear where a company mainly sits.

3. A BADGE ON EVERY OUTREACH ROW AND CONTACT CARD. Small, always visible, never hidden behind a filter. The badge is what prevents a mistake; a filter only helps when you remember to set it.

4. A PRODUCT SWITCH AT THE TOP OF THE APP: Pier Protect, Ticketplan, Both. It filters every view, not only Outreach, and it stays set while Oliver moves between Companies, Contacts, Outreach and Today, because the point is to focus on one book for a stretch of work. Default Both, with the badges on, so nothing is ever silently hidden.

5. EVERY COUNT RESPECTS IT. Volume, Pending Review, Awaiting Reply, reply rate, momentum. Those five numbers on the Outreach header are currently two products added together, which makes each of them true of nothing.

BACKFILL IS LIST-BASED, NOT A GUESS PER RECORD. The Ticketplan contacts came in from the Ticketplan book and the Ticketplan monday workspace, so they can be marked as a set. Anything not on that list is Pier Protect until someone says otherwise. Unknown is a value Brad can filter on, not a blank.$il$,
$il$PRODUCT IS NOT A LABEL, IT IS A ROUTING KEY. This is the argument for a schema field rather than a coloured chip. Almost everything downstream already differs by product and the system currently cannot tell:

  THE PITCH DIFFERS. Pier Protect sells device protection into retailers and telcos. Ticketplan sells refund protection into ticketing and events. A draft written from the Pier Protect wedge and sent to a ticketing contact is not slightly off, it is about the wrong product.

  THE VOICE DIFFERS. Ticketplan has its own identity and must not carry Pier branding. Ticketplan German writes du by default; Pier Protect does not.

  THE CHANNEL RULES DIFFER. Ticketplan email goes through monday, because there is no Outlook access on the Ticketplan address. So an email route proposed for a Ticketplan contact is one Oliver cannot actually use.

  THE SCORING DIFFERS. Annual devices sold, refurbished, SIM-free, and the deal heuristic at 8 percent on phones and 6 percent on laptops and tablets mean nothing for a ticketing platform. The company scoring in i071 will rank Ticketplan companies on Pier Protect inputs and produce nonsense unless it knows which book it is scoring.

SO THE FIELD DOES FOUR JOBS: it picks the wedge, the voice, the channel and the scoring model.

IT ALSO MATTERS FOR REPORTING. Pier Protect and Ticketplan are separate lines for Oliver, so any read of how the pipeline is doing has to be per product. At the moment no number in the system can be split.

AND THE CONNECTION REQUEST BUDGET IS SHARED WHILE THE PRODUCTS ARE NOT. Twenty a day, see i072, spent across two books with no way to say how many went to each. That is what i039 is about, and it cannot be built until this field exists.

SAME PATTERN AS i041, i086 AND i093. Product and pipeline position are independent facts, so they are two fields. Worth saying because the tempting shortcut is to encode product inside an existing status, a list name or a tag, and it will break the same way.

ONE THING TO WATCH. Both is a real value, not a fudge. A large events retailer could genuinely be worked for both. It should be rare and deliberate, and if the backfill produces a lot of Both, that means the list was not clean, not that the companies are ambiguous.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i003$il$, $il$Replace P0 / P1 / P3 with a derived next_step$il$, $il$Lovable UI$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-08T16:02:00.000Z'::timestamptz, 3, array[$il$i036$il$]::text[], array[$il$i025$il$,$il$i029$il$,$il$i030$il$]::text[], null, null, false, false, $il${"Brad": "2026-09-14T22:51:59.664Z"}$il$::jsonb,
$il$Oliver: we've got P0, P1, P3, which is confusing. Do not merge it into the score, they answer different questions. Score = how good is this company. next_step = what do I do about it and when. Derive nightly: research now, source leads, outreach ready, walk the checkout, waiting, nothing. Full reasoning in section 8.4 of the master handover.$il$,
$il$$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i004$il$, $il$Group level duplicate approach guard$il$, $il$Guards$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-08T16:03:00.000Z'::timestamptz, 2, '{}'::text[], array[$il$i005$il$,$il$i047$il$]::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Four group collisions surfaced in five days and one is live: getgoods.com is a Conrad Electronic company and C316 Conrad is already Contacted. Before any send, check whether a sibling under the same parent_group is Contacted or In conversation. This guard does not exist today.$il$,
$il$$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i005$il$, $il$Every guard must fail closed$il$, $il$Guards$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-08T16:04:00.000Z'::timestamptz, 2, array[$il$i004$il$,$il$i030$il$,$il$i044$il$,$il$i089$il$]::text[], '{}'::text[], null, null, false, false, $il${"Oliver": "2026-09-09T11:30:56.188Z"}$il$::jsonb,
$il$The previous cooldown guard read if date > today and silently passed every row where the date was NULL. 37 percent of withdrawn rows, unnoticed for a month. A null, missing or unparseable value must BLOCK, never pass.$il$,
$il$$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i006$il$, $il$Estimates must never share a column with stated figures$il$, $il$Data & schema$il$, $il$Brad$il$, $il$must$il$, $il$done$il$, $il$Oliver$il$, '2026-09-08T16:05:00.000Z'::timestamptz, 1, '{}'::text[], '{}'::text[], $il$Brad$il$, '2026-09-14T18:43:44.927Z'::timestamptz, false, false, $il${}$il$::jsonb,
$il$A Claude estimate and a partner stated number must be visually and structurally distinct. On the sourcing board estimates render in orange, labelled estimated (Claude), and cannot be written into the stated column. Took three attempts to get right. Do not collapse them.$il$,
$il$$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i007$il$, $il$Wire the four layer draft stack$il$, $il$Voice$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-08T16:06:00.000Z'::timestamptz, 4, array[$il$i026$il$,$il$i037$il$]::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Not one skill. Pier Rules for sales logic, pier terminology for register, the right Architect for the message type, then the personal voice on top. Oliver's voice applies to only two of the six draft types: first message after CR accepted, and warm reply in a live email thread. See 002_DRAFT_STACK_manifest in the handover pack.$il$,
$il$$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i008$il$, $il$Hold the four draft layers as versioned rows in Supabase$il$, $il$Voice$il$, $il$Brad$il$, $il$must$il$, $il$done$il$, $il$Oliver$il$, '2026-09-08T16:07:00.000Z'::timestamptz, 4, '{}'::text[], array[$il$i001$il$]::text[], $il$Brad$il$, '2026-09-14T18:43:11.950Z'::timestamptz, false, false, $il${"Oliver": "2026-09-09T11:21:36.329Z"}$il$::jsonb,
$il$Pasted copies go stale. It has already happened twice: the EA bundle drifted nine files behind in August, and pier terminology on claude.ai is behind the console copy right now. One source, and stamp every draft with the versions that produced it so drift is visible.$il$,
$il$$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i009$il$, $il$Move to Monday button$il$, $il$Integrations$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-08T16:08:00.000Z'::timestamptz, 5, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Wire the existing button. This retires AddToCRM at 70 pounds a month.$il$,
$il$$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i010$il$, $il$Connection status not mirroring$il$, $il$Integrations$il$, $il$Brad$il$, $il$must$il$, $il$done$il$, $il$Oliver$il$, '2026-09-08T16:09:00.000Z'::timestamptz, 1, '{}'::text[], '{}'::text[], $il$Brad$il$, '2026-09-14T18:43:55.278Z'::timestamptz, false, false, $il${}$il$::jsonb,
$il$A contact showed Accepted in Lovable but the connection state was empty, and he is a first degree connection. Oliver is sending the LinkedIn URL.$il$,
$il$$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i011$il$, $il$Source leads for these companies, as a headline in Today$il$, $il$Lovable UI$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-08T16:10:00.000Z'::timestamptz, 5, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$New companies that have passed research need to trigger the LinkedIn step. Oliver: exactly, there needs to be a section that tells me source leads for those.$il$,
$il$$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i012$il$, $il$Funnel view$il$, $il$Lovable UI$il$, $il$Brad$il$, $il$nice$il$, $il$open$il$, $il$Oliver$il$, '2026-09-08T16:11:00.000Z'::timestamptz, 6, '{}'::text[], '{}'::text[], null, null, false, false, $il${"Brad": "2026-09-20T14:41:41.766Z"}$il$::jsonb,
$il$Oliver: it tells me where am I starving, where's there a bottleneck, where do we have wastage. Stages, counts and conversion between them, filterable by country and product. Answers Mark's what does your pipeline look like in one screen.$il$,
$il$$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i013$il$, $il$Campaigns section$il$, $il$Outreach & drafting$il$, $il$Brad$il$, $il$nice$il$, $il$open$il$, $il$Brad$il$, '2026-09-08T16:12:00.000Z'::timestamptz, 6, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Brad's suggestion. The right home for the revised cooldown, a monthly nurture cadence rather than a hard six month block, and for the events coming up. Manual editor, add contacts to a campaign, cadence per campaign.$il$,
$il$$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i014$il$, $il$Buying signals feed the timing slot$il$, $il$Research agent$il$, $il$Both$il$, $il$nice$il$, $il$open$il$, $il$Oliver$il$, '2026-09-08T16:13:00.000Z'::timestamptz, 6, '{}'::text[], array[$il$i001$il$]::text[], null, null, false, false, $il${"Oliver": "2026-09-15T13:06:54.643Z"}$il$::jsonb,
$il$The score has a timing component that is deliberately inert because nothing feeds it. Signals ranked by strength: a published RFP, a carrier switch, a new finance partner, hiring a Head of Partnerships, a checkout relaunch, funding. The bump must be time boxed and decaying, never a permanent score change. Store with a date, a source URL and an expiry.$il$,
$il$$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i015$il$, $il$Email and phone enrichment$il$, $il$Integrations$il$, $il$Brad$il$, $il$nice$il$, $il$open$il$, $il$Brad$il$, '2026-09-08T16:14:00.000Z'::timestamptz, 6, '{}'::text[], array[$il$i031$il$]::text[], null, null, false, false, $il${"Oliver": "2026-09-09T11:33:58.985Z"}$il$::jsonb,
$il$Brad pays for a platform. Wire the API so there is a reveal button on the contact card.$il$,
$il$$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i016$il$, $il$Delete button straight to deleted companies$il$, $il$Lovable UI$il$, $il$Brad$il$, $il$nice$il$, $il$open$il$, $il$Oliver$il$, '2026-09-08T16:15:00.000Z'::timestamptz, 5, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Currently you set a company to out of scope and it lands in the deleted companies archive. A direct delete button would be quicker.$il$,
$il$$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i017$il$, $il$LinkedIn button on the contact card$il$, $il$Lovable UI$il$, $il$Brad$il$, $il$nice$il$, $il$open$il$, $il$Oliver$il$, '2026-09-08T16:16:00.000Z'::timestamptz, 5, '{}'::text[], array[$il$i032$il$]::text[], null, null, false, false, $il${}$il$::jsonb,
$il$It is in the table but not on the card itself.$il$,
$il$$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i018$il$, $il$Reply Classification enum is too small$il$, $il$Data & schema$il$, $il$Both$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-08T16:17:00.000Z'::timestamptz, 1, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$37 of 990 touches classified, 343 touches with no outcome, and no Monday hand off date. This is why the success metric is currently unmeasurable. Raise the enum before cutover.$il$,
$il$$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i019$il$, $il$Do not automate outbound LinkedIn deep links$il$, $il$Integrations$il$, $il$Both$il$, $il$parked$il$, $il$open$il$, $il$Oliver$il$, '2026-09-08T16:18:00.000Z'::timestamptz, null, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$The Find leads button opens a LinkedIn keyword search and does not work well. The Google string version works better, but arriving at LinkedIn from an external link is plausibly how automation gets detected, and that bit us before. Keep deep links out of any automated flow.$il$,
$il$$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i020$il$, $il$Title matching alone picks the wrong people at scale$il$, $il$Research agent$il$, $il$Both$il$, $il$parked$il$, $il$open$il$, $il$Oliver$il$, '2026-09-08T16:19:00.000Z'::timestamptz, null, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Chibo has 273 people with matching titles and around ten Head of Partnerships who serve client partners rather than external ones. Keep a human in that loop rather than auto sourcing on title.$il$,
$il$$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i021$il$, $il$Calibrate the 1.5 percent conversion rate against a real partner$il$, $il$Data & schema$il$, $il$Oliver$il$, $il$parked$il$, $il$open$il$, $il$Oliver$il$, '2026-09-08T16:20:00.000Z'::timestamptz, null, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Every traffic derived volume scales linearly off this assumption. At 3 percent every figure doubles. One partner's real visits to orders ratio would tighten fifty rows at once. The single highest value measurement available.$il$,
$il$$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i022$il$, $il$Edit fields inline in the Companies view$il$, $il$Lovable UI$il$, $il$Brad$il$, $il$nice$il$, $il$open$il$, $il$Oliver$il$, '2026-09-09T08:10:00.000Z'::timestamptz, 5, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$The Companies view is read only today. Industry, Product Line, Parent Group, Tracking, Country and Category all need editing in place, without opening the record. Oliver marked this low priority.

Worth pairing with the audit table so an inline edit records who changed it and when, otherwise the fastest way to change data becomes the least traceable one.$il$,
$il$$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i023$il$, $il$Adjustable column widths in the tables$il$, $il$Lovable UI$il$, $il$Brad$il$, $il$nice$il$, $il$open$il$, $il$Oliver$il$, '2026-09-09T08:11:00.000Z'::timestamptz, 5, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Drag to resize columns so the view can be adapted on the fly. Oliver marked this low priority. Worth remembering the widths per user so it does not reset every visit.$il$,
$il$$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i024$il$, $il$MediaMarkt Saturn policy URL does not load$il$, $il$Data & schema$il$, $il$Both$il$, $il$nice$il$, $il$open$il$, $il$Oliver$il$, '2026-09-09T08:12:00.000Z'::timestamptz, 5, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$C119 MediaMarkt Saturn. The Policy URL field holds two links and neither loads. Refresh them, and add a periodic link check across Policy URL and Source URLs that flags dead ones for re-research rather than letting them quietly decay.$il$,
$il$Why it matters beyond one link: the policy URL is the evidence behind the IPID test, which is what decides greenfield versus incumbent. A dead link means the verdict can no longer be checked. MediaMarkt is a real incumbent, Zurich Gruppe Deutschland on an exclusive partnership to at least 2035, with claims through AQILO, so the verdict itself is not in doubt here. The general problem is link rot across the evidence fields.

Worth a periodic link check on Policy URL and Source URLs, flagging dead ones for re-research rather than letting them quietly decay.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i025$il$, $il$Comments or instructions field on company and lead, routable to the research agent$il$, $il$Research agent$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-09T08:13:00.000Z'::timestamptz, 3, array[$il$i003$il$,$il$i040$il$]::text[], array[$il$i001$il$]::text[], null, null, false, false, $il${"Oliver": "2026-09-15T13:06:56.870Z"}$il$::jsonb,
$il$A free text field on a company or a contact where Oliver writes what he has noticed or wants checked. Two routes out of it: someone applies it by hand, or it is queued for the research agent. Where it is queued, the agent writes its answer back underneath rather than overwriting the note. The note carries who wrote it, when, and a status of raw, actioned or queued.$il$,
$il$NOTE ON PRIORITY: Oliver raised this alongside two low priority items but I have put it in Must have, so knock it back if you disagree. The reason is that this is the correction loop, and right now there is not one. On 4 September Oliver walked eight checkouts and two of them overturned a confident desk verdict, both in the optimistic direction: DiTech.at had a Wertgarantie policy the research had missed, and BA-Computer could not be shown to sell a device at all. Those corrections only survived because he typed them into a Claude session that happened to be open. Without a field like this, the single highest quality input to the data has nowhere to go.

Suggested shape: the note carries who wrote it and when, a status of raw, actioned or queued for research, and where it was queued the agent writes its answer back underneath rather than overwriting the note.$il$);

-- exactness gate: every item in this part must hash to the value computed from the source file
do $verify$
declare bad text;
begin
  select string_agg(e.item_key, ', ' order by e.item_key) into bad
  from (values
    ('i000', 'aa4fadcbfccb56705115bdcf0ce36f3b', 1),
    ('i001', 'a341c932a14e38f0ff1be7ebca89102c', 1),
    ('i002', '82a3b51b2a900081581ba8c73b9ef754', 0),
    ('i003', 'b9c700caa543f6bac84b7b7676fd008a', 0),
    ('i004', '36f0a1a982db65cd1d3447841ba94980', 0),
    ('i005', 'dcde1bbcb48b0a634d62054cebd96710', 0),
    ('i006', '856baeab4a2989621fc4f2dadfd2d820', 0),
    ('i007', 'd52c0fafac6ef1d0968891937f97da49', 0),
    ('i008', 'b005459b2a717ae3212ca285d19d1314', 0),
    ('i009', '90154cd39238048f3783e91b87c4ef62', 0),
    ('i010', '0d454f229c10df67cb4f0226456773db', 0),
    ('i011', '8796eaaf3aa2bb490e6c62569ebeec17', 0),
    ('i012', 'a9883a8a3bc58c6e129a14def9ce3b59', 0),
    ('i013', '44ac455422a7714fd1b370ed35d4435d', 0),
    ('i014', 'fb2268f35024db940b4ef049e876d864', 0),
    ('i015', '2fc6bccb27824421ad82a52e95f0cda5', 0),
    ('i016', 'be8058e6336f027aeedf3248200f7031', 0),
    ('i017', '4c9eb4627c95dd2fe2d67751f2571f8a', 0),
    ('i018', '02d06fee6d4d3ee23d4389b9313b9818', 0),
    ('i019', 'f228eec03d4d3d6a55ec930388654a12', 0),
    ('i020', 'a644826dac1bc334f50ac6bba58333db', 0),
    ('i021', 'dd851aad0c2cd8b3a1850bf66c57fb75', 0),
    ('i022', '847b51a02e9ad7e297ed8d0774fabca3', 0),
    ('i023', '302f299cd03f9db4c6a0541af31db47d', 0),
    ('i024', '83edc3b64c946eea0d85bd0c3fe6c17a', 0),
    ('i025', '4ce0a97bc0418237ecc99bc6e2febf45', 0)
  ) as e(item_key, src_md5, n_comments)
  left join public.improvements i
    on i.item_key = e.item_key and i.team_id = (select id from public.teams limit 1)
  where i.id is null
     or e.src_md5 is distinct from md5(concat_ws(chr(31),
      i.title, i.category, i.owner, i.priority, i.status, coalesce(i.raised_by,''), i.detail, i.notes,
      coalesce(i.done_by,''), array_to_string(i.blocks,','), array_to_string(i.blocked_by,','),
      coalesce(i.build_wave::text,''), i.pinned::text, i.hidden::text,
      to_char(i.created_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), coalesce(to_char(i.done_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),''), i.seen_by::text,
      coalesce((select string_agg(concat_ws(chr(31), c.who, to_char(c.at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), c.text), chr(30) order by c.at)
                from public.improvement_comments c where c.improvement_id = i.id), '')));
  if bad is not null then
    raise exception 'F18.5 import: rows differ from the source export: %', bad;
  end if;
end
$verify$;
