-- 118b_f18_5_improvement_log_import_p03
-- F18.5(b) improvement log import, part 3 of 12: i036..i045 (10 items, 0 comments).
-- GENERATED by scripts/gen_improvement_log_import.py from 260920_lovable_improvement_log_export.json - do not edit by hand.
-- Text is dollar-quoted and must stay byte-for-byte; the DO block at the end rolls the part back if not.

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i036$il$, $il$Next action shows in the activity area, and you can schedule one by hand$il$, $il$Outreach & drafting$il$, $il$Both$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-09T11:15:46.000Z'::timestamptz, 3, array[$il$i063$il$,$il$i064$il$,$il$i106$il$]::text[], array[$il$i003$il$]::text[], null, null, false, false, $il${}$il$::jsonb,
$il$The activity area on a company and on a person should say what happens next here and when. Two lanes into the same field, visibly different. Derived from the standard process, which is i003. Or set by hand: pick an activity, pick a date, add a one line steer, and it beats the derived one until it is done. The critical part: scheduling creates the ACTIVITY, not the message. The draft is written on the day it comes up, against the thread as it stands that morning, and the guards are re-checked then too.$il$,
$il$LANE 1, THE STANDARD PROCESS. Derived, nightly, from where the record actually is: research now, source leads, outreach ready, walk the checkout, waiting, nothing. That derivation is i003, which this item sits on top of. This item is the surface, i003 is the value. Show where it came from, so a derived action reads as derived and nobody argues with it as if a person set it.

LANE 2, SET ONE BY HAND. Add an activity on the record: LinkedIn DM, chaser, InMail, email, call, or a plain check-back. Pick the date. Add a one line steer if there is one, for example do not mention price, or he asked to be chased after the trade show. A hand set action beats the derived one and is marked as such until it is done or cleared.

THE PART THAT MATTERS MOST: THE DRAFT IS WRITTEN ON THE DAY, NOT WHEN YOU SCHEDULE IT. Scheduling a chaser for the 3rd creates the ACTIVITY, not the message. On the 3rd it lands in Today and drafting starts then, reading the thread as it stands that morning. A draft written three weeks early is written against a conversation that has since moved, and it will get sent anyway because it is sitting there looking finished. This is the single thing to get right in this item.

GUARDS FIRE AT SEND TIME, NOT AT SCHEDULE TIME. Between scheduling and firing, someone can opt out, a deal can open in Monday, a cooldown can start, or the market rule can change. So the scheduled activity is re-checked against DNC, the company level pause, the cooldown and the market legality rule on the morning it comes up, and it is blocked there if any of them now say no. A scheduled action is a request to draft, never a permission to send.

NEVER BLANK. Completing an activity has to produce the next one. That is a standing rule, not a preference: every contact carries a next action and a date, a no becomes a six month check back, and only a hard opt out is exempt. Closing an activity with nothing behind it should not be possible without explicitly choosing the check back or the opt out.

Worth Brad knowing the scope: this is the follow up engine, which today runs on Monday plus Make.com plus in thread Outlook chasers. Bringing it into Lovable is what lets that be retired, so it is worth building the scheduling properly rather than as a reminder field.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i037$il$, $il$Drafts come out as one solid block with no line breaks$il$, $il$Outreach & drafting$il$, $il$Both$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-09T11:26:34.000Z'::timestamptz, 4, array[$il$i051$il$]::text[], array[$il$i007$il$]::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Every draft arrives as a single paragraph. The Rodolphe Surdez InMail is four distinct thoughts run together with no break anywhere. Oliver flagged it as not urgent today but a must before volume goes up, and he is right about that ordering.

It is an AGENT level fix, not a UI one. Add the paragraph shape to the drafting rules and lint it, so the break survives regardless of which surface renders the message. Also check the storage and the send path preserve newlines, because a draft that is correct in the field and flat in the inbox is the same defect one layer down.$il$,
$il$WHY IT MATTERS MORE AT VOLUME, which is the part worth being precise about. A wall of text is the single most reliable visual signal of a bulk send. A recipient decides whether to read in about a second, on a phone, and shape is what they read first, before a word of the argument. So this is not tidiness, it costs reply rate, and it costs it on exactly the messages Oliver has spent the most effort on.

THE SHAPE THE RULES ALREADY IMPLY. The Reply Ladder is ASK, GIVE, EXIT, and the welcome DM anatomy is their pain first, then fix and gain in one breath, then a short informal ask. Those are three moves, so they are three paragraphs. The structure is already written down, the drafts are simply not rendering it.

SUGGESTED RULE, to be argued with rather than accepted:
1. One thought per paragraph, blank line between. Three or four paragraphs for a DM or an InMail body.
2. No paragraph longer than roughly three lines as it renders on a phone, which is about 40 words.
3. The ask sits alone on the last line. It is the only thing that must not be buried.
4. Greeting on its own line, sign off on its own line.
5. No bullet lists in a first touch. Bullets read as a deck, not as a person typing.

LINT IT RATHER THAN HOPE. predraft already lints and fails closed on other rules, so add a check: a body over roughly 60 words with no blank line in it fails. A rule that is only prose gets ignored the moment the model is in a hurry, which is the whole lesson of the enforcement over prose principle.

CHECK THE PIPE, NOT JUST THE PROMPT. Three places can eat a newline between Claude and the recipient: the JSON write to Supabase, the textarea rendering it, and the Sales Nav or email send call. Confirm a break typed by hand into the draft field survives all the way to a real sent message before concluding the agent is at fault. It may be both.

LANGUAGE NOTE. German sentences run longer than English ones, so the same word count reads as a denser block. If anything the German drafts need the breaks more, not less.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i038$il$, $il$Country filter across the whole app, with DACH as one click$il$, $il$Lovable UI$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-09T11:28:27.000Z'::timestamptz, 5, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Oliver wants to work one market at a time. A country selector that takes several countries at once, with DACH as a single preset and Germany, Austria and Switzerland selectable on their own. It filters everything on the screen: the drafts in Pending Review, the thread list, the company and contact lists, and the category counts down the left.

Two things that decide whether it is trustworthy. The headline numbers at the top, Volume, Pending Review, Awaiting Reply, Positive Replies, must move with the filter or they contradict the list underneath. And the selection has to survive a reload, because a filter that resets every morning gets abandoned by Wednesday.$il$,
$il$WHICH COUNTRY FIELD IT READS, and this is the part to get right. A contact and their company do not always sit in the same country. Rodolphe Surdez is CEO France and Benelux at Save Group. For choosing what to SEND, the contact's country is the one that matters, because it drives language and legality. So filter on the contact's country, fall back to the company's home country when the contact has none, and show which one was used.

DO NOT FILTER ON COUNTRIES SELLING IN. That is a different field and a different question, see item i027. A German retailer that also ships to France should not appear under a France filter, or the legality rule gets read off the wrong value.

SHARED VOCABULARY WITH i027. Both this and the Countries Selling In picker need the same canonical country list. Define the enum once and have both read it. Not a blocking dependency, just do not end up with two lists that drift.

PRESETS WORTH HAVING, taken from the territory sequencing already in use:
  DACH, meaning Germany, Austria, Switzerland
  Core, meaning DACH plus France, Spain, Italy
  Benelux, meaning Netherlands, Belgium, Luxembourg
  and every country individually
United Kingdom is Jack's territory. It should be selectable, because the data is there, but worth a marker on it so it is never picked by accident.

THE FILTER SHOULD TELL YOU THE CHANNEL RULE, which is where this becomes more than convenience. Cold email is permitted for France, Belgium, Netherlands and Switzerland-targeted only. Germany, Austria, Spain, Luxembourg, Italy and Czechia are LinkedIn led. So when the filter is set to Germany, the email channel should visibly not be an option rather than relying on someone remembering. The rule already exists as a guard; this is the natural place to surface it, and it turns a filter into a safeguard.

ONE PRACTICAL NOTE. Filtering to a single country will make the Pending Review number small, which is the point. Do not let an empty state read as an error. Empty means that market is clear, which is the good outcome.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i039$il$, $il$Set LinkedIn send limits and split the allowance between Pier Protect and Ticketplan$il$, $il$Outreach & drafting$il$, $il$Both$il$, $il$nice$il$, $il$open$il$, $il$Oliver$il$, '2026-09-09T11:31:27.000Z'::timestamptz, 6, '{}'::text[], array[$il$i002$il$]::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Oliver wants to say, in one instruction: allow 60 connection requests to Pier Protect leads scoring above 90, and 40 to Ticketplan leads scoring above 80. Illustrative numbers, but that is the shape. A cap per product line, a score floor per product line, and a period the cap resets on.

The thing that makes it worth building rather than just useful: LinkedIn's invite allowance is ONE pool on ONE account. Ticketplan and Pier Protect are already competing for it, and right now nothing says so. Whoever sources on a given morning wins the week by accident. This turns an invisible race into a decision.

Low priority per Oliver, and it depends on i002 splitting the two product lines first.$il$,
$il$TWO DIFFERENT BUDGETS, DO NOT COLLAPSE THEM. Connection requests reset weekly and the ceiling is LinkedIn's, not ours. InMail credits are monthly, currently 50 a month accruing to a 150 cap, and they are money rather than a rate limit. A single cap field cannot express both, so each needs its own period and its own allocation.

THE REAL DESIGN QUESTION IS WHAT HAPPENS WHEN A BUCKET RUNS DRY. If Pier Protect has only 40 leads above 90 this week, do the spare 20 go to Ticketplan, or stay unused? Both answers are defensible. Unused protects the split from being quietly eaten by whichever product has more loose supply. Reallocating protects the volume. Recommendation: hold them by default, show the shortfall plainly as 20 of 60 unfilled, and let Oliver release them with one click. The shortfall is itself the useful signal, because it says sourcing is behind in that product, and silently backfilling from the other one hides exactly that.

THE TWO SCORES ARE NOT ON THE SAME SCALE, so 90 and 80 are not comparable numbers and the thresholds must stay per product. The Pier Protect score is GWP 40, incumbent 30, territory 15, wedge 15. There is no equivalent model for Ticketplan yet. Until there is, a Ticketplan threshold has nothing real to read, so either build that scoring first or let the Ticketplan bucket run on a plain cap with no floor and say so.

UNASSESSED IS NOT ZERO, and a threshold is where that rule gets broken. A company scoring 90 with three of four components assessed is not the same as 90 with all four. If the filter reads the number alone it will systematically favour thinly researched companies, because a smaller denominator is easier to score high against. Show confidence next to the score in this view, and consider a minimum confidence alongside the minimum score.

IT HAS TO RESPECT THE GUARDS, not sit beside them. A cap of 60 is 60 SENDABLE leads, after the cooldown, the do not contact list, the company level pause and the Monday deal suppression have run. A budget counted before the gate would promise volume that the gate then refuses, which is worse than no budget at all.

PAIRS NATURALLY WITH THE COUNTRY FILTER in i038. Cap by product and floor by score gets you a queue; adding the market gets you a week of work you can actually plan.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i040$il$, $il$Drain Intel Staging into Supabase, then retire the page$il$, $il$Data & schema$il$, $il$Both$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-09T12:08:02.000Z'::timestamptz, 3, '{}'::text[], array[$il$i025$il$]::text[], null, null, false, false, $il${}$il$::jsonb,
$il$While the connector is down, research findings are being written to a separate page called Intel Staging, each one carrying the exact fields and values it should change. When the connector works, someone walks that list and applies it.

On naming, so nothing gets confused: the page is INTEL STAGING and the Supabase table it eventually lands in is intel_staging. Staging is the whole point of the word. It is a queue, not a record, it is emptied as entries are applied, and no report, score or guard is ever allowed to read from it. If anything starts reading it, it has stopped being staging and we have quietly built a second source of truth.

This is a manual stand in for i025, the comments and instructions field routable to the research agent. When i025 ships, Intel Staging retires into it.$il$,
$il$WHY IT IS A MUST RATHER THAN HOUSEKEEPING. The single highest quality input we have is Oliver noticing something the desk research missed. On 4 September a checkout walk overturned two confident verdicts. Those corrections survived only because a Claude session happened to be open. A staging page fixes the losing, but a staging page nobody drains is just a nicer place to lose things, so the draining is the item.

TWO KINDS OF ENTRY, AND THEY MUST NOT BE APPLIED THE SAME WAY.
To apply: agreed, evidenced, no argument. These can be written in a batch.
Needs a decision: changes a verdict, or contradicts what is already on the record. Every one of these gets read by a person before anything is written. Overwriting a greenfield verdict silently is exactly how bad data enters, and a batch job cannot tell the difference.

WHAT SHOULD SURVIVE THE DRAIN. Applying a finding writes the value, but the value alone loses why we believe it. Keep the evidence: source URL, who found it, when, and what it replaced. That belongs in an evidence trail, not in the staging queue, and it is the same requirement as the source per fact rule the research instructions already carry. Do not conflate the two tables: intel_staging empties, the evidence trail grows.

DIFF, DO NOT OVERWRITE. Same rule as the re-research item i029. If a field already holds a value and the finding disagrees, the disagreement is the most valuable output. Surface it, do not quietly replace.

A CLEAN DEFINITION OF DONE for this item: intel_staging holds zero entries in To apply, every Needs a decision entry has been looked at, and the page itself is either retired or clearly marked as superseded by i025. Leaving it running alongside i025 is the failure mode, because then there are two places to write a correction and people will use both.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i041$il$, $il$Header controls and the fields below them do not talk to each other$il$, $il$Lovable UI$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-09T12:19:01.000Z'::timestamptz, 5, array[$il$i029$il$]::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$On City Compliance, C1342, the chips at the top of the record carry the same facts as the controls further down, and the two do not move together. Change one and the other stays where it was. Confirmed on BOTH Status and Research Stage, so treat it as a pattern across the header rather than two separate bugs.

Research Stage makes it worse than a stale label. The chip in the header is itself an EDITABLE dropdown, offering Untouched, Light triage, Deep research done and Outdated, and there is a second dropdown for the same field lower down the record. Two live controls writing the same fact, out of step. Whichever one is saved last wins, and nothing on screen tells you which that was.

It is not cosmetic. A wrong value at the top of the record is read first and doubted least. Someone sees Untouched in the header, sends the company to research, and it was researched last week.

The rule to build to: one fact, one piece of state. A header control is a VIEW of the field, never a second copy of it, and both re-render from the same source the moment either is used.$il$,
$il$THE LIKELY CAUSE, worth checking before writing sync code. Header chips that go stale are usually rendered once from the record as it was when the drawer opened, and never resubscribed. If that is what is happening here, the fix is to bind the chip to the same state the control writes to, not to add a handler that copies one into the other. Two-way copying between two sources of truth is how you get a field that flickers between values, and it will be worse than the bug.

A HARDER QUESTION UNDERNEATH IT, and this one is worth Brad and Oliver actually deciding rather than coding around. On this record OoS appears as the PRIORITY, and Out of Scope appears again as the STATUS lower down. Those look like one fact stored in two fields. If they are, syncing the header to the field only tidies the symptom while leaving two places to disagree.
The lake's own vocabulary says dead equals Out of Scope, as a status. Priority holding a value of OoS is Priority being used to answer a question it was not built for, which is the same confusion item i003 exists to clear up. So: settle whether OoS is a status or a priority, keep it in one field, and derive anything else that needs to show it.

RESEARCH STAGE IS THE URGENT HALF, because i029 is about to make that value DERIVED from the research date. A derived value with two hand editable controls pointed at it is a contradiction waiting to happen: the nightly job writes Outdated, someone sets Deep research done in the header, the field below still says something else, and the research queue picks up the wrong set. Settle this before i029 lands, or i029 inherits the mess. The same test applies to every other chip on the header, not just these two. A derived value shown in a chip that does not resubscribe will be wrong the day after it changes, and nobody will notice because nobody edits it by hand.

A CHEAP TEST FOR DONE: open a record, change the field at the bottom, and watch the chip without reloading. Then change it from the header side and watch the field. Then reload and confirm the value that survived is the one you set last, not the one that happened to render first.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i042$il$, $il$Add a contact from wherever one is discovered, and pull the details rather than typing them$il$, $il$Lovable UI$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-09T12:22:43.000Z'::timestamptz, 5, '{}'::text[], array[$il$i031$il$]::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Raised twice now, so raised to must. On Reconciliation the only routes out of a card are Assign to contact, which lists people already on record, and Dismiss. If the person is not in Lovable there is nowhere to put them.

Add Create new contact, here and anywhere else a person is picked up who is not on file.

PULL THE DETAILS, DO NOT TYPE THEM. Oliver asked whether the person's information can come from LinkedIn instead of being filled in by hand. Yes, but through the browser, not a server: that is i045, the extension that pushes a profile into Lovable. Fetching profiles server side is the behaviour that gets LinkedIn accounts restricted, and the account is already throttled. So the flow is: create the contact from what the card already knows, then enrich it from the profile with one press while the page is open.

THE REPLY COMES WITH THEM. Creating an empty contact and losing the message is the same data loss in a tidier shape. The message becomes touch one, dated as it happened, on the new record.

A NUANCE ON THIS PARTICULAR CARD: it is one of Oliver's OWN outbound messages, not an inbound reply. So the contact to create is the person it was sent TO, which is in the thread rather than on the card. Create new contact has to read the thread, not the sender line, or it will create a contact for Oliver.$il$,
$il$THE DUPLICATE RISK IS THE REAL ONE, and this card shows it perfectly: five different Patricks suggested for one message, none of them the right one. The right one is Patrick Bruecker. With Create new contact one click away, a sixth Patrick is the likely outcome. So the create flow runs the same duplicate check a sourced lead runs, on name AND company AND profile URL, and offers Assign where it finds a probable match.

WHAT CAN BE PULLED AND WHAT CANNOT. From the profile, with the extension: name, headline, role, company, location, both URLs, and the dated profile snapshot. What cannot be pulled is email, which is a separate enrichment problem, and anything about the company, which is research. So expect a contact created this way to arrive complete on the person and empty on the company, which is i046 and i055.

THE COMPANY USUALLY WILL NOT EXIST EITHER, and one created this way has had no research. It lands as Untouched with no priority so it enters triage rather than appearing in a worklist as though somebody had looked at it.

NOT EVERY REPLY IS A PROSPECT. Kevin Jones on that same screen is a recruiter. So the counterpart to Create new contact is a Dismiss that asks why, which is i074, and where the reason is not a prospect it should offer to mark the company Out of Scope rather than just clearing the row.

WHY IT SITS UNDER i031. Creating a contact writes a profile URL, and until the LinkedIn and Sales Nav fields are separated that write lands in the wrong column and has to be unpicked later.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i043$il$, $il$Dismiss in Reconciliation has to be reversible, and it should say why$il$, $il$Lovable UI$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-09T12:26:27.000Z'::timestamptz, 5, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Oliver pressed Dismiss on a reply from Patrick Bruecker instead of assigning it to his contact. There was no obvious way back. Dismiss is a one click action with a lasting consequence and no visible undo, sitting next to the action you actually want, on a screen you work at speed.

Two things. Make it reversible, from the card or from the Actions Log tab, which already exists and may be most of the answer. And make Dismiss ask why: not a prospect, wrong person, already handled, noise. The reason is the only signal we get about what keeps landing in this tab.

Brad, check the Actions Log first. If a dismiss can already be reversed there, this is a discoverability job rather than a build one, and saying so is the fix.$il$,
$il$WHY THIS IS A MUST AND NOT TIDYING, stated plainly so it can be argued with. A dismissed reply does not delete the message, it leaves the reply UNLINKED from the contact. The contact's history then shows no inbound answer. Every guard we have reads touch history, so an unlinked reply makes a person who has already answered look like someone who never did. That is precisely how a contact gets chased after replying, or messaged as though fresh. The rule that a missing touch is worse than no data is already written down; this button creates missing touches by accident.

THE PATTERN, NOT THE INCIDENT. This is the second problem on the same screen in one day. The other is i042, no way to create a contact when the person is not on file. Both come from the same shape: two routes out of a card, one of which quietly discards, and no third route and no way back. Worth Brad looking at the screen as a whole rather than patching two buttons.

AN EASY MISTAKE TO MAKE HARDER. Dismiss sits immediately beside Assign to contact. Separate them, or give Dismiss a lighter weight than the action you usually want. Cheap, and it removes most of the occasions for the undo to be needed.

WORTH CHECKING AT THE SAME TIME: whether Patrick was offered in the suggested contacts list at all. If he was not, the matching failed before the click did, and the reason five Christians can be suggested for one message while a real match is missed is the thing actually worth fixing.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i044$il$, $il$Monday suppression is applied on some screens and not others$il$, $il$Guards$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Claude$il$, '2026-09-09T12:29:37.000Z'::timestamptz, 2, array[$il$i066$il$]::text[], array[$il$i005$il$]::text[], null, null, false, false, $il${}$il$::jsonb,
$il$The rule is that a company in a live Monday deal freezes the whole company in the Growth Engine. Lovable applies it in some places and not in others, which is worse than either applying it everywhere or nowhere, because you cannot tell which screen you are looking at.

APPLIED: the company picker in the New contact dialog leaves Monday companies out. That is why Oliver could not find spusu. Correct behaviour, done silently, which causes its own problem, see i046.

NOT APPLIED: the unmatched replies queue on Reconciliation. A reply from Patrick Bruecker at asgoodasnew, C290, In Monday, Monday deal, Active Lead, with every contact flagged BLOCKED worked in Monday not the Lake, was offered up for assignment to a Growth Engine contact like any other.

What it should do, on every surface: contacts of a Monday company do not appear in worklists, do not accept drafts, and are not offered for matching. Where one surfaces anyway it is labelled as a Monday company and routed there, never silently omitted and never silently allowed.$il$,
$il$ONE RULE, ONE IMPLEMENTATION. The picker and the reconciliation queue evidently each decide for themselves whether to honour the Monday flag. That is the actual defect: the rule is written twice and only one copy is right. It should be a single check that every surface calls, the way the lake scripts all call one gate. Worth Brad auditing which surfaces call it today, because two are known and the rest are unknown.

AND WHEN IT SUPPRESSES, IT SHOULD SAY SO. Silent omission taught Oliver that spusu was missing rather than blocked. See i046. Suppressed means visible, greyed, labelled and unusable, not absent.

WHY THIS IS THE MOST EXPENSIVE GUARD TO GET WRONG. Every other guard failing produces a wasted message. This one failing produces two Pier people approaching the same company from two directions with two different pitches, while a real deal is live. It is the one mistake a partner actually notices.

IT IS NOT HYPOTHETICAL TODAY. See Intel Staging n004. Save Group C285 is being worked in the Growth Engine with a Pending Review InMail to its CEO France and Benelux, and the lake's own notes on both records say Save Group and asgoodasnew are probably the same group. asgoodasnew is the live Monday deal. That InMail is currently one approval away from being exactly this failure.

THE GUARD HAS TO WORK AT GROUP LEVEL, NOT COMPANY LEVEL, which is why this and i004 belong together. Suppressing asgoodasnew alone does nothing if the sister company sits in the same list unflagged under a different name and domain. The lake already carries the group text on both records; Lovable needs a real link between them so a guard can traverse it.

FAIL CLOSED, per i005. If the Monday status of a company cannot be determined, treat it as suppressed and say so, rather than assuming it is free. An unnecessary hold costs a day. A double approach on a live deal costs the deal.

WORTH CHECKING ON IMPORT, not just going forward: how many lake companies carry a Monday flag or a BLOCKED note in their contact notes, and how many of those are unflagged in Lovable right now. That number is the size of the exposure and it can be counted today.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i045$il$, $il$Push a contact into Lovable straight from LinkedIn or Sales Nav$il$, $il$Integrations$il$, $il$Both$il$, $il$nice$il$, $il$open$il$, $il$Oliver$il$, '2026-09-09T12:29:37.000Z'::timestamptz, 6, '{}'::text[], array[$il$i031$il$]::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Oliver wants a button on a LinkedIn or Sales Navigator profile that pushes that person into Lovable, instead of retyping them into the New contact dialog. The intent is to replace AddToCRM, which today costs about 70 pounds a month and pushes to monday rather than to Lovable.

Worth knowing before anyone scopes this from scratch: a LinkedIn to monday Chrome extension already exists in Oliver's console, under 01_Claude Main Folder. Retargeting that at Lovable is likely a far smaller job than building one, and it is the first thing to look at.

It must capture BOTH LinkedIn URLs, the plain /in/ profile AND the Sales Navigator /sales/lead/ record, as two separate fields per i031, plus name, role, company and a dated profile snapshot. And it must run the same duplicate check a sourced lead runs before it writes anything.$il$,
$il$IT HAS TO BE A BROWSER EXTENSION OR A BOOKMARKLET, not a server side fetch. Sales Nav has no public API for this and pulling profiles from a server is the behaviour that gets accounts flagged. A button the person presses while looking at the profile is a human reading a page, which is ordinary.

NOT IN CONFLICT WITH THE PARKED CAUTION IN i019, but the line matters. i019 is about not building automated outbound LinkedIn deep links into a scripted flow at volume. One profile, one press, is not that. A bulk capture that walks a search result page IS that, so do not build the bulk version even though it will be tempting once the single one works.

CAPTURE IS NOT PERMISSION TO CONTACT. A pushed contact lands as sourced, and it still has to pass the normal gate before anything is drafted to it. If the button also queues outreach, the gate has been bypassed by a convenience feature, which is the classic way a guard dies.

THE PROFILE SNAPSHOT IS THE BIT PEOPLE SKIP. Capturing name and URL is easy and half the value. The dated text summary of who this person is and what they have posted recently is what makes the first message personal, and it can only be captured while the page is open. Take it at push time.

COST CASE, since it replaces something we pay for. AddToCRM is about 70 pounds a month. i009 already retires it for the lake to monday direction. This item covers the LinkedIn to Lovable direction. Do both and the subscription goes.$il$);

-- exactness gate: every item in this part must hash to the value computed from the source file
do $verify$
declare bad text;
begin
  select string_agg(e.item_key, ', ' order by e.item_key) into bad
  from (values
    ('i036', 'cd852af789537d171edd007f9aee636d', 0),
    ('i037', '7135b0f96f51154349c172a8fdab0664', 0),
    ('i038', 'b65870fb0f7b1bd47326a579561e663f', 0),
    ('i039', '0b80fcabc745302ea7f982fb3cdad397', 0),
    ('i040', '84d9834688b4981a63f394136f376d34', 0),
    ('i041', 'c9641d783378fc95e0ee52992b492634', 0),
    ('i042', 'f5674293d9eeabf850b21a7bc6f12aac', 0),
    ('i043', 'c0b91e9c5f66ce5517a19bedef68211c', 0),
    ('i044', '530f9f65a7c1dfdf7b994281dd49c3e9', 0),
    ('i045', '16964235bf794594117b551e7956ca25', 0)
  ) as e(item_key, src_md5, n_comments)
  left join public.improvements i
    on i.item_key = e.item_key and i.team_id = (select id from public.teams limit 1)
  where i.id is null
     or e.src_md5 is distinct from md5(concat_ws(chr(31),
      i.title, i.category, i.owner, i.priority, i.status, coalesce(i.raised_by,''), i.detail, i.notes,
      coalesce(i.done_by,''), array_to_string(i.blocks,','), array_to_string(i.blocked_by,','),
      coalesce(i.build_wave::text,''), i.pinned::text, i.hidden::text,
      to_char(i.created_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), coalesce(to_char(i.done_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),''), i.seen_by::text,
      coalesce((select string_agg(concat_ws(chr(31), c.who, to_char(c.at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), c.text), chr(30) order by c.at)
                from public.improvement_comments c where c.improvement_id = i.id), '')));
  if bad is not null then
    raise exception 'F18.5 import: rows differ from the source export: %', bad;
  end if;
end
$verify$;
