-- 118b_f18_5_improvement_log_import_p11
-- F18.5(b) improvement log import, part 11 of 12: i900..i999 (2 items, 0 comments).
-- GENERATED by scripts/gen_improvement_log_import.py from 260920_lovable_improvement_log_export.json - do not edit by hand.
-- Text is dollar-quoted and must stay byte-for-byte; the DO block at the end rolls the part back if not.

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i900$il$, $il$TEST ITEM: prove the log works, then tick it off$il$, $il$Lovable UI$il$, $il$Both$il$, $il$nice$il$, $il$done$il$, $il$Claude$il$, '2026-09-09T11:00:36.000Z'::timestamptz, null, '{}'::text[], '{}'::text[], $il$Brad$il$, '2026-09-09T16:04:46.537Z'::timestamptz, true, false, $il${"Oliver": "2026-09-09T11:02:38.066Z"}$il$::jsonb,
$il$Brad, this one is a throwaway. It exists so we both confirm the page really is shared and saving before we start working from it. Five steps, about a minute.

1. Press Brad in the top right corner. There is no sign-in on this page, so that button is the only thing telling the log who you are. Check the chip next to it says saving and shared, live. If it says local only, stop and tell Oliver, because nothing you do will reach him.

2. Write a comment on this item. Anything, hello is fine. Press Add comment or hit Enter.

3. Change the Owner dropdown on this item from Both to Brad. That proves field edits save too, not just comments.

4. Check both ends of the page. Top left, next to the title, there is a last updated stamp that should now carry your name and the time. Scroll to the very bottom and the Latest activity list should show your two actions. That is the audit trail, so we can each see what the other has touched without asking.

5. Have a quick look at Group by, Build order in the filter bar. That is the view worth using when you pick up work, because it puts the items in the order that avoids building things twice, and each card shows what it unlocks and what it is waiting on.

Then tick this item off with the checkbox and it disappears from the top of the list. Message Oliver on WhatsApp when you have done it so he knows the shared log is live.

One caveat worth knowing. Everyone sees the same list, so if we both edit the same field at the same second, the last write wins. In practice that never bites, but do not treat it as a document you can both type into at once.$il$,
$il$$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i999$il$, $il$For Brad, from Oliver$il$, $il$Lovable UI$il$, $il$Brad$il$, $il$nice$il$, $il$open$il$, $il$Oliver$il$, '2026-09-18T10:45:00.000Z'::timestamptz, null, '{}'::text[], '{}'::text[], null, null, false, true, $il${}$il$::jsonb,
$il$★ ☆ ★ ☆ ★ ☆ ★ ☆ ★ ☆ ★ ☆ ★ ☆ ★ ☆ ★ ☆ ★ ☆ ★ ☆ ★

   ██████╗ ██████╗  █████╗ ██████╗
   ██╔══██╗██╔══██╗██╔══██╗██╔══██╗
   ██████╔╝██████╔╝███████║██║  ██║
   ██╔══██╗██╔══██╗██╔══██║██║  ██║
   ██████╔╝██║  ██║██║  ██║██████╔╝
   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝

          I S   A   R O C K S T A R

★ ☆ ★ ☆ ★ ☆ ★ ☆ ★ ☆ ★ ☆ ★ ☆ ★ ☆ ★ ☆ ★ ☆ ★ ☆ ★

That is it. That is the whole item. Oliver put it here on 18 September 2026.$il$,
$il$This entry carries no task and needs no reply. It sits outside the log's own view on purpose, so it is only met by whoever goes looking through the data rather than the page.$il$);

-- exactness gate: every item in this part must hash to the value computed from the source file
do $verify$
declare bad text;
begin
  select string_agg(e.item_key, ', ' order by e.item_key) into bad
  from (values
    ('i900', 'f1c8b341271f937e957f0911d48271af', 0),
    ('i999', 'a749cd22fd9ffaae3564691fed364176', 0)
  ) as e(item_key, src_md5, n_comments)
  left join public.improvements i
    on i.item_key = e.item_key and i.team_id = (select id from public.teams limit 1)
  where i.id is null
     or e.src_md5 is distinct from md5(concat_ws(chr(31),
      i.title, i.category, i.owner, i.priority, i.status, coalesce(i.raised_by,''), i.detail, i.notes,
      coalesce(i.done_by,''), array_to_string(i.blocks,','), array_to_string(i.blocked_by,','),
      coalesce(i.build_wave::text,''), i.pinned::text, i.hidden::text,
      to_char(i.created_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), coalesce(to_char(i.done_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),''), i.seen_by::text,
      coalesce((select string_agg(concat_ws(chr(31), c.who, to_char(c.at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), c.text), chr(30) order by c.at)
                from public.improvement_comments c where c.improvement_id = i.id), '')));
  if bad is not null then
    raise exception 'F18.5 import: rows differ from the source export: %', bad;
  end if;
end
$verify$;
