-- 118b_f18_5_improvement_log_import_p06
-- F18.5(b) improvement log import, part 6 of 12: i069..i070 (2 items, 3 comments).
-- GENERATED by scripts/gen_improvement_log_import.py from 260920_lovable_improvement_log_export.json - do not edit by hand.
-- Text is dollar-quoted and must stay byte-for-byte; the DO block at the end rolls the part back if not.

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i069$il$, $il$Sparring brief: monday, Supabase and what a clean sheet GTM system would look like$il$, $il$Data & schema$il$, $il$Both$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-15T12:34:41.000Z'::timestamptz, 6, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$The full document is in the background below. Open Background and reasoning, select it and copy, or point your Claude at this page and it will read it.

It sets out what exists in Supabase today, what exists in monday, how the two map onto each other, and then a clean sheet answer to a different question: what a go to market system for Pier would look like if nothing had to be replicated. Five nouns, how next is decided, what integrates and what stays human, what to stop doing, and what it costs.

Brad, section 13 is addressed to you and asks you to spar against it before building any of it. Section 9 is the list of decisions it needs from us. Oliver's ask from the call: have a crack at it, put a time estimate against it, and then the three of us take it to Mark.

Source file: 260915_PIER_gtm_system_clean_sheet_design_v01_OM_C2.md in the handover pack.$il$,
$il$# Clean sheet: what a go-to-market system for Pier should look like if nothing had to be replicated

**v01, 15 September 2026, Oliver Müller (written with Claude Code), C2 Commercial in Confidence**
**For: Brad Gordon and his Claude. Read after `260915_PIER_lovable_single_gtm_system_crm_analysis_v02_OM_C2.md`. Where the two disagree, this file is the design intent and the v02 file is the inventory.**

---

## 0. The question this answers

The v02 analysis asked "what would it take to move what monday does into Supabase and Lovable". This file asks the harder question Oliver put afterwards: **if we had a clean sheet, with Supabase already holding the top of the funnel and monday holding the deals, what is the best system, and how much of what we built in monday deserves to exist at all?**

The method is simple. Every field, board, automation and habit in monday was tested against one question: **is this a fact somebody learned, or a workaround for something monday could not compute?** Facts survive. Workarounds die. What is left is small.

---

## 1. Verdict in one page

**Roughly two thirds of what monday holds should not be rebuilt.** Not because it was wrong, but because most of it exists to make a spreadsheet-shaped tool behave like a database.

| What monday has | Count | Verdict | Why |
|---|---|---|---|
| Typed status vocabularies (Deals Stage, Companies Sales Status, Companies Status, Contacts Type, Contacts Priority, Pipeline health, Health, Stage status, Basis, Activity flag) | 10 | **Keep 1** (Stage) | Everything else is either derivable from stage, touches and tasks, or a duplicate of another field. Companies carries three overlapping status columns today |
| Deal columns typed or stamped by hand or automation | about 25 | **Keep 8** | company, owner, stage, expected close, park-until, three value overrides. Next Step Date, Last interaction, Stage changed, Days in stage, Health, Stage status, Basis, Weighted, Year-3, Business case tick, Country, Deal Source (derivable), the mirrors and the flag all go |
| Activities board rows | 676 | **Keep about 60** | 450 or so are "I sent a message" records that Supabase already holds as touches. Only calls, meetings and internal to-dos are tasks. The board is 70% duplication of the message log |
| Activity type labels (live and dead) | 18 | **Keep 0** | A touch is a channel plus a position in a sequence, two fields that already exist. A chaser is not a type of thing |
| Automations on Deals and Activities | 17 | **Keep 1** (un-park) | Fourteen exist to stamp dates, move groups or copy flags so that a formula somewhere can read them. In a database those are queries |
| Dashboard widgets | about 16 | **Keep 6 numbers and 3 charts** | Half the widgets exist because monday cannot filter a widget by a computed value, so a column was created to hold the value. The weekly report is what Mark asked for; the dashboard was our idea |
| Emails & Activities timeline | one per item | **Keep, and make it the centre** | The one thing monday does that is a fact record, not a workaround. Rebuild it as a single interactions table across every channel and every object |
| monday Notetaker transcripts | per meeting | **Keep the transcript, not the tool** | Transcripts come from Teams through Graph; the summary comes from our own draft stack, which knows Pier's rules |
| Outlook BCC integration | one address | **Kill** | Lossy, breaks for Ticketplan items, needs a human to remember the BCC. Capture from the mailbox instead |
| AddToCRM | one subscription | **Kill** | The Supabase watchers already do it |
| Two logins for one person | | **Kill** | One account, one person, roles on it |

**The design that falls out has five nouns and one verb.** Company, Person, Interaction, Deal, Play. The verb is "next", meaning the system always knows the next action for every record and Oliver only ever sees a list of them. Section 3 defines the nouns; section 4 the engine; section 5 the channels; section 6 the human's day; section 7 what to stop doing in Claude Code as well.

---

## 2. The principle, stated once

**A fact is recorded once, at the moment it happens, by the channel it happens in. Every status, health, priority, value and next step is computed from facts. Nothing is typed that could be derived, and nothing is derived twice.**

Test any proposed field against it. monday fails the test about 40 times. The current Supabase passes it nearly everywhere in the cold funnel (the chase state machine, the refusal gate, the send effects function) and this file simply extends the same discipline over the deal.

Corollaries, because each has cost us before:

1. **A typed date rots.** Next Step Date was typed and read "overdue" on Revendo while the thread was live that morning. Dates come from tasks and touches, never from a cell.
2. **A status vocabulary is a query with a name.** "Engaged", "Open Deal", "Active Lead" and "In Monday" are four spellings of "has a live conversation". One query, no spellings.
3. **A workaround becomes a field, and the field becomes a habit.** Pipeline health had to be refreshed by hand before each meeting because monday could not compute it. Nobody questioned it for a month.
4. **Approval is the one human step in a send, and it should be the only one.** Today a chaser is typed into a Draft column, pasted into Outlook, sent, marked Done, given an Outcome, and the Next Step Date is re-derived. Six actions for one email. The target is one: approve.

---

## 3. The object model: five nouns

### 3.1 Company

Exactly what `companies` is today, minus the fields that duplicate a deal or a derived state. Keep: identity, country (as a key, not free text), parent group, product line, research stage, insurance state as data, size history with rungs, owner, score. Drop: `opportunity_status` as a typed field, `tracking` for anything except the EUREFAS flags, `monday_deal_id`, `account_owner`. The company's **engine mode** (cold, in conversation, in deal, partner, lost, parked) is a view over deals and interactions, never a column.

### 3.2 Person

Exactly what `contacts` is today. It already carries the chase state machine, the promise of quiet, DNC, cooldown and provenance. Two additions only: `deal_contacts` roles when a deal exists, and the monday Language dropdown carried into `formality` where blank. Drop from the monday side: Type, Priority, Seniority as free text.

### 3.3 Interaction

**This is the centre of the clean sheet and the one table monday never had.** One row per touch in any channel, in either direction, on any object: a connection request, a LinkedIn message, an InMail, an email, a call, a meeting, an event conversation, a note. `outreach_log` is already 85% of this; it needs `deal_id`, `direction`, `email_thread_id`, `meeting_id` and touch types for call, meeting and note. The timeline of a company, a person or a deal is then one query with three joins, and "last interaction" is `max(occurred_at)`, never a stamp.

Two consequences. The Activities board disappears as a concept, because a sent message is an interaction, not a completed task. And the monday habit of logging "Sales Navigator" as an activity after sending disappears, because the watcher already recorded the send.

### 3.4 Deal

A company in a commercial conversation, with eight typed fields: company, owner (plus optional co-owner), stage, expected close date, park-until date, and three value overrides (attachment, GWP per policy, Pier share) with a note. `deal_stage_history` gives every date the old board stamped. Value, weighting, basis, days in stage, moving or stuck, next step and last interaction are all views (v02 section 5).

**Recommend collapsing the stage ladder from seven to five.** Opportunity and Discovery are weighted 5% and 10% with no calibration and no won deals; the boundary between them has never been defined in writing; and 17 of 28 active deals sit in Discovery today, which says the distinction is not doing work. Proposed ladder: **Conversation, Proposal, Negotiation, Won, Lost**, with **Parked** as a state on any open stage (a deal parked at Proposal is still a Proposal) carrying the revisit date. Weights: Conversation 10, Proposal 30, Negotiation 60. This is Mark's to rule on, because the weights are his; the recommendation is recorded here so it is asked, not assumed.

**Drop from the deal:** Year-3 run-rate (context nobody reads; a note in the value method is enough), the Business case checkbox (derive from a document of type business_case existing on the deal), Country (the company's), Deal Source as a typed status (derive from the first interaction's channel; keep a typed override only for Referral and Event, which cannot be inferred), Current IPID (belongs on the company's insurance state).

### 3.5 Play

The generalisation that makes cold outreach and deal follow-up one system instead of two. A play is a rule set: **trigger, steps, exit conditions, approval mode, caps**. The current chase engine is one hardcoded play (CR sent → accepted → first message → 7 days → chaser, capped per channel). Brad's campaigns idea is the same thing with a manual enrolment trigger. Deal follow-up is the same thing with a different voice layer and a different approval rule. Nurture after a lost deal or a withdrawn CR is the same thing on a monthly rhythm with content instead of asks.

```
plays
  id, team_id, product_line, name, purpose enum (cold_sequence | deal_followup | nurture | event_followup | reengagement),
  trigger enum (cr_accepted | positive_reply | deal_opened | deal_lost | manual_enrol | event_attended | signal_detected),
  approval enum (approve_each | approve_batch | auto_within_caps),
  active bool, created_by, version

play_steps
  play_id, step_no, delay_days, channel, message_type (maps to voice_assets.applies_to),
  cap_per_contact, stop_on enum[] (reply | dnc | deal_open | promise_of_quiet | cooldown | unsubscribed)

play_enrolments
  play_id, contact_id, deal_id nullable, enrolled_at, current_step, next_due_on, state (active | paused | exited), exit_reason
```

The chase engine becomes the runner of every enrolment whose `next_due_on` is today, calling the same gate (`fn_evaluate_gates`) and the same drafter, and producing rows in the same draft queue. One engine, one queue, one approval screen, for a cold InMail chaser and for a warm email to Revendo alike. **This is the single largest efficiency gain available**, because today the cold side runs in Supabase and the warm side runs in a person's head plus a monday column.

### 3.6 The two small nouns

**Task**: a non-message action with a due date and an owner (call, meeting to hold, send the proposal, internal). About 60 of monday's 676 activities. **Note**: free text pinned to any object, the monday Updates tab. Both feed the timeline. Neither holds a draft.

---

## 4. The engine: how "next" is decided

Every record has one computed `next_step` and one `next_due_on`. Today reads them, ordered by value at stake. This replaces Health, Stage status, Pipeline health, Next Step Date, the P0 to P3 priority scale and the afternoon board at the same time.

| Record | Derived from | Reads as |
|---|---|---|
| Company, cold | research stage, score, contact count, gates | research now / source leads / outreach ready / walk the checkout / nothing |
| Person, in a play | enrolment step, gate result, reply state | approve draft / answer reply / waiting until date / blocked: reason |
| Deal | open tasks, last interaction, stage age, park date | task due: call Matthias / no next step planned / stale 21 days / stuck 61 days in Conversation / revisit due |
| Play | enrolments due, caps remaining | 7 drafts to approve, 12 sends scheduled |

Health as seven labels was a monday workaround for "I cannot sort a board by a computed value". In Lovable the sort is the health. Keep the labels only as filter chips on the deal board.

---

## 5. Channels: what integrates, how deep, and what stays human

| Channel | Capture (in) | Send (out) | Human step |
|---|---|---|---|
| LinkedIn and Sales Navigator | Already done: three watchers, alias matching, reply classification, idempotent capture | **Stays manual** (LinkedIn terms; account safety). One click opens the thread with the approved draft on the clipboard; the watcher records the send | Click, paste, send |
| InMail | As above; credit ledger exists | Manual, same one click; credit deducted by the ledger at send | Approve, click, paste |
| Email (Outlook) | **New: Graph mailbox capture**, both directions, matched to persons and deals by address and thread; unmatched queue; calendar noise filtered | **New: system send after approval** via Graph on the rep's behalf, at a scheduled time, only where `markets.cold_email_legal` or the thread is warm. This is where the six-actions-per-chaser problem goes to one | Approve (batch, each morning) |
| Phone and Teams | Teams transcript via Graph after the meeting; call logged as an interaction with one tap | n/a | Hold the call; accept the drafted summary and tasks |
| Events | Event list pasted as intake; attendees matched or created; enrolled in the event follow-up play | Through the plays | Approve the batch |
| LinkedIn content (Oliver's posts) | Post published → interaction of type content on every connection who engaged | Manual | Write the post |
| Web signals | Research agent on Supabase (blocked on the Paul permission) writes `signals` with decay | n/a | None |

**What deliberately stays human, and why.** Sourcing people on LinkedIn (judgement about who decides; title matching fails at scale, the Chibo lesson). Sending on LinkedIn (terms of service). Approving every send (Oliver's rule, and the only quality gate that has never failed). Holding the conversation. Everything around those four is the system's job.

---

## 6. Oliver's day on the clean sheet

1. Open Today. Six counts: replies to answer, drafts to approve, deal tasks due, deals needing a decision (stuck, slipped, revisit due), companies to source, blocked overnight.
2. Answer replies. Each reply card shows the classification, the thread, and a drafted answer already queued; approve or edit.
3. Approve drafts in one pass: cold chasers, first messages, warm deal follow-ups, nurture touches, all in one queue, each card showing who, why now, the wedge, the guard result and the play it belongs to. Email sends itself at 09:30. LinkedIn drafts wait on the clipboard for the click.
4. Work the deal tasks: the call, the proposal, the meeting. The summary and next tasks are drafted from the transcript.
5. Paste anything new into the intake: an event list, a name Mark mentioned. It is triaged overnight.
6. Friday: the report goes to Mark without anyone building it.

Six steps, one system, one login. Against today's day: the afternoon board in Claude Code, the Lovable queue, monday's Open - Today view, Outlook, Sales Navigator and the LinkedIn inbox, with the chaser skill bridging two of them.

---

## 7. What to stop doing, including in Claude Code

The clean sheet is not only about monday. Several things in the console exist because two systems had to be kept in step, and they go when there is one.

| Retire | Because |
|---|---|
| `create-monday-chaser` skill, `monday_guard.py`, the 2,000-character rule | No monday column to fill |
| `outreach_gate.MONDAY_ACTIVE`, `is_monday_company`, the `In Monday` tracking flag, `BLOCKED - worked in Monday` next actions | Engine mode is derived from deals |
| The afternoon board artifact and its LOG-BACK loop | Today in Lovable is the board, and sends record themselves |
| `predraft.py`, `verify_batch.py`, `check_cards` as separate Python gates | `fn_evaluate_gates` already is the gate; the lint rules that still live only in Python (F61 no-repetition, the message-card format) move into the drafter |
| The xlsx lake and `lake_common.py` guardrails | Frozen since 3 September; Supabase is the record |
| Cowork briefs for lead sourcing as documents | Sourcing queue in Lovable is the brief; the watcher is the return path |
| Living Context entries as the way rules reach the drafter | `voice_assets` and `pier_ea_documents` are versioned in the database; Claude Code pushes a new version, nothing is re-typed |

Claude Code's remaining job becomes what it is good at: writing and versioning the rules and voice layers, running the research agent, doing the occasional analysis like this one, and being the place Oliver argues with the system. Daily operation lives in Lovable.

---

## 8. What this costs and what it removes

| Removed | Note |
|---|---|
| monday seats for Pier Protect | account stays for Ticketplan |
| AddToCRM | GBP 70 a month |
| monday Notetaker | once meetings have a home |
| Make.com | nothing live |
| Otter.ai | already gone |
| The double-entry hour | logging sends in two places, refreshing snapshot columns, re-deriving the monday freeze |

| Added | Note |
|---|---|
| Graph app registration and admin consent | the one external dependency; Paul or the M365 admin |
| Brad's build time for blocks A to D of the v02 file plus the plays engine | plays is the addition this file makes; it replaces the chase engine's hardcoded sequence rather than sitting beside it |
| Supabase compute | negligible at this volume |

---

## 9. Decisions this asks for

| # | Decision | Owner | Recommendation |
|---|---|---|---|
| 1 | Collapse seven stages to five with Parked as a state | Mark | Yes; the Opportunity and Discovery split has no definition and no calibration |
| 2 | System-sent email after approval, on the rep's behalf, in legal markets and warm threads | Oliver, Phil for compliance comfort | Yes, batch-approved each morning; LinkedIn stays manual |
| 3 | Plays as the single automation concept, replacing the hardcoded chase sequence | Brad, Oliver | Yes; build the runner once, express the current sequence as the first play |
| 4 | Retire the Activities board concept; tasks only for non-message actions | Oliver | Yes; a sent message is an interaction |
| 5 | Drop Health and Stage status as labels; keep them as sort and filter | Oliver, Jack | Yes; the labels were a monday workaround |
| 6 | Weekly report first, dashboard second | Mark | Yes; the report is what was asked for |
| 7 | Retire the console tooling in section 7 as each Lovable block lands | Oliver | Yes, one block at a time, never before |

---

## 10. What this file does not claim

It does not size Brad's effort; the v02 file does that per block, and the plays engine adds roughly one block of similar size. It does not settle the stage weights or the 2,000 device floor, both of which are Mark's. It assumes Graph consent is obtainable on the Pier tenant. And it keeps every guard from the master handover exactly as it is: the clean sheet is about removing workarounds, never about removing the things that refuse.

---

## 11. The blueprint on one page

This is the same design as sections 3 to 6, condensed to the page Brad can put next to his screen.

**One database, one front end, one login per person. Five record types and nothing else.**

| Record | What it is | Typed by a human | Everything else |
|---|---|---|---|
| Company | the account: identity, country, group, product line, research state, insurance state, size history, score | name, source, product line, owner | mode (cold, in conversation, in deal, partner, lost, parked), status, priority: all computed |
| Person | a decision maker at a company | LinkedIn URL when sourced; roles on a deal | connection state, chase state, cooldown, DNC, formality: captured or derived |
| Interaction | every touch in every channel, both directions, on any record: CR, LinkedIn message, InMail, email, call, meeting, event conversation, note | nothing; the channels write it | the timeline, last interaction, reply state |
| Deal | a company in a commercial conversation | company, owner, stage (Conversation, Proposal, Negotiation, Won, Lost), expected close, park-until, three value overrides | value, weighting, basis, days in stage, moving or stuck, next step, health |
| Play | a rule set: trigger, steps, exit conditions, approval mode, caps | the play definition, once | enrolments, due dates, drafts |

Plus Task (call, meeting, internal to-do) and Note.

**The engine.** Every record carries one computed next step and one due date. Today is the list of those, ordered by value at stake. Plays are the one automation: cold sequence, deal follow-up, nurture, event follow-up and re-engagement are the same runner with different triggers, voice layers and approval rules. Every draft passes the existing refusal gate and lands in one approval queue.

**The channels.**

| Channel | In | Out |
|---|---|---|
| LinkedIn and Sales Navigator | the three watchers, already live | manual by LinkedIn's terms; one click opens the thread with the approved draft on the clipboard, the watcher records the send |
| Email | Graph mailbox capture, both directions, matched by address and thread, calendar noise filtered, no BCC | sent by the system after approval, at a scheduled time, only in legal markets or warm threads |
| Phone and Teams | transcript via Graph after the meeting; a call logged with one tap | summary and follow-up tasks drafted from the transcript |
| Events | attendee list pasted in, matched, enrolled in the event play | through the play |
| Oliver's LinkedIn posts | engagement captured as interactions on connections | manual |
| Web signals | research agent writes decaying signals that lift a company's next step | none |

**The day.** Open Today, six counts. Answer replies, each with a drafted answer waiting. Approve drafts in one pass; email sends itself at 09:30, LinkedIn waits for the click. Work the deal tasks. Paste anything new into the intake. On Friday the report reaches Mark without anyone building it.

**What stays human, deliberately.** Choosing who to source, sending on LinkedIn, approving every send, holding the conversation.

**What it removes.** monday for Pier Protect, AddToCRM, the Notetaker once meetings have a home, the Outlook BCC address, the second login, and the console plumbing that kept two systems aligned.

---

## 12. Two ways to get there, and a suggested path

The v02 analysis describes **Path A: replicate**. Build the deal layer as monday has it, migrate, then simplify. Its strength is that nothing is lost and every acceptance test maps to something visible today. Its weakness is that it carries the workarounds across before removing them, so the team builds Health labels and stage-status logic it will delete a month later.

This file describes **Path B: clean sheet**. Build the five nouns and the plays engine, migrate only facts (deals, interactions, tasks, transcripts), and never build the workarounds. Its strength is a smaller system. Its weakness is that it changes the stage ladder and the approval habits at the same time as the tooling, which is two changes at once for the people using it.

**Suggested path: B for the schema, A for the sequencing.** Build the clean data model from day one (it is smaller than the replicated one, so it is not more work), but bring the reps across in the v02 order: deals first, then tasks and timeline, then email, then reporting, then decommission. Concretely:

1. **Week 1.** Interaction table extended (`deal_id`, `direction`, `email_thread_id`, call and meeting types), `deals` with five stages and a `parked_until` state, `deal_stage_history`, `deal_contacts`, `tasks`, `notes`, `meetings`, `valuation_standards`, `pipeline_stage_config`, and the views for value and next step. Migrate the 33 monday deals, 60 or so real tasks, and the deal timelines as interactions. Seven monday stages fold into five at import; the mapping is recorded on each stage-history row.
2. **Week 2.** The Deals board and deal page in Lovable. Today gains the deal buckets. The company engine mode goes live and the cold engine respects it. Oliver and Jack work deals in Lovable; monday goes read-only.
3. **Weeks 2 to 4, in parallel.** Graph mail capture in shadow next to the BCC; the plays runner built as a generalisation of the chase engine, with the current cold sequence expressed as play number one and a deal follow-up play as number two. Meetings intake from transcripts.
4. **Week 5.** System-sent email after batch approval switched on for warm threads and legal markets, once the two-week shadow capture is clean. The weekly report goes to Mark from Lovable. Nurture and event plays added.
5. **Week 6.** BCC off, AddToCRM cancelled, Pier Protect workspace in monday archived, console plumbing in section 7 retired one item at a time.

The acceptance tests in the v02 file still apply; add three: a cold chaser and a warm deal follow-up both appear in the same approval queue on the same morning; an approved email to a French contact sends itself at the scheduled time and appears as an interaction on the deal within a minute; a company whose deal is lost enters the nurture play automatically and leaves it the moment a reply arrives.

---

## 13. Brad: spar against this before building any of it

Oliver's instruction is that this design is to be argued with, not mirrored. The 9 September start-here note said the same about the master handover and it produced better decisions than the original. So, before writing a migration:

**Read it looking for the places it is wrong.** Likely candidates, in Oliver's own words where they exist:

1. **Five stages.** Is collapsing Opportunity and Discovery a simplification or a loss of signal? Jack works fewer, larger UK deals; does he need the distinction that Oliver's DACH funnel does not? Ask him.
2. **Plays as the one engine.** Is a warm deal follow-up really the same machine as a cold InMail chaser, or does forcing them together produce a runner with so many exceptions that two simple engines would be cleaner? The test is the exit conditions: if the list of stop reasons is the same for both, one engine is right.
3. **System-sent email.** Does sending on the rep's behalf through Graph create a deliverability, compliance or trust problem that pasting into Outlook did not? Phil should be asked once about the compliance comfort. Is a 09:30 batch better than sending at approval time?
4. **The Interaction table as a single spine.** Is one table for CRs, emails, meetings and notes a clean design or a wide table with many nullable columns? Would `interactions` plus typed satellite tables (`emails`, `meetings`) be easier to query and index?
5. **Derived company mode.** A view that decides whether the cold engine may touch a company is on the critical path of every send. Is a view fast and safe enough, or should the mode be a materialised column maintained by the same triggers that write deals and interactions, with the view as the check?
6. **The retirement list in section 7.** Which of the console guards encode a rule that is NOT yet in `fn_evaluate_gates` or the drafter? The F61 no-repetition lint is one known case. List them before anything is switched off.
7. **What is missing.** Partner management after Won (onboarding, programme reviews, renewals) is out of scope here on purpose. Is that the right cut, or does a Won deal need a home on day one so it does not fall back into a spreadsheet?

**Then report back in this shape**, so Oliver can rule quickly: for each point, agree or disagree, the reason in two or three sentences, and what you would build instead. Where you disagree and the evidence is in the database, run the query and quote the number; that is how the cooldown defect and the group collisions were found. Oliver will read it, rule on the contested points, and the ruling goes into this file as a dated note before the first migration runs.

**Two things are not up for sparring**, because they are the lessons this system has already paid for: every guard fails closed, and Oliver approves every send.
$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i070$il$, $il$Everything that calls out fails with unauthorized: AI edit, Regenerate, Send and Generate draft$il$, $il$Outreach & drafting$il$, $il$Brad$il$, $il$blocker$il$, $il$done$il$, $il$Oliver$il$, '2026-09-15T13:27:11.000Z'::timestamptz, 0, '{}'::text[], '{}'::text[], $il$Brad$il$, '2026-09-18T10:44:12.675Z'::timestamptz, false, false, $il${"Brad": "2026-09-18T10:44:11.634Z", "Oliver": "2026-09-15T13:46:19.837Z"}$il$::jsonb,
$il$BLOCKER, AND IT IS ONE FAULT, NOT THREE. As of 16 September all three actions return unauthorized:
  AI edit: AI edit failed: unauthorized
  Regenerate: unauthorized
  Send now: Send failed: unauthorized, try again or send manually from LinkedIn, see i082

Everything that READS still works. The page loads, drafts render, guardrails generate, the lint scores, the AI state of play panel updates. Everything that ACTS is refused.

Regenerate failing is what settles it. Earlier the open question was whether the model credentials were fine and only certain routes were broken. They are not fine, or the token is not reaching any of them. One credential or one token, not three bugs.

CONFIRMED ACROSS DRAFTS AND CHANNELS: rebuy, Marcel Erian, German InMail on 15 September; Drei, Robert Karl, German LinkedIn DM on 16 September; Digitec Galaxus, Ivana Petrovic, German DM. Different records, channels and instructions, same failure.

Oliver is now copy and pasting messages by hand. That has a cost beyond the time, see the background.$il$,
$il$WHAT TO CHECK, now that it is one fault. The token or key the edge functions use to call out, and whether the user session is being passed through to them at all. Reads go straight to the database, actions go through a function, and only the second kind fails. That is the boundary.
Also worth confirming nothing expired on 15 September, since that is when it started.

SURFACE THE REAL ERROR. Unauthorized on a toast is all Oliver can see. Whatever the function actually returned, status code and body, should be visible or logged where he can quote it. Every one of these currently costs a round trip to Brad, and Brad is away.

THE MANUAL WORKAROUND LOSES THE RECORD, and this is the part that will hurt later. A message copied out and sent by hand is a touch Lovable did not write. The four hourly watcher picks up LinkedIn DMs, so those should reconcile. InMails are the risk: LinkedIn's own export has never contained InMails, so if the watcher does not capture them directly there is no route back and they are gone. See i048.
PRACTICAL SUGGESTION WHILE THIS IS BROKEN: send DMs by hand, because they are recoverable, and hold InMails until send works. If an InMail genuinely cannot wait, write down who and when at the moment of sending, not afterwards.

A REVISION MAY STILL BE WRITTEN ON FAILURE. One draft showed PREVIOUS DRAFTS 3 on a contact where nothing has been sent. Worth checking whether failed AI edits or regenerations leave partial revisions behind, because a silent bad revision is worse than the visible error.

TWO THINGS STILL WORKING WELL, worth saying since this report is all bad news. The guardrails generate correctly and specifically, for instance do not name Helvetia, AIG or Helvetic Warranty by name, do not cite the volume estimate or any commission figures, do not reference Stolle, Teuteberg or any warm intro path. And the AI state of play panel is writing a proper record of what each draft did and why. Both are the hard parts, and neither is affected.

THE SAME SCREENS KEEP SHOWING i067: Beste Gruesse, Oli, now on a fourth draft. And i084 stands, LINT 100 while a displayed guardrail is broken.$il$);
insert into public.improvement_comments (team_id, improvement_id, who, at, text)
select i.team_id, i.id, $il$Claude$il$, '2026-09-16T10:12:58.000Z'::timestamptz,
$il$16 Sept: still failing, now on a LinkedIn DM to Robert Karl at Drei. Different contact, channel and instruction from yesterday, so it is not one bad draft. Two things on this screenshot worth checking. PREVIOUS DRAFTS reads 3 on a contact where nothing has been sent yet, so revisions ARE being created by something; if failed AI edits are among them, that is the silent partial revision risk. And this draft signs off Beste Gruesse, Oliver Mueller in full, where yesterday's signed Oli, which means i067 is inconsistent rather than universal and probably points at two generation paths.$il$
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i070$il$;
insert into public.improvement_comments (team_id, improvement_id, who, at, text)
select i.team_id, i.id, $il$Claude$il$, '2026-09-16T10:19:52.000Z'::timestamptz,
$il$16 Sept, second update: Regenerate also returns unauthorized. That is all three actions, so this is one credential or token rather than three separate faults, and it is the whole action layer. Oliver is copy pasting by hand, which means manual sends during the outage will not be logged. DMs should reconcile through the watcher; InMails probably will not.$il$
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i070$il$;
insert into public.improvement_comments (team_id, improvement_id, who, at, text)
select i.team_id, i.id, $il$Oliver$il$, '2026-09-17T14:00:00.000Z'::timestamptz,
$il$17 Sept, FOURTH FUNCTION AND THIRD DAY. Generate draft now returns unauthorized too, on Frank Pelzer at Vodafone Germany, shown both as a toast and inline in the Outreach tab where the draft should be. So the list is AI edit, Regenerate, Send now and Generate draft. Every function that calls out is down and reads still work, which makes the single credential or token diagnosis as strong as it is going to get without seeing the logs.

IT ALSO CHANGES WHAT THE OUTAGE COSTS. Until now the queue could not be corrected or drained but it could still be worked, because 63 drafts already existed. With Generate draft down, no new draft can be produced at all, so a contact freshly added or freshly accepted cannot be actioned through Lovable in any way. The system is now read only in practice.

WORTH SAYING TO BRAD PLAINLY: this is not four bugs to triage, it is one thing to restore, and every day it stays down the manual workaround writes more rows that i053 and i048 will have to reconcile afterwards.$il$
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i070$il$;

-- exactness gate: every item in this part must hash to the value computed from the source file
do $verify$
declare bad text;
begin
  select string_agg(e.item_key, ', ' order by e.item_key) into bad
  from (values
    ('i069', '1dbb0c3469dacd717eb272e36875eb52', 0),
    ('i070', 'ba20ec0f3a618bab05ad2f6c6d23b745', 3)
  ) as e(item_key, src_md5, n_comments)
  left join public.improvements i
    on i.item_key = e.item_key and i.team_id = (select id from public.teams limit 1)
  where i.id is null
     or e.src_md5 is distinct from md5(concat_ws(chr(31),
      i.title, i.category, i.owner, i.priority, i.status, coalesce(i.raised_by,''), i.detail, i.notes,
      coalesce(i.done_by,''), array_to_string(i.blocks,','), array_to_string(i.blocked_by,','),
      coalesce(i.build_wave::text,''), i.pinned::text, i.hidden::text,
      to_char(i.created_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), coalesce(to_char(i.done_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),''), i.seen_by::text,
      coalesce((select string_agg(concat_ws(chr(31), c.who, to_char(c.at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), c.text), chr(30) order by c.at)
                from public.improvement_comments c where c.improvement_id = i.id), '')));
  if bad is not null then
    raise exception 'F18.5 import: rows differ from the source export: %', bad;
  end if;
end
$verify$;
