-- 118b_f18_5_improvement_log_import_p04
-- F18.5(b) improvement log import, part 4 of 12: i046..i052 (7 items, 3 comments).
-- GENERATED by scripts/gen_improvement_log_import.py from 260920_lovable_improvement_log_export.json - do not edit by hand.
-- Text is dollar-quoted and must stay byte-for-byte; the DO block at the end rolls the part back if not.

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i046$il$, $il$New contact dialog: type to find the company, create it inline, and take both LinkedIn URLs$il$, $il$Lovable UI$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-09T12:29:37.000Z'::timestamptz, 5, '{}'::text[], array[$il$i031$il$]::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Four gaps in the same small dialog. Oliver hit all three on real leads today.

ONE, THE COMPANY PICKER IS A LIST YOU HAVE TO SCROLL, AND IT HIDES THINGS WITHOUT SAYING SO. Oliver hunted for spusu and could not find it. The reason turned out to be that spusu is a Monday company and the picker excludes those. That exclusion is CORRECT, but doing it silently is not: an absent company reads as a missing record, and the obvious next move is to create it again. Show suppressed companies in the results, greyed out, labelled worked in Monday, and not selectable. Then the answer to where is spusu is on the screen instead of being hunted for. It should be a search box: type, and matches appear below. Match on more than the display name, because the display name is often not what someone types. Match the trading name, the legal name, the website domain and the company id, and show country and domain on each result row so near identical entries can be told apart. The record in the screenshot reads Selling Electronics Responsibly FZCO / SER Mobile Phones LLC, which nobody is going to scan for.

TWO, IF THE COMPANY IS NOT THERE THE CONTACT CANNOT BE SAVED AT ALL. Not slower, not clumsier: it does not go in, and Oliver had to abandon a real lead. The search should end with a Create option carrying whatever was typed, so no results flows straight into making the company rather than into a dead end. A company made this way has had no research, so it lands as Untouched with no priority and is visibly marked as created in passing.

THREE, THERE IS ONE LINKEDIN URL FIELD AND THERE SHOULD BE TWO. The dialog takes an /in/ profile. The Sales Navigator /sales/lead/ record is a different thing and it is the one outreach is sent from, while only the /in/ form works for enrichment. Two fields, matching the two columns the lake already holds. This is i031 at the point of entry: if the dialog takes one, every contact created here starts life with the gap we are trying to close.

FOUR, SENIORITY AND FUNCTION ARE FREE TEXT AND SHOULD BE DROPDOWNS. Both are already enums everywhere else. The filter bar behind this dialog counts them: Seniority as C-suite 160, Senior 81, Director 68 and more; Function as Sales 106, Strategy 74, Other 64 and more. Typing them by hand into the create dialog is the one place they can be spelled wrong, and Seniority is read by the sourcing floor, so a typo does not just look untidy, it slips a junior contact past a gate that was meant to catch them. Use the same enum the filters use, do not define a second one.

Raised to a must rather than the nice to have Oliver first called it, because point two is a hard stop on getting data in. Say if you disagree.$il$,
$il$WHY SPUSU WAS HARD TO FIND, corrected by Oliver. Not list length and not spelling. spusu is a MONDAY COMPANY and the picker leaves Monday companies out. The suppression is right. The silence is the bug.

SILENT ABSENCE IS THE MOST EXPENSIVE KIND OF HIDING, because of what the person does next. You look for a company, it is not there, so you conclude it does not exist and you create it. Now there is a duplicate of a company that is in a live Monday deal, and the guard that was protecting it cannot see the new row. The picker prevented one mistake and set up a worse one. Show it, grey it, label it worked in Monday, and let the person read the reason instead of guessing at it.

THE DUPLICATE RISK HERE IS ALREADY REAL. The lake holds THREE spusu records: C456 spusu Austria, C659 spusu Italia, C939 spusu Deutschland GmbH, all marked Monday deal and C939 an Active Lead. A silent picker plus an inline create button is how a fourth gets made. So the create path must check against ALL companies including the suppressed ones, not against the filtered list it is showing.

IT ALSO SHOWS THE SUPPRESSION IS INCONSISTENT RATHER THAN MISSING. The picker honours the Monday flag; the unmatched replies queue in i044 does not. Same rule, two surfaces, two behaviours. Worth finding out which other surfaces honour it before assuming any of them do.

FREE TEXT WHERE AN ENUM EXISTS IS THE SAME DEFECT AS i027, the Countries Selling In field. Worth Brad sweeping the whole app for it once rather than fixing them one screenshot at a time: any field a filter, a score or a guard reads must be a picker, because the number depends on the string matching.

MINIMUM FIELDS ON THE INLINE CREATE: name, website, country. Country because the legality guard reads it and a company with no country cannot safely be drafted to. Everything else waits for research. Do not put a big form in a small dialog.

DUPLICATE CHECK AS YOU TYPE, on the same fields the search matches. Three spusu records already exist, Conrad, getgoods and Voelkner were three, and Save Group and asgoodasnew are probably one group held as two. A create button with no matching behind it is how the fourth appears.

ON THE TWO URLS: neither should be required, because you will not always have both, but the dialog should show which it has and which is missing rather than accepting one silently. A contact with no Sales Nav URL has a dead jump button in i032, and 242 of 665 contacts are already in that state.

A TOOL THAT REFUSES TO STORE WHAT YOU JUST FOUND teaches you to stop putting things in it. The cost is not the two minutes, it is the leads never entered at all, and those are invisible: nobody can count what was abandoned in a dialog. The standing rule is to log every company found, even a non fit, with the reason. This dialog makes that rule impossible to follow at the moment you are trying to follow it.

PAIRS WITH i042 AND i045. All three are the same underlying gap: getting a real person into the system from wherever you found them, without the tool making you do it in the wrong order. Worth Brad treating them as one piece of work.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i047$il$, $il$Companies need a real group structure, not just a note saying they are related$il$, $il$Data & schema$il$, $il$Both$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-09T12:37:02.000Z'::timestamptz, 1, array[$il$i004$il$,$il$i054$il$,$il$i057$il$,$il$i068$il$]::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Today a group relationship is a free text box called Parent Group, and it only points one way. A company can say who its parent is. A parent cannot say who its subsidiaries are. Oliver wants to link from either end.

THE FIX IS NOT A SECOND FIELD. Do not add a Subsidiaries box next to Parent Group. That is two copies of one fact and they will disagree the first time somebody edits one and not the other. Store the relationship ONCE, let it be created or removed from either side, and render it from both: the parent lists its subsidiaries, the subsidiary names its parent.

SHOW IT AT THE TOP, NOT BURIED IN GEOGRAPHY AND STRUCTURE. The group is the first thing that changes how you treat a company, so it belongs in the header next to the priority and research chips, where Duttenhofer currently shows only a dash, Untouched and Germany. Something like Part of Save Group, or 3 companies in this group, as a chip you can click through. Anyone opening a record should see the group before they see anything they might act on.

AND IT HAS TO BE A LINK, NOT TYPED TEXT. Parent Group currently holds a name someone typed. A typed name cannot be clicked, cannot be traversed by a guard, and drifts in spelling. It has to reference an actual company record.

OLIVER ASKED WHETHER THIS IS A MUST. It is, and not for tidiness. i004, the group level duplicate approach guard, is already agreed as a must, and a guard needs something to traverse. Without a real link there is nothing to walk, so i004 cannot be built. That makes this the prerequisite, and it is why it sits in wave 1 where getting it wrong means a migration rather than an edit.

It is also not theoretical. Four group collisions surfaced in five days, and more since: Save Group and asgoodasnew, where a live Monday deal sits on one side and a Pending Review InMail on the other; three unlinked spusu records across Austria, Germany and Italy; four Recommerce records; Telia and its Nordic subsidiaries; Coolblue with a German country manager and no German entity.

The shape should be settled with Brad first. The questions are in the background, and the second one matters more than the schema.$il$,
$il$QUESTION ZERO, NOW THAT THE DIRECTION PROBLEM IS CLEAR: one relationship row between two company records, not a field on either of them. That is what makes it editable from both ends without two sources of truth, and what lets a company sit in a group of more than two. A field on the child cannot express a parent with six subsidiaries without six separate reads.

QUESTION ONE, THE SHAPE. A self referencing parent field on companies is the cheap option and handles a straight tree. A separate groups table is more work and handles the cases where there is no clean parent, for instance a cooperative whose members own it rather than the other way round. Recommendation: a link with a TYPE on it, rather than a bare parent pointer, for the reason in question two.

QUESTION TWO, AND THIS IS THE ONE THAT MATTERS. A corporate tree is not what we actually need. What outreach needs to know is one thing: WOULD APPROACHING THIS COMPANY BE NOTICED BY THAT ONE. Those are different questions, and the real cases already prove it.
Conrad, getgoods and Voelkner is ownership. One approach, one conversation.
EURONICS and Berlet is a cooperative. Berlet is commercially independent and would not blink at a EURONICS conversation, even though they share a brand.
Otto Group is a holding of trading companies that run their own commercial decisions.
spusu Austria, Germany and Italy is one brand across three markets, probably one buying decision.
Flatten all four into parent and you lose exactly the distinction the guard needs. So the link carries a type, and the guard behaves differently per type: block for ownership and one buying centre, warn for holding company, ignore for cooperative membership.

QUESTION THREE, VERIFIED OR NOT. The Save and asgoodasnew link is recorded twice in the lake as probable but unverified, and it has stayed that way for months. If the model has no confidence flag, that guess becomes a fact the moment someone types it into a parent field, and then a guard starts blocking real outreach on the strength of a hunch. Every link needs verified or unverified and a source, and an unverified link should warn rather than block.

QUESTION FOUR, WHO SIGNS. If the group is one buying centre, the pitch goes to the parent and the subsidiaries are volume, not prospects. If they buy independently, each is its own prospect. This is a commercial question, not a data one, and it is the reason to have the conversation with Brad and probably with Mark rather than just picking a schema.

QUESTION FIVE, DO NOT DOUBLE COUNT THE VOLUME. If Save Group and asgoodasnew both carry device numbers and one is the other's channel, summing them at group level invents GWP that does not exist. Group level sizing needs a rule about which entity owns the volume before any roll up is shown, or the board will quietly inflate.

MIGRATION NOTE. The group text already exists as prose on the records that have it. Whoever builds this should harvest those notes rather than start empty, and every harvested link lands as unverified until someone checks it.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i048$il$, $il$Every lead timeline must be complete, and the record must say how complete it is$il$, $il$Outreach & drafting$il$, $il$Both$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-09T12:42:07.000Z'::timestamptz, 1, array[$il$i052$il$,$il$i053$il$,$il$i074$il$]::text[], array[$il$i031$il$]::text[], null, null, false, false, $il${"Brad": "2026-09-18T08:47:43.405Z", "Oliver": "2026-09-15T13:07:52.796Z"}$il$::jsonb,
$il$Every message already sent has to be on the lead's timeline, because the next message is drafted from it. A missing touch does not read as unknown, it reads as never contacted, and that is how someone gets a welcome message they have already had.

ONE CORRECTION UP FRONT, BECAUSE IT CHANGES THE PLAN. Oliver's LinkedIn export will not settle this. LinkedIn's own data export contains DMs only. It has never contained InMails and it never will. So the export fixes the DM backlog and connection state, and leaves every historical InMail exactly as missing as it is today. Those exist only in Oliver's Sales Navigator inbox and no sync, scrape or reconciliation will recover them.

So the plan has three parts, not one. Record at send time, which is the only thing that makes this true going forward. Load the export, which repairs the DM half of the backlog. And mark what is known to be incomplete rather than letting a thin timeline pass as a complete one.

On Phantombuster: nobody has confirmed it can read message history at all, and there is account risk in the answer. Do not plan around it until it is checked. See the background.$il$,
$il$PART ONE, RECORD AT SEND TIME. This is the whole fix going forward and everything else is cleanup. If the message is written and sent through Lovable, the touch is written in the same action, and the timeline cannot drift. It is already a standing rule for the engine and it needs to be a hard constraint of the build rather than a habit. The corollary is uncomfortable but real: anything Oliver sends by hand in Sales Nav, outside the system, will still go missing. Either sends go through Lovable or there is a permanent reconciliation chore.

PART TWO, THE EXPORT. Oliver runs the full LinkedIn data export and hands over the archive. It carries Connections, Invitations sent and received, and Messages, which are DMs. Load them, match on the profile identifier rather than the name, and write what is missing. This is the same archive as i033, so do it once and use it for both the URLs and the history. Depends on i031 having split the URL fields first.

PART THREE, SAY HOW COMPLETE EACH TIMELINE IS. This is the part usually skipped and it is what makes the other two safe. A contact should carry something like history verified to a date, set when the export was loaded or when the first system send happened. A drafter, human or agent, then knows whether a quiet timeline means no contact or means we simply do not know. Without it the backlog repair silently converts unknown into confirmed empty, which is worse than the gap, because now nobody doubts it. Until a contact is verified, the standing caveat still applies: if they are first degree or accepted, treat a prior message as possible and check the thread before sending.

ON PHANTOMBUSTER, honestly. Two things are unknown and both matter. Whether it can read message threads at all, as opposed to profiles and connections, which is what it is mostly used for. And whether reading a Sales Navigator inbox on a schedule puts the account at risk, which is the same caution parked in i019 about automated LinkedIn activity at volume. Losing Oliver's Sales Nav account to recover message history would be a poor trade. Brad should confirm both before it goes in a plan, and if the answer is uncertain, part one plus part three is enough to work from.

WHY IT IS A MUST AND SITS IN WAVE 1. Every guard reads touch history. The cooldown, the do not contact check, the duplicate approach guard, the day seven reply check, the next action derivation in i003 and i036. All of them treat absence as a fact. Feeding them an incomplete timeline does not degrade them gracefully, it makes them confidently wrong, and Catherine Meng's missing 20 August message in i031 is the worked example.$il$);
insert into public.improvement_comments (team_id, improvement_id, who, at, text)
select i.team_id, i.id, $il$Claude$il$, '2026-09-17T12:20:00.000Z'::timestamptz,
$il$17 Sept, a fresh instance and a new problem inside it. Oliver's DM to Marjolein van Osch, Head of eCommerce at Fairphone, 1st degree, sent 7 September at 14:07 from the LinkedIn messaging window, is not in Lovable and not in Sales Navigator. Oliver only found it by opening LinkedIn.

THE NEW PART IS NOT THE GAP, IT IS WHAT THE GAP DISPROVES. This is a plain LinkedIn DM, which is exactly the kind the four hourly watcher is supposed to reconcile, and it has sat unrecorded for ten days. So the fallback that everything else assumes is not working, at least not for threads opened in linkedin.com/messaging rather than in Sales Navigator. Three things to establish, in order: is the watcher running at all, does it read linkedin.com/messaging threads or only Sales Navigator ones, and how far back does it look.

GOOD NEWS ON THIS ONE: a native DM is precisely what the LinkedIn export does contain, so part two of this item would recover it. Oliver has asked for the full export and that is the right call. It still recovers no InMails, ever, and LinkedIn inMail is 315 of the touches on the dashboard, so the export closes the DM half and leaves the InMail half permanently open.$il$
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i048$il$;

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i049$il$, $il$The review of what should be a picker and what stays free text, done once$il$, $il$Data & schema$il$, $il$Both$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-09T12:52:36.000Z'::timestamptz, 1, array[$il$i027$il$]::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Oliver has now hit this five times: Countries Selling In, Seniority, Function, Category, and the general question of which fields should be a selection at all. It is one defect. Fixing it a screenshot at a time means he keeps finding it and Brad keeps making the same change.

Do it as one review. Walk every field on companies and contacts and sort each into three buckets. Already a picker. Genuinely free text, like Notes and Evidence. Should be a picker because something downstream reads it. Then convert the third bucket in one pass and publish the list so nobody has to rediscover it.

The test for the third bucket: does a filter, a score, a guard or a report read this field. If yes it must be a picker, because the answer depends on the string matching. A typo in free text is not untidy, it is a silent wrong number.

Category has a proposed list ready, derived from what is actually in the data. It is in the background below.$il$,
$il$CATEGORY, DERIVED FROM THE REAL DATA rather than invented. The lake holds 16 distinct values across 227 populated rows, and most of the tail is one company each saying the same thing differently:
  Mobile/Gadget Retail 153, Refurb / Recommerce 29, Telco 17, Telco / Manufacturer 9, Software Provider 6, Industry Media / Influencer 2, Consumer electronics retail chain 2, then single instances of B2B IT Leasing / Asset Management, Manufacturer, Software / Telco Infrastructure, Education channel device retail, Department store multi-category retail, Consumer electronics e-commerce, IT / Consumer Electronics Retail, and one row reading Mobile/Gadget Retail with a TBC note inside the value.

SUGGESTED LIST, eight values, argue with it:
  Mobile and gadget retail
  Refurb and recommerce
  Consumer electronics retail, covering the department store, e-commerce and retail chain variants
  Marketplace
  Telco and operator
  Manufacturer and OEM
  IT leasing and asset management
  Software, platform and media
Marketplace is not in the current Category values at all but exists in the other field, and refurbed is one, so it needs to be here. Telco / Manufacturer as a combined value should go: pick the primary and let the group structure in i047 carry the rest.

ONE ROW HAS THE WORD Industry AS ITS CATEGORY VALUE. That is a header row that leaked into the data during a migration. Worth finding, because where there is one there are usually others.

SETTLE CATEGORY AGAINST INDUSTRY FIRST, and the data now proves the overlap rather than just suggesting it. The other field carries Refurbished Specialist, Operator / Manufacturer and Marketplace / Comparison Site, which are the same distinctions in different words. Two pickers for one concept is worse than the free text, because then they can disagree and both look official. Decide whether one of them dies.

INSURANCE PROVIDER IS FREE TEXT AND SHOULD NOT BE. It is on the same screen, and it is the field that names the incumbent carrier: Coverd, Tryg, Wertgarantie, Assurant, Zurich, Ostangler. That is the competitor register in disguise, and it is exactly the field you would want to filter on to ask which carrier we keep running into. As free text it cannot be counted. Same treatment, with the list seeded from what is already recorded plus an other option that flags for review.

OTHER KNOWN MEMBERS OF THE THIRD BUCKET, all raised by Oliver from live screens: Countries Selling In, which is i027 and needs multi select against the canonical country list; Seniority, which the sourcing floor reads, so a typo slips a junior contact past a gate; Function; and the new field in i075 for who the company sells to. Assume there are more. That is the point of reviewing rather than patching.

DO NOT INVENT VOCABULARIES. Where a list already exists, in the filters, the scoring model, or the lake's status vocabulary, use exactly that. A second list that is nearly the same is how values drift apart.

MIGRATION IS THE REAL WORK, not the pickers. Converting a field to an enum leaves every value that does not match, and those become blanks or errors rather than vanishing. Each conversion needs a mapping pass and a reviewed list of what could not be mapped. The unmappable value is often the interesting one.

WHY WAVE 1. These are schema decisions. Changing free text to an enum after things have been written against it is a migration; doing it before is an edit.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i050$il$, $il$Question for Brad: after pressing Send, can I leave the contact and carry on elsewhere?$il$, $il$Outreach & drafting$il$, $il$Brad$il$, $il$question$il$, $il$open$il$, $il$Oliver$il$, '2026-09-09T12:58:40.000Z'::timestamptz, null, '{}'::text[], '{}'::text[], null, null, false, false, $il${"Brad": "2026-09-11T08:14:55.532Z", "Oliver": "2026-09-09T13:00:05.343Z"}$il$::jsonb,
$il$When Oliver presses Send now on a draft, does he have to sit on that contact until it completes, or can he navigate away and keep working while it goes?

Two answers needed, and the second is the one that actually matters.
1. Does the UI hold him there. If each send locks the screen for a few seconds, forty sends is several minutes of watching a spinner, and that is the difference between a session that flows and one that does not.
2. If he navigates away mid send, does the touch still get written. A send that completes after the page has moved on, but never records the touch, produces exactly the invisible gap that i048 is about. That would be much worse than a slow spinner.$il$,
$il$WHAT A GOOD ANSWER LOOKS LIKE, so this can be closed properly rather than with a yes.
The send is fired, the card shows sending, and Oliver can move on immediately.
The touch is written by the same operation that sends, not by the page, so navigating away, closing the tab or losing wifi cannot separate the two.
If it fails after he has moved on, it surfaces somewhere he will see it, not only as a toast on a screen he has already left. A failed send that is silently forgotten is the same defect as an unrecorded one.
The contact does not need to be reopened to confirm it went.

WHY OLIVER IS ASKING. The daily pattern is a batch: work down a list of approved drafts and send them one after another. Anything that makes each send a stop rather than a step turns a twenty minute job into an hour, and the thing that gets dropped is the last few sends of the day.

RELATED, NOT THE SAME. i048 is about the timeline being complete. This question is about whether the send flow can break it. If the answer to point two is no, that is not a question any more, it is a must, and it should be raised as one.$il$);
insert into public.improvement_comments (team_id, improvement_id, who, at, text)
select i.team_id, i.id, $il$Brad$il$, '2026-09-09T16:10:36.001Z'::timestamptz,
$il$Yes. Send hands off to the automation and the row updates itself, so you can move on straight away. It takes up to about two minutes: it flips to Scheduled immediately, the phantom sends, and the callback flips it to Sent with the exact text you sent frozen onto the record. If LinkedIn deduplicates it you get a Skipped state with the reason rather than a silent failure, and it stays in Approved so you can decide what to do. You never need to sit and watch it.$il$
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i050$il$;

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i051$il$, $il$Incoming messages lose their line breaks somewhere between LinkedIn and Lovable$il$, $il$Integrations$il$, $il$Brad$il$, $il$nice$il$, $il$open$il$, $il$Oliver$il$, '2026-09-09T13:06:26.000Z'::timestamptz, 5, '{}'::text[], array[$il$i037$il$]::text[], null, null, false, false, $il${}$il$::jsonb,
$il$A message arrives from LinkedIn with paragraphs in it and shows up in Lovable as one block. Preserve the original breaks on the way in and on the way out.

THIS IS PROBABLY THE SAME BUG AS i037, AND IT IS THE BETTER CLUE. i037 is that our own drafts come out as one blob, and the open question there was whether the agent is writing them flat or something in the pipe is eating the newlines. An INBOUND message is the control experiment: nobody generated it, LinkedIn definitely sent it with breaks, so if it also arrives flat then the agent is not the problem and the pipe is. Diagnose the two together and one fix may close both.

One thing narrows it further before anyone opens the code. On the Reconciliation screen the messages DO render with their paragraphs intact, in both the unmatched replies Oliver screenshotted. So the breaks survive at least as far as that view. Find out where they are still present and where they are not, and the answer is between those two points.$il$,
$il$THREE PLACES IT CAN BE LOST, and the test above tells you which.
ON INGEST, if the sync strips or collapses whitespace when writing the message. If this were it, Reconciliation would be flat too, and it is not, so probably rule it out.
IN STORAGE, if the field trims. Same reasoning, probably not.
IN A PARTICULAR VIEW, if the container lacks white-space pre-wrap and HTML collapses the newlines on render. This is the most likely one given Reconciliation is fine and other views are not. It is a one line CSS fix per view, which is why it is worth five minutes of finding rather than an hour of guessing.

WHY IT IS WORTH FIXING EVEN THOUGH IT IS COSMETIC. It is not only cosmetic when a person is reading a reply to decide what to say next. A wall of text hides the structure of what someone actually said, and the part that matters, the question or the objection, is usually its own paragraph. Harder to read means more likely to be skimmed, and skimming a prospect's reply is how the next message answers the wrong thing.

IT ALSO FEEDS THE AGENT. The drafting stack reads the thread. If the thread is stored or served flat, the model reads it flat too, and the structure that would have told it which sentence was the ask is gone. So this is not purely a display concern if the loss turns out to be earlier than the view.

CHECK THE ROUND TRIP WHILE YOU ARE THERE, per i037: type a break by hand into a draft field, send it, and confirm it survives to a real sent message. Inbound and outbound share most of the same plumbing.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i052$il$, $il$Reply from inside the conversation, and put every channel in one thread$il$, $il$Outreach & drafting$il$, $il$Both$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-15T11:22:20.000Z'::timestamptz, 1, array[$il$i088$il$]::text[], array[$il$i048$il$]::text[], null, null, false, false, $il${"Oliver": "2026-09-15T13:07:47.996Z"}$il$::jsonb,
$il$Urs Moeller at Coolblue replied. On his contact view the Conversation section shows what was sent and his answer, which works well, and there is no way to reply from there. Oliver has to leave, find the thread in Sales Navigator, and answer it somewhere else.

TWO STAGES.
Now: a reply box in the Conversation section, so a reply is written where the thread is read.
Next: every channel in that one thread. LinkedIn DM, InMail and email in a single chronological view, with a channel selector on the reply so Oliver picks how it goes out. In this case they are connected, so it is a free DM.

THIS IS A DATA FIX WEARING A CONVENIENCE HAT, which is why it is a must rather than a nice to have. Replying inside Lovable means the touch is recorded by the same action that sends it. Replying in Sales Navigator means somebody has to remember to log it, and the record of what we have said to people is exactly what keeps going missing. See i048. This feature does not add to that problem, it is one of the few things that actually closes it.$il$,
$il$THE CHANNEL SELECTOR IS NOT A FREE CHOICE, and this is the part to get right or the feature becomes a way to break the rules faster. The channel is already determined by things the system knows:
Connected first degree means a DM, which is free. Not connected means InMail, which costs a credit. That difference is real money and should be shown on the button, not discovered after.
Cold email is permitted for France, Belgium, Netherlands and Switzerland-targeted only. Germany, Austria, Spain, Luxembourg, Italy and Czechia are LinkedIn led. So for a German contact the email option should be visibly unavailable with the reason, not quietly selectable.
Sales Navigator is the default channel even for first degree connections.
So: preselect the correct channel, show why, and make the wrong one refuse rather than warn. A picker that offers five equal options invites the one mistake the guards exist to prevent.

A REPLY TO AN INBOUND IS NOT A COLD TOUCH, so it should not have to go through the full draft review queue. But the hard guards still apply and must run at send: a hard opt out, a do not contact flag, or a company that has moved into Monday all block the send even here. Fail closed, per i005.

EMAIL IS THE LONG POLE and should not hold up stage one. LinkedIn DMs and InMails already arrive through the Sales Navigator integration. Email lives in Outlook and needs its own capture. Two traps when it comes:
Thread on the In-Reply-To and References headers, never on the subject text. Subjects get edited, translated and re-used, and threading on them merges conversations that are not related.
A reply sent from Lovable has to land in Oliver's Outlook Sent Items as well, or his own mailbox stops being a complete record and he ends up checking two places. That is the same split this item is trying to remove.

IT UNLOCKS PROPER DRAFTING, which is the quieter benefit. The standing rule is that no message is drafted without reading the full thread first. Right now the thread is spread across Sales Navigator, Outlook and the touch log, so that rule is followed by hand or not at all. One chronological view is the first time an agent could actually read the conversation before writing into it.

WHAT IS ALREADY GOOD IN THAT VIEW, and should survive the rebuild. The AI state of play panel under Notes is doing real work: it classified Urs's answer as an objection, named it as a differentiation challenge rather than a rejection, placed Coolblue as a sophisticated incumbent on a monthly recurring model, and flagged the open risk carrier question. That is the context a drafter needs, and it is sitting in the right place. The reply box belongs directly under it.

WORTH DECIDING EARLY: does the reply box draft for you, or start blank. Oliver should be able to write two lines himself without waiting for a model. Suggest blank by default with a generate button, rather than an agent filling the box before he has decided what he wants to say.

This is the conversation half of the single GTM system spec. The deal layer went to Brad on 15 September; this is the same argument applied to messages.$il$);
insert into public.improvement_comments (team_id, improvement_id, who, at, text)
select i.team_id, i.id, $il$Oliver$il$, '2026-09-17T14:20:00.000Z'::timestamptz,
$il$17 Sept, Oliver restated this from the Hector Destailleur thread at Recommerce Group and added three things the item did not yet say. Recording them here rather than as a new item, because it is the same feature.

1. HALF OF STAGE TWO IS ALREADY BUILT, which shrinks the job. The Hector thread shows the whole history in one chronological view already: connection request 13 May, InMail 14 May, DM 15 May, his DM reply the same day, the email of 18 May with its subject line, and his DM reply to that. Four channels, both directions, correctly ordered. So the unified view exists. What is missing is only the reply box and the send path underneath it.

2. REPLY IN KIND BY DEFAULT. The channel should preselect to the one THEY last used, not just the cheapest permitted one. Replying where someone wrote to you keeps the thread in one place on their side too. That sits on top of the rules already in the background here, so the precedence is: hard blocks remove options entirely, then match their last inbound channel, then fall back to the cheapest permitted one and say why the default moved.

3. CHANGING THE CHANNEL IS A DELIBERATE ACT AND STARTS SOMETHING NEW. Oliver's words: it should be able to be changed to initiate a new sequence. So switching the picker is not a formatting choice, it opens a new thread on the new channel, and the interface should say so. It matters for threading, for the sequence counter, and for whether the next chaser follows the old conversation or the new one.

AND ONE THING THIS THREAD SHOWS BY ACCIDENT. Hector handed over his address inside a DM, hector.destailleur at recommerce.com, and the email that followed used it. Addresses arrive inside messages and do not reach the Email field, which is empty on most contacts. When an inbound message contains an address, offer to save it to the contact in one click. That is what makes the email option on this picker available at all, and it is cheap next to the enrichment in i015.$il$
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i052$il$;

-- exactness gate: every item in this part must hash to the value computed from the source file
do $verify$
declare bad text;
begin
  select string_agg(e.item_key, ', ' order by e.item_key) into bad
  from (values
    ('i046', '5271136e8b347c14a9649a9534ddc186', 0),
    ('i047', 'd78c917841f6c50f657dad5c5bc2ea7a', 0),
    ('i048', 'c631d00e4fb2ecfb3bf387a27c57e36e', 1),
    ('i049', '349bde3d2089f325cadac0918d70c97c', 0),
    ('i050', 'e7777f906bc22eb33aff3efd5ac5675d', 1),
    ('i051', '99b3bdd7caba456c165762786c7c5012', 0),
    ('i052', '4f423b0a568edb8f2e1002c844113521', 1)
  ) as e(item_key, src_md5, n_comments)
  left join public.improvements i
    on i.item_key = e.item_key and i.team_id = (select id from public.teams limit 1)
  where i.id is null
     or e.src_md5 is distinct from md5(concat_ws(chr(31),
      i.title, i.category, i.owner, i.priority, i.status, coalesce(i.raised_by,''), i.detail, i.notes,
      coalesce(i.done_by,''), array_to_string(i.blocks,','), array_to_string(i.blocked_by,','),
      coalesce(i.build_wave::text,''), i.pinned::text, i.hidden::text,
      to_char(i.created_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), coalesce(to_char(i.done_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),''), i.seen_by::text,
      coalesce((select string_agg(concat_ws(chr(31), c.who, to_char(c.at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), c.text), chr(30) order by c.at)
                from public.improvement_comments c where c.improvement_id = i.id), '')));
  if bad is not null then
    raise exception 'F18.5 import: rows differ from the source export: %', bad;
  end if;
end
$verify$;
