-- 118b_f18_5_improvement_log_import_p05
-- F18.5(b) improvement log import, part 5 of 12: i053..i068 (16 items, 2 comments).
-- GENERATED by scripts/gen_improvement_log_import.py from 260920_lovable_improvement_log_export.json - do not edit by hand.
-- Text is dollar-quoted and must stay byte-for-byte; the DO block at the end rolls the part back if not.

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i053$il$, $il$The same outbound DM is logged twice on the Urs Moeller thread$il$, $il$Data & schema$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Claude$il$, '2026-09-15T11:22:57.000Z'::timestamptz, 1, '{}'::text[], array[$il$i048$il$]::text[], null, null, false, false, $il${"Brad": "2026-09-18T09:02:34.569Z"}$il$::jsonb,
$il$On Urs Moeller at Coolblue, the Conversation view shows Oliver's opening DM twice. Identical text, both stamped 10 Sep 2026. It was sent once.

SECOND INSTANCE, 17 Sep 2026, Frédéric Gandon at Largo. Touch history shows two Connection request rows on 5 Aug 26, T503 and T817, and the conversation below shows the same connection request note twice, both marked Sent. One request was sent. So this is not one thread, it is a pattern, and the count is worth running now rather than after the LinkedIn export is loaded.

Two possible causes and they need different fixes. The same message ingested twice, which means two touch rows and a dedup rule missing at the point of ingest. Or one touch row rendered twice, which is a display bug and the data is fine. The Largo case argues for the first, because the two rows carry different touch ids. Check the underlying rows first.$il$,
$il$THIRD INSTANCE, AND IT SHOWS WHERE THE DUPLICATES COME FROM. 17 Sep 2026, Hermann-Wilhelm Wantia. His touch history holds five rows and the ids come from four different namespaces:
  20 Aug 26  T855                                          Connection request
  25 Aug 26  agent-8e3a95e2-c1f3-426b-ba5a-f618a50de5a4    Initial message
  25 Aug 26  cr-backfill-f83f6eb8-74a3-48bd-9c2b-8bc7d7912888  Connection request
  25 Aug 26  sup-1787755496481-jewzjs                      Initial message
  26 Aug 26  T901                                          Initial message

FOUR WRITERS, FOUR ID SCHEMES, NO SHARED KEY. A T series, an agent job, a connection request backfill, and something minting sup plus a millisecond timestamp. Each one invents its own identifier, so no two of them can ever recognise the same event. That is not a bug in one importer, it is the absence of the key this item asks for, and it is now visible on screen rather than inferred.

WHAT IS ALMOST CERTAINLY DUPLICATED HERE. The 25 August connection request carries a cr-backfill id and sits five days after the T855 request of 20 August, which strongly suggests a backfill re-recording the same invitation rather than a second one being sent. And three separate Initial message rows on 25 and 26 August, written by three different processes, for what the conversation below shows as one DM on 26 August.

THE CONSEQUENCE IS LIVE ON THIS SCREEN. The draft is labelled message 3 of 3, so the sequence believes this thread is exhausted and is drafting the exit message. If the real history is one connection request and one DM, the exit message is arriving a step or two early, to somebody who has barely heard from us. This is the second time the counter has been provably wrong, after chaser 3 of 2 on i082.

SO THE COUNT IS WORTH RUNNING NOW. Group touches by contact, direction, channel and date, and count the groups with more than one row. Break it down by id prefix as well, because that says which writer is producing them and therefore which one to fix first.

WHY A DUPLICATE TOUCH IS NOT COSMETIC. Touch history is read by things that count. The day seven reply check, the cooldown, the message N of 3 sequence position, and the momentum and volume figures on the dashboard all treat a touch row as one contact event. Two rows for one message means the sequence thinks Oliver is a step further along than he is, and a chaser could fire a position early.

IT ALSO POINTS THE OTHER WAY FROM i048. That item is about touches going MISSING. This is a touch appearing twice. Both are the same underlying problem, which is that nothing owns the identity of a message. A touch needs a stable key, ideally the platform's own message id, so that re-running a sync updates a row rather than adding one. Without that, every future sync or backfill risks doing this again at scale, and the LinkedIn export load in i033 and i048 is exactly such a backfill.

SO THE REAL FIX IS THE KEY, not this thread. Deduplicate on the message identifier rather than on text, because text matching would collapse two genuinely identical short messages sent to different people, and would miss a duplicate that differs by a trailing space.

AND THE KEY HAS TO BE THE SAME KEY FOR EVERY WRITER. A stable identity that the agent, the backfill, the supabase path and the T series all resolve to, so a row can be recognised as already present no matter which process meets it second. Otherwise dedup only ever works inside one writer.$il$);
insert into public.improvement_comments (team_id, improvement_id, who, at, text)
select i.team_id, i.id, $il$Claude$il$, '2026-09-17T15:35:00.000Z'::timestamptz,
$il$FIFTH ID NAMESPACE, 17 Sept. Dhananjay Choubey at Revent, P303, carries a touch with the id synthetic-cr-P303. So the list is now T numbers, agent jobs, cr-backfill, sup timestamps and synthetic. This one names itself as generated rather than observed.

The underlying connection request does look real, it shows as sent on 30 August in the conversation below, so synthetic is most likely a placeholder id minted where the platform id was unknown. That needs confirming rather than assuming. If any synthetic row describes an event that did not actually happen, then the touch history contains invented touches, and every guard that reads it, cooldown, duplicate approach, day seven check, sequence position, is wrong in the direction that costs the most.

Either way it strengthens the ask: one identity scheme that every writer resolves to, and a flag on each touch saying whether it was observed or inferred.$il$
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i053$il$;
insert into public.improvement_comments (team_id, improvement_id, who, at, text)
select i.team_id, i.id, $il$Claude$il$, '2026-09-17T16:10:00.000Z'::timestamptz,
$il$THE CLEAREST INSTANCE YET, AND IT SUGGESTS THE MECHANISM. Alexander Peretti at 0815, P595. His touch history holds THREE Initial message rows all dated 28 July 26, ids T775, T576 and T540. The conversation below shows why that is wrong: one InMail on 28 July with a full body, Geraeteschutz in AT und DE, followed by two more 28 July InMail entries that are COMPLETELY EMPTY. One message, three rows, two of them with no content.

THAT POINTS AT A SPECIFIC CAUSE. A row with no body was almost certainly created from a thread listing, where only the metadata is visible, while the row with the body came from opening the thread itself. Two capture paths, no shared key, so the same message lands twice more.

AND IT MAKES THE FIRST CLEANUP CHEAP AND SAFE. Find touch rows with an empty body where another row exists for the same contact, channel and date, and merge them into the one that has content. That does not need the identity scheme to be designed first and it would remove the most obvious duplicates today.

THE COST IS ON SCREEN AGAIN: the footer reads logged as chaser 3 of 2. A sequence cannot be at position three of two, and this is the second contact where that exact string has appeared, after the one on i082. The touch history also opens with synthetic-cr-P595, the same synthetic namespace as Revent.

ONE FURTHER ODDITY WORTH A LOOK, not necessarily this item. The channel counts moved during the day without any send going out: LinkedIn inMail went from 315 to 314 and LinkedIn DM from 191 to 192, with Sent unchanged at 847. That looks like a touch being reclassified from InMail to DM. If something is rewriting the channel on existing touches, that is worth knowing, because channel drives the credit accounting and the free DM logic.$il$
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i053$il$;

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i054$il$, $il$A deal belongs to a country, not to a company. Decide the rule before the deal layer is built$il$, $il$Data & schema$il$, $il$Both$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-15T11:45:33.000Z'::timestamptz, 1, '{}'::text[], array[$il$i047$il$]::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Coolblue is headquartered in the Netherlands. Urs Moeller is Country Manager Germany, so the live conversation is a German one. Oliver asked the right question: is the deal Coolblue, or is it Coolblue Germany, and does that mean creating a German entity record.

ANSWER TO THE DIRECT PART FIRST. There is no Coolblue Germany in the lake. Coolblue appears once, C485, coolblue.nl, Deep research done, In conversation. So the German entity does not exist today.

THE RULE WORTH ADOPTING: entity records follow the SIGNATURE, deals follow the MARKET. Create a separate company record only where there is a separate legal entity Pier would actually contract with. Otherwise keep one company and let the deal carry the country. That keeps the account list honest and still lets you run Germany and the Netherlands as separate opportunities with separate volumes, separate timing and separate owners.

For Coolblue that makes it a question for Urs rather than a modelling decision: would a German programme be signed by Coolblue in the Netherlands or by a German entity. It is a fair thing to ask and the answer decides the record.

This needs i047 underneath it. Country level deals without a group structure just produces unlinked look alike companies, which is what is already happening.$il$,
$il$THERE IS A LIVE COMPLIANCE HOLE IN THIS EXACT CASE, and it is the strongest reason to settle the rule now. Coolblue is recorded as Netherlands. Cold email is permitted for Netherlands targeted contacts. Urs is in GERMANY, where outreach is LinkedIn led and cold email is not permitted. A guard reading the COMPANY country would clear an email to him. A guard reading the CONTACT country would stop it. This is exactly the rule written into i038, and Coolblue is the worked example: the legality check must read the contact, falling back to the company only when the contact has no country.

THE SPLIT IS ALREADY HAPPENING BY HAND, INCONSISTENTLY. 35 company records already carry a country in the name: Vodafone Germany and Vodafone Italia, Euronics Deutschland and Euronics Italia, Media Markt Switzerland, Back Market Italia, Lycamobile Germany, Magenta Telekom Austria, Apple Germany. Beyond that, 72 brand names appear more than once. So the convention exists, it is applied to some groups and not others, Coolblue among the nots, and nothing links any of the siblings. Whatever rule gets chosen has to be applied backwards over those 35 as well, or the list stays half and half and neither half can be trusted.

SIZING IS WHERE IT BITES SECOND. If one Coolblue record carries group wide device volumes and a German deal is sized off it, the German opportunity inherits Dutch volume and the number is wrong. Volumes belong at whatever level the deal sits. Same trap as the group roll up warning in i047, now with a real instance attached.

THREE MORE THINGS A COUNTRY LEVEL DEAL NEEDS, worth agreeing with Brad at the same time:
An owner per deal, not per company. Germany is Oliver, the UK is Jack. One company can carry both.
A currency. Euro for Germany, Swiss franc for Switzerland, sterling for the UK. Pier Protect rates already exist in all three, so the deal needs to know which table it is priced from.
Its own stage and next action. A German deal can be in conversation while a Dutch one has not started, and today one company record can only be in one state.

TIMING. The deal layer spec went to Brad on 15 September. This is a requirement of that spec rather than a change to it, so it is worth reaching him before he builds the deal object, not after.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i055$il$, $il$Unresearched company must not stop a draft being written$il$, $il$Outreach & drafting$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-15T12:20:41.000Z'::timestamptz, 2, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Agreed on the 15 September call. Today the guard refuses to create a draft where the company has not been researched, so contacts sit doing nothing and go stale. Oliver's call: still write the draft, mark it clearly as company not researched, and park it in its own section. He can then override and push it through when he knows something the record does not.

In the Outreach section, a parked draft gets a button that moves it into Pending Review. Same for anything sitting in Refused: a manual route back in, so strict logic never becomes a dead end.$il$,
$il$WHY OLIVER WANTS THE OVERRIDE, in his words: there might be something he has just not put in, or he might have heard something that means now is the time. A guard that cannot be overridden by the person with the most context is a guard that gets worked around.

THE FLAG HAS TO BE ON THE DRAFT ITSELF, not only on the section. The wedge and the angle for an unresearched company are necessarily weaker, so the reviewer needs to know what he is reading before he approves it, not after.

BRAD'S POINT, WORTH KEEPING: once the research agent runs, this mostly solves itself. A contact with a connection request sent should make its company a research priority automatically. So build the override, but treat the queue ordering in i029 as the real fix.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i056$il$, $il$Merge duplicate companies, choosing field by field$il$, $il$Data & schema$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-15T12:21:41.000Z'::timestamptz, 1, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$There is no way to merge two records that are the same company. Recommerce alone appears four times, including one with an exclamation mark in the name from an old character recognition pass. Otto Austria has two. Add a merge action.

It must NOT merge automatically. Oliver's requirement: a preview that goes field by field, because the record with less data overall sometimes holds the one field worth keeping. So: show both values side by side, pick per field, then commit.$il$,
$il$FIELDS THAT WILL CONFLICT and need the per field choice: website, category, country, countries selling in, revenue, employees, research stage, engagement, notes. Contacts and touches should always be unioned rather than chosen between, because losing a touch is losing history.

KEEP THE LOSING ID. After a merge, the absorbed company id should still resolve to the surviving record rather than 404, because that id may be referenced in the lake, in notes, or in something Oliver typed into monday months ago.

SAME CONTROL SERVES i047. Merging is what happens when two records turn out to be the same company; linking is what happens when they are two companies in one group. The UI should make it obvious which one you are doing, or people will merge a subsidiary into its parent and lose it.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i057$il$, $il$Filter by group in Outreach$il$, $il$Lovable UI$il$, $il$Brad$il$, $il$nice$il$, $il$open$il$, $il$Oliver$il$, '2026-09-15T12:22:41.000Z'::timestamptz, 5, '{}'::text[], array[$il$i047$il$]::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Brad's suggestion on the call and Oliver agreed. Once groups exist, being able to filter outreach by group means you can see every live conversation across a group before touching any of it. Depends on i047.$il$,
$il$$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i058$il$, $il$One contact can belong to more than one company$il$, $il$Data & schema$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-15T12:23:41.000Z'::timestamptz, 1, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Dr. Boris Ewenstein exists twice at Otto, once with the title and once without, and the dedup did not catch it. The underlying reason a strict rule was never applied: Oliver sometimes works the same person at two companies, which a one contact one company model cannot express.

Fix both at once. Allow a contact to be linked to several companies. Then enforce the strict rule that made impossible: one LinkedIn URL per contact, and a new contact matching an existing URL is flagged rather than created.$il$,
$il$THE TITLE IS WHY THE DUPLICATE SURVIVED, and it is dealt with separately in i059. Dedup on a name string will keep failing while titles, middle names and umlaut spellings live in the same field.

MATCH ON THE URL, NOT THE NAME. A profile identifier is the only thing on a LinkedIn contact that is unique and stable. Names are not: two Christians at MediaMarkt, five suggested for one message in the reconciliation queue.

WHICH COMPANY OWNS THE OUTREACH when a contact has two. Probably the one the conversation is about, set per touch rather than per contact. Worth deciding before building, or the touch history ends up on the wrong company record.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i059$il$, $il$Academic title as its own field$il$, $il$Data & schema$il$, $il$Brad$il$, $il$nice$il$, $il$open$il$, $il$Oliver$il$, '2026-09-15T12:24:41.000Z'::timestamptz, 1, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Dr. Boris Ewenstein is held with the title inside the first name, which is how the duplicate got past the check. Split it: academic title, first name, last name. Dr, Prof, Prof Dr.

It also matters for German drafting. A salutation reading Hallo Dr. Boris is wrong, and Sehr geehrter Herr Dr. Ewenstein is right, so the title has to be addressable separately from the name.$il$,
$il$$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i060$il$, $il$Contact ID visible on the contact overview$il$, $il$Lovable UI$il$, $il$Brad$il$, $il$nice$il$, $il$open$il$, $il$Oliver$il$, '2026-09-15T12:25:41.000Z'::timestamptz, 5, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$The contact id exists as the last column of the contacts table, but it disappears the moment a contact is opened. Put it on the overview of the individual contact so it can be quoted in a message to Brad or in these notes.$il$,
$il$$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i061$il$, $il$Every draft says why it was written, and why now$il$, $il$Outreach & drafting$il$, $il$Both$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-15T12:26:41.000Z'::timestamptz, 4, array[$il$i067$il$]::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Under each draft, a short plain summary of how it was built: which layer or agent produced it, which facts it used, and what triggered it now. Oliver cannot currently tell whether a message came from the executive assistant, the email architect, the LinkedIn architect or the voice file, and when something reads wrong there is no way to find out where it went wrong.

The why now half is the more valuable one. Reasons like they accepted the connection request, or they posted that they are looking for a provider, are prioritisation signal as well as an explanation, and can bump the score.$il$,
$il$THE FAILURE THIS CATCHES, in Oliver's words: it was classifying greenfield opportunities that were not greenfield, because something was silently dropped or decided. A wrong verdict inside a confident looking draft is invisible. Showing the inputs makes it visible in the second it takes to read the line.

IT IS ALREADY HALF BUILT. There is a Why this now field on the outreach card, and the AI state of play panel on the contact view is doing the harder version of this well. This item is extending that to the draft itself: not only why this person now, but why THIS message.

KEEP IT TO ONE OR TWO LINES. If it becomes a paragraph nobody reads it, and an unread explanation is the same as none.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i062$il$, $il$There is no way to archive a company, and archiving must keep it findable$il$, $il$Data & schema$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-15T12:27:41.000Z'::timestamptz, 3, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$AB Gsmshop.at GmbH is marked OoS and the only action on the record is Move to Monday, which is the wrong destination for an out of scope company. There is no Archive at all. Add one, reachable from the company header.

WHEN IT ARCHIVES it should ask why and store the reason, and carry the company's contacts, touch points and outreach notes with it rather than leaving them loose. Archived with no explanation is indistinguishable from archived by mistake, and six months later nobody can tell which.

ARCHIVE MUST NOT MEAN HIDDEN FROM SEARCH. An out of scope company has to stay findable, because the whole point of recording it was so we never spend research credits on it twice. Archiving takes it out of worklists, queues and counts. It does not take it out of the search box.

So: Out of Scope is the REASON, archive is the SHELF. Do not make one automatically imply the other, and do not let the shelf swallow the record.$il$,
$il$THE STANDING RULE THIS PROTECTS: log every company found, including a non fit, marked Out of Scope with the reason, so the same company is never researched twice. An archive that removes a company from search would quietly break that rule, and the failure is invisible. Somebody sources it again in three months and nobody notices it was already ruled out.

WHAT SHOULD DISAPPEAR ON ARCHIVE: worklists, the sourcing queue, the ranked list in i071, draft creation, and the headline counts. What should NOT: search, the company id resolving, and the record itself when someone lands on it from a note or an old link.

IT PAIRS WITH THE GROUP CASES. The Conrad and Save Group collisions both end in archive with a reason rather than a deletion, and the reason is the whole value: worked in Monday under the parent, or ruled out as B2B only. An archive with no reason turns into a mystery the first time anyone asks why the company is not in the pipeline.

AND IT NEEDS AN UNDO, or at least a visible archived filter with a restore. Brad already offers Archived only as a toggle on contacts, so the pattern exists; the company side needs the same.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i063$il$, $il$Set the follow-up while sending the reply, and default it to automatic$il$, $il$Outreach & drafting$il$, $il$Both$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-15T12:28:41.000Z'::timestamptz, 3, '{}'::text[], array[$il$i036$il$]::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Next to Send on a reply, a follow-up setter. Presets of a week, a month, six months, and a custom date from a calendar, so a reply saying come back in January can be scheduled as 12 January on the spot.

The default is AUTO. The system reads the reply and picks the date itself, so a follow-up exists even when Oliver forgets to set one. He can always override. In his words, it should never be possible for a conversation to go silent.

This applies to replies Oliver sends. Everything else is already inside a funnel and keeps the cadence it has.$il$,
$il$AUTO HAS TO SHOW ITS WORKING, which is i061 again. When the chaser surfaces, it should say promised follow up in January, so Oliver can see why it is due today and trust it. An automatic date with no visible reason is the thing people switch off.

BRAD'S POINT IS RIGHT AND WORTH HOLDING: a contact who says come back in January is still cold, so the lead stays where it is rather than being promoted. The follow-up is a date, not a status change.

THIS IS THE SAME MECHANISM AS i036, seen from the other end. i036 is the activity area on the record; this is setting one at the moment of sending. Build one scheduler and surface it in both places, not two.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i064$il$, $il$A message sent outside Lovable still gets a follow-up$il$, $il$Integrations$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-15T12:29:41.000Z'::timestamptz, 3, '{}'::text[], array[$il$i036$il$]::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Oliver replied to Urs Moeller directly in LinkedIn. The inbox watcher will pick that up on its next run, which is right. What must also happen is that the follow-up logic fires on it.

So: any send detected from outside the system defaults to automatic AI chasing, same as i063. It is the failsafe. Nothing that leaves Pier should be able to go silent just because it was sent in the wrong window.$il$,
$il$$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i065$il$, $il$Show when LinkedIn next syncs, and let it be triggered by hand$il$, $il$Lovable UI$il$, $il$Brad$il$, $il$nice$il$, $il$open$il$, $il$Oliver$il$, '2026-09-15T12:30:41.000Z'::timestamptz, 5, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$The LinkedIn sync runs every four hours and there is no way to see when the next one is. Oliver wants it fixed in the top bar, next to the dark mode toggle, reading something like next LinkedIn sync at 14:00, so he can plan a batch of sends around it.

Alongside it, a manual trigger. Brad has this planned for the next version. Keep both: the schedule so nothing depends on somebody pressing a button, and the trigger for when Oliver has just done an hour of connection requests and wants them picked up now.$il$,
$il$$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i066$il$, $il$Moving a parent to Monday must not archive the rest of the group$il$, $il$Guards$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-15T12:31:41.000Z'::timestamptz, 2, '{}'::text[], array[$il$i044$il$]::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Telia Sweden is the parent and has moved to Monday. Denmark, Finland and Norway are still lake companies and should stay workable.

Oliver's reasoning: there are several roads into a group. Sometimes the subsidiary is the way in, and sometimes a country has no insurance at all while the parent does. So moving one company to Monday marks that company only, shows the group link, and leaves the siblings alone.

It is the opposite requirement to the Monday suppression in i044, and both are right. Suppress a company that is being worked elsewhere. Do not suppress its sisters unless they are being worked too.$il$,
$il$$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i067$il$, $il$Sign-offs are wrong, including one draft signed with Brad's name$il$, $il$Voice$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-15T12:32:41.000Z'::timestamptz, 4, '{}'::text[], array[$il$i061$il$]::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Drafts are signing off inconsistently and sometimes with the wrong person entirely.
  Oli, seen on at least four drafts. Oliver never signs outbound that way.
  Oliver Mueller in full on others, so it is not a single wrong constant.
  BRAD, on the 8 September regenerated draft for Florian Pfeiffer. Another person's name, on Oliver's message, one click from being sent.

The canonical rule already exists in the voice file: external communications sign as Oliver, never Ollie. So this is not a preference being violated, it is a written rule not reaching the drafter.

Trace it rather than patch it. Something is supplying a name from the wrong place, and whatever does that will be getting other things from the wrong place too.$il$,
$il$THE INCONSISTENCY IS THE CLUE. If every draft signed Oli it would be one bad constant. Some sign Oli, some sign Oliver Mueller, and one signs Brad. That points at more than one generation path, or at the sign off being inferred from context rather than set from the voice layer. Brad appearing suggests it can pick up whoever is associated with the session or the record rather than the sender.

WORTH CHECKING WHICH LAYERS ACTUALLY LOAD at draft time, which is i061. If the sign off is wrong, other rules from the same file are probably also not landing, and nobody would notice because the rest are less visible than a name at the bottom.

A DRAFT SIGNED BRAD IS A REPUTATION RISK, not a typo. It reads as a message written by somebody else on Oliver's behalf, which is precisely the impression the whole voice layer exists to avoid. Worth a lint rule that fails any draft whose sign off is not Oliver, rather than relying on the prompt, per i084 and the enforcement over prose principle.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i068$il$, $il$Verify every company group and subsidiary against the web, once$il$, $il$Research agent$il$, $il$Both$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-15T12:33:41.000Z'::timestamptz, 1, '{}'::text[], array[$il$i047$il$]::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Brad's suggestion, and a good one. A single long agent run across all companies that checks group and subsidiary relationships against the web and reports what is wrong, rather than Oliver correcting 1,400 records by hand.

It must HIGHLIGHT rather than change. Oliver reviews and approves, because a wrong parent written confidently is worse than no parent at all.

The Recommerce case shows why it is needed and why it is hard: Recommerce Group in France, Recommerce AG, and verkaufen.ch were separate until Recommerce Group acquired Recommerce AG through its Swiss subsidiary RS Switzerland SA in June 2025. A relationship that is true today was false eighteen months ago, so every finding needs a date and a source.$il$,
$il$RUN IT AFTER i047, not before. Without somewhere structured to put a parent, a subsidiary and a relationship type, the run produces a list nobody can apply.

EVERY LINK LANDS UNVERIFIED until a person confirms it, same rule as i047. An agent reading a website is evidence, not proof, and the Save Group and asgoodasnew case shows how a probable ownership note hardens into an assumed fact if nothing marks it as unconfirmed.

IT WILL ALSO FIND THE DUPLICATES, which feeds i056. Recommerce appears four times, including one with a stray exclamation mark from an old character recognition pass.$il$);

-- exactness gate: every item in this part must hash to the value computed from the source file
do $verify$
declare bad text;
begin
  select string_agg(e.item_key, ', ' order by e.item_key) into bad
  from (values
    ('i053', '15ae5f805cde3a888f5d7d2e2dfc6461', 2),
    ('i054', 'db64b11b8e6ac2f799e86455edb416e6', 0),
    ('i055', 'faa1e45b18fb7b12a995298b5e2b2cb8', 0),
    ('i056', '76d9af0aa63ba772759a06bf6357c2e0', 0),
    ('i057', 'fd1ab4b218d1f7085f557315b1993859', 0),
    ('i058', 'df5b4fd24dcc727762cb05db5fd07da9', 0),
    ('i059', 'd660468e982f2b3e656cc964d5f3c0d9', 0),
    ('i060', 'f861aae4b16bd565da4bbe6f14f2d730', 0),
    ('i061', 'f570e2f10ddd455cb1b5af5e883bd65d', 0),
    ('i062', '1387b4ea7cdd2f21bba6f6358e156ebb', 0),
    ('i063', '12d2bf4810cd27e7295097c35f5659c5', 0),
    ('i064', 'd7d9b8de2c459891af6a7c99451a4546', 0),
    ('i065', 'b17228f74630cd1fe55a69d92ee45d69', 0),
    ('i066', 'd0bb412a265b7f5207355aaf1953c114', 0),
    ('i067', '68a4fbeac63da5f84089f52d6d02cf97', 0),
    ('i068', '2bdb758837fbca5402891ab77c3eee70', 0)
  ) as e(item_key, src_md5, n_comments)
  left join public.improvements i
    on i.item_key = e.item_key and i.team_id = (select id from public.teams limit 1)
  where i.id is null
     or e.src_md5 is distinct from md5(concat_ws(chr(31),
      i.title, i.category, i.owner, i.priority, i.status, coalesce(i.raised_by,''), i.detail, i.notes,
      coalesce(i.done_by,''), array_to_string(i.blocks,','), array_to_string(i.blocked_by,','),
      coalesce(i.build_wave::text,''), i.pinned::text, i.hidden::text,
      to_char(i.created_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), coalesce(to_char(i.done_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),''), i.seen_by::text,
      coalesce((select string_agg(concat_ws(chr(31), c.who, to_char(c.at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), c.text), chr(30) order by c.at)
                from public.improvement_comments c where c.improvement_id = i.id), '')));
  if bad is not null then
    raise exception 'F18.5 import: rows differ from the source export: %', bad;
  end if;
end
$verify$;
