-- 118b_f18_5_improvement_log_import_p08
-- F18.5(b) improvement log import, part 8 of 12: i082..i091 (10 items, 5 comments).
-- GENERATED by scripts/gen_improvement_log_import.py from 260920_lovable_improvement_log_export.json - do not edit by hand.
-- Text is dollar-quoted and must stay byte-for-byte; the DO block at the end rolls the part back if not.

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i082$il$, $il$Cannot send LinkedIn messages. Send fails unauthorized, same as AI edit$il$, $il$Outreach & drafting$il$, $il$Brad$il$, $il$blocker$il$, $il$done$il$, $il$Oliver$il$, '2026-09-16T10:01:50.000Z'::timestamptz, 0, '{}'::text[], '{}'::text[], $il$Brad$il$, '2026-09-18T10:44:17.835Z'::timestamptz, false, false, $il${"Brad": "2026-09-18T07:53:04.206Z"}$il$::jsonb,
$il$BLOCKER. Press Send now on an approved draft and it returns: Send failed: unauthorized. Try again or send manually from LinkedIn. Nothing goes out.

READ THIS WITH i070. AI edit fails with unauthorized. Send fails with unauthorized. Same word, two different functions, on the same day. They are almost certainly one fault, not two, and fixing them as one thing will be faster than chasing them separately.

THE PATTERN SO FAR: reads work. The page loads, drafts render, the guards evaluate, the lint scores. What fails is anything that ACTS: rewriting a draft, sending a message. That points at the session token not reaching the functions that perform actions, rather than at the model or at LinkedIn.

It also means the review queue cannot drain at either end. Drafts cannot be corrected, and now they cannot be sent. 74 were waiting yesterday with one message sent.$il$,
$il$THE FASTEST TRIAGE, in order:
1. Does Regenerate work? It was the question on i070 and it now splits three ways rather than two. If Regenerate works but AI edit and Send both fail, the model credential is fine and it is the action routes. If Regenerate also fails, everything that calls out is failing and it is one credential or one token.
2. Does a reload fix it? If an expired session shows up as unauthorized instead of asking Oliver to sign in again, then the session handling is the bug and the two symptoms are just where it surfaces.
3. Is it every draft or some? Same question as i070, and the answers should match. If they do not, they really are two bugs.

THE FALLBACK IN THE MESSAGE IS THE DANGEROUS PART. Try again or send manually from LinkedIn is sensible advice and it quietly breaks the record: a message sent by hand in LinkedIn is a touch that Lovable did not write. That is i048 and i052, and the four hourly watcher should catch it, but only for DMs. So if Oliver works around this for a few days, expect gaps. Worth confirming the watcher backfills anything sent manually during the outage, and worth saying so in the toast.

CHASER 3 OF 2, VISIBLE ON THE SAME SCREEN, is a separate defect and it is evidence for i053. The footer reads logged as chaser 3 of 2. A sequence cannot be at position three of two. i053 predicted exactly this: a duplicated touch row makes the sequence think it is a step further along than it is. That is no longer a theory, it is on screen.

THE GUARDS ARE WORKING WELL, again worth saying. On this draft they read: do not restate the Garantieverlaengerung wedge or the 4-5x figure, both already spent; no question mark anywhere in the message; no meeting, call or estimate offer; do not mention that this is a third message or reference the prior touches. That is the exit message doctrine applied correctly and automatically, which is the hard part and it is done.$il$);
insert into public.improvement_comments (team_id, improvement_id, who, at, text)
select i.team_id, i.id, $il$Claude$il$, '2026-09-16T10:19:52.000Z'::timestamptz,
$il$16 Sept: Regenerate now also fails unauthorized, so AI edit, Regenerate and Send are all down with the same error. This is not a send specific bug. Root cause and the full picture are in i070; keep this item for the send specific detail, the manual fallback risk and the chaser 3 of 2 evidence.$il$
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i082$il$;
insert into public.improvement_comments (team_id, improvement_id, who, at, text)
select i.team_id, i.id, $il$Claude$il$, '2026-09-17T10:35:00.000Z'::timestamptz,
$il$17 Sept, STILL BROKEN, third day. Oliver pressed Send now on the message 3 of 3 German DM to Hermann-Wilhelm Wantia and got the same Send failed: unauthorized. Try again or send manually from LinkedIn. Screenshot attached. Note this is a DIFFERENT fault from i096, which is a database constraint refusing a write; this one is still the unauthorized family with i070.$il$
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i082$il$;
insert into public.improvement_comments (team_id, improvement_id, who, at, text)
select i.team_id, i.id, $il$Claude$il$, '2026-09-17T12:20:00.000Z'::timestamptz,
$il$17 Sept, THE MANUAL FALLBACK IS NOW A KNOWN LOSS, not a risk. These notes assumed the four hourly watcher would backfill anything Oliver sent by hand, at least for DMs. It did not: his 7 September DM to Marjolein van Osch at Fairphone is still absent from Lovable and Sales Nav ten days later. Recorded on i048. So while send is down, every message Oliver sends manually should be treated as unrecorded and written back deliberately, and the toast should stop implying the system will pick it up.$il$
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i082$il$;

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i083$il$, $il$Put the company facts on the review card so a draft can be judged at a glance$il$, $il$Outreach & drafting$il$, $il$Both$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-16T10:03:19.000Z'::timestamptz, 4, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$The tiles under the contact name work well: free DM 0 credits, 2nd degree, message 1 of 3, DE, profile updated 1d ago. They are all about the SEND. Nothing on the card is about the COMPANY, which is what actually decides whether the message is right.

Add a second row of tiles carrying the company facts:
  Insurance state: greenfield, monthly, or yearly
  The incumbent by name, where there is one
  The wedge, in two or three words
  Research stage, and whether it was the agent or a person, per i079
  The score, and its confidence
  Physical stores, yes or no
  A group flag where the company belongs to one with a live deal

Row one is about the send. Row two is about the company. Then approve, edit or reject can be decided from the top of the card instead of by opening the company in another tab.$il$,
$il$MOST OF THIS IS ALREADY ON THE CARD, JUST NOT SKIMMABLE, which is worth Brad knowing before he builds anything new. Why this now on the Robert Karl draft reads: cold open to a P0 whale operator with a live competitor, bolttech, on the book; anchors on publicly visible product detail to prove research was done; asks a discovery question rather than pitching, since this is a displacement play against an incumbent. That paragraph contains the insurance state, the incumbent, the wedge and the strategy. It is genuinely good. It is also four lines of prose, and Oliver is reviewing dozens.
So this is as much about form as content: keep the paragraph, and lift the four or five facts out of it into tiles above it.

COLOUR ONLY THE ONES THAT SHOULD STOP YOU. If every tile looks the same they all get skipped. Neutral for context, amber for check this, red for do not send. A group collision or an unresearched company should be visibly different from DE or 2nd degree.

BILLING SHAPE IS THE ONE PEOPLE FORGET. Greenfield and yearly incumbents are the priority; monthly across the whole range is deprioritised, not excluded. That is a ranking rule already in use, and it is invisible on this card today even though it changes whether the message is worth a credit at all.

WHAT NOT TO ADD. Anything that does not change the approve, edit or reject decision stays on the company record. The test for a tile is whether Oliver would act differently if it said something else. Revenue and employee count fail that test; insurance state passes it.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i084$il$, $il$A draft broke its own guardrail and still scored LINT 100$il$, $il$Outreach & drafting$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Claude$il$, '2026-09-16T10:04:19.000Z'::timestamptz, 4, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$On the Robert Karl draft, guardrail one reads: do not lead with Pier Protect's own attachment rate stats or the 4-5x multiple, this is discovery not pitch.

The draft contains: Wir helfen Partnern das 4-5 Fache.

The lint score reads 100.

So the guardrails are being generated and displayed, and then not checked against the text. A score of 100 currently means the message was written, not that it passed anything.

That matters more than one bad draft. Oliver is being asked to review at volume, and a score that looks like a pass but is not one is worse than no score, because it invites approval. Either the lint evaluates every displayed guardrail, or the number should not be shown.$il$,
$il$HOW IT SHOULD BEHAVE: each guardrail is a check with a pass or fail against the current text, re-run on every edit and regeneration. The score is the count that passed. A failing guardrail turns red on the card and blocks Approve until it is resolved or explicitly overridden with a reason, the same override pattern as i055.

THE HARD PART IS THAT THESE ARE SEMANTIC, NOT STRING MATCHES. Do not use a hard meeting ask cannot be checked with a regular expression. But the two on this card that were broken are the easy kind: the 4-5x multiple is a literal, and a question mark rule is a literal. Do the literal ones as real lint now, and route the semantic ones to a model check. Partial enforcement that is honest about which rules it actually tested beats a single number that implies all of them.

SHOW WHAT WAS CHECKED. If the score covers four of seven guardrails, say four of seven. That is the same argument as i061, why this message was written: a number with no visible basis gets trusted until it fails badly once, and then it never gets trusted again.

TWO MORE THINGS ON THE SAME DRAFT. It signs off Oli, which is i067 again and now three sightings. And the body appears to stop mid sentence, at Wir helfen Partnern das 4-5 Fache, with the sign off directly after. Worth confirming whether that is the real content or the textarea cropping in the screenshot, because a truncated send is a different and worse bug.$il$);
insert into public.improvement_comments (team_id, improvement_id, who, at, text)
select i.team_id, i.id, $il$Claude$il$, '2026-09-17T11:05:00.000Z'::timestamptz,
$il$17 Sept: LINT 100 again, on the German draft to Hartmut Baumann, which carries two grammar errors and three abbreviations. Raised separately as i098 because it is a different gap from this one. This item is about displayed guardrails not being evaluated; i098 is about the text not being checked for correctness at all. Same misleading number, two causes.$il$
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i084$il$;
insert into public.improvement_comments (team_id, improvement_id, who, at, text)
select i.team_id, i.id, $il$Claude$il$, '2026-09-17T15:20:00.000Z'::timestamptz,
$il$17 Sept, SECOND UPDATE, AND IT CORRECTS PART OF THIS ITEM. The WeFix draft to Louis Salzman-Le Goff scores LINT 85, not 100, and shows a real failure underneath the draft in red: Use Partner not client. So the lint IS evaluating something and CAN score below 100. This item said a score of 100 currently means the message was written; that is too strong. What is true is that it checks some rules and not others, and gives no indication which.

THE SHARPER PROBLEM IS NOW VISIBLE. The rule failed, the failure is displayed, the draft still says clients twice, and Approve was available and worked. So a failing check does not block approval. That is exactly what this item asks for and there is now a screenshot of it not happening.

So the two asks separate cleanly. Evaluate every displayed guardrail, and say how many of them were actually tested. And make a failure block Approve until it is fixed or explicitly overridden with a reason.$il$
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i084$il$;

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i085$il$, $il$The tabs and the Draft Status filter are two status filters that silently cancel each other$il$, $il$Lovable UI$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-16T10:18:32.000Z'::timestamptz, 5, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Oliver approved two drafts, then filtered Draft Status to Approved and got No outreach touches found. He reasonably concluded the approvals had been lost.

They were not. The tab bar reads Approved 3, so they saved correctly.

THE LIKELY CAUSE IS NOT A BROKEN FILTER. The tabs ARE a status filter. Pending Review was still the selected tab while Draft Status was set to Approved, and a touch cannot be both. The empty result is arithmetically correct and completely unhelpful, because nothing on the screen says the two controls are fighting.

FIX THE CONTRADICTION, NOT THE FILTER. Either selecting a Draft Status moves the tab to match, or the Draft Status control disappears while a status tab is active, or the empty state says why: no results, because the Pending Review tab and the Approved filter cannot both be true.

No outreach touches found is the wrong message for a contradiction. It reads as the data is missing, which is exactly the conclusion Oliver drew, and with approvals it is an alarming one.$il$,
$il$THIS IS THE SAME SHAPE AS i041, two controls over one piece of state that do not agree. There the header chip and the field below it disagreed about Status. Here the tab and the dropdown disagree about Draft Status. Worth fixing as one habit rather than two bugs: one fact, one control, and where a second view of it exists it reflects rather than competes.

AN EMPTY LIST NEEDS A REASON, ALWAYS. Distinguish nothing matches these filters, which invites clearing them, from nothing exists here, which does not. The current message says neither and implies the worse one.

THE APPROVED PILE IS ABOUT TO GROW, and this matters more than usual this week. Send is broken, see i082, so approving does not send. Oliver said he is going to work through and approve more now. That means a backlog of approved-but-unsent drafts accumulating behind a broken send, in a view he currently cannot filter to. Two things follow:
  Make sure the Approved view is easy to reach and shows how long each has been sitting.
  When send is fixed, there has to be a way to work that backlog, ideally sending from the Approved list rather than reopening each card.

AND APPROVED DRAFTS GO STALE. A message approved today and sent four days later can reference something that has moved, and the day-7 reply check timing is computed from the send, not the approval. Worth showing the age of an approved draft and flagging anything approved more than a couple of days ago for a re-read before it goes.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i086$il$, $il$Settle what Refurbished and SIM-free mean, because the data already answers it differently$il$, $il$Data & schema$il$, $il$Both$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-16T10:34:56.000Z'::timestamptz, 1, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Oliver asked to confirm the two fields. His reading: refurbished Yes means they sell refurbished; SIM-free Yes means they also sell NEW phones without a contract.

The first half is right. The second half is not how the field has been filled, and the lake proves it.

SIM-FREE MEANS CONTRACT-FREE, NOT NEW. In retail it describes how a handset is sold, outright and not tied to a network, and it applies to refurbished devices just as much as new ones. A refurbished iPhone bought outright is SIM-free.

THE NUMBERS SETTLE IT. Across the lake: 68 companies are Yes and Yes, 54 are No refurbished and Yes SIM-free, 14 are No and No, and only THREE are Yes refurbished and No SIM-free. Under Oliver's reading every pure refurbisher would sit in that last bucket, and there are 313 companies whose category is Refurbished Specialist. They are not there. They are in Yes and Yes, because whoever filled the field used the standard meaning.

So if the definition changes now, 68 or more existing records become wrong silently. Worth deciding deliberately rather than by drift.$il$,
$il$NEITHER DEFINITION IS QUITE WHAT PIER NEEDS, which is the more useful conclusion. The question that actually decides whether Pier Protect fits is not new versus refurbished. It is HOW THE DEVICE IS SOLD:
  Bought outright by the customer, new or refurbished. The core case. The customer owns it, so protection can be offered after the sale.
  Sold on an operator contract, billed by the telco. A different commercial route, and the reason A1, Drei, spusu and Vodafone are a separate kind of conversation.
  Rented or subscribed, where the customer never owns it. Grover. A different model again, and the reason the Grover wedge is a programme sale rather than a checkout attach.

THE THIRD STATE IS ALREADY HIDING IN ANOTHER FIELD. Category carries Device rental / subscription (Grover model) for 15 companies. So the commercial model is already being recorded, just in the wrong place and only for the rental case.

SUGGESTED SHAPE, to argue with: two questions instead of two booleans.
  CONDITION SOLD: new, refurbished, or both.
  HOW SOLD: outright, on operator contract, rental or subscription. Multi select, since large retailers do more than one.
That answers Oliver's original question cleanly, keeps the 68 existing Yes and Yes records meaningful, and pulls the Grover case out of Category where it does not belong.

THIS IS THE i078 TEST FAILING IN PUBLIC. That item says a field needing a paragraph of explanation is usually two fields. Two people looked at SIM-free and read it differently, and one record in the lake has SIM-free filled in with the word refurbished inside it, which is somebody conflating them at the point of entry. Whatever is decided, it goes in the field help.

MIGRATION NOTE: three records are currently Yes refurbished and No SIM-free. Those three are worth looking at by hand whichever way this goes, because under either definition they are unusual.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i087$il$, $il$Deep link straight to a Lovable record from the logs and from Claude$il$, $il$Integrations$il$, $il$Both$il$, $il$nice$il$, $il$open$il$, $il$Oliver$il$, '2026-09-16T11:55:34.000Z'::timestamptz, 6, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Oliver asked for a Lovable MCP so records can be linked from artifacts. The underlying want is deep links: an entry in this log or in Intel Staging that points at the actual company or contact, one click away, instead of naming it in prose.

THAT PROBABLY DOES NOT NEED A LOVABLE MCP. It needs two things, and one of them already exists.
  The record id, which comes from Supabase, read only. That is the connector in i001.
  The URL pattern, which is already observable from the browser.

Observed patterns so far:
  pier-lead-lake.lovable.app/contacts/<uuid>?tab=overview
  pier-lead-lake.lovable.app/outreach/<uuid>
  pier-lead-lake.lovable.app/reconciliation?tab=replies
The companies pattern has not been confirmed yet and should be, along with whether a tab can be targeted directly, for instance straight to Conversation.

So this is mostly waiting on i001 rather than on a new tool. Low priority, as Oliver said, but it gets close to free once the connector works.$il$,
$il$THE PAYOFF IS IN INTEL STAGING MORE THAN HERE. Those entries name a company and then describe which fields should change. With a deep link, each one becomes a click through to the record being corrected, which is the difference between a list of findings and a work queue. The Save Group and asgoodasnew entry, the three spusu records, the Patrick Bruecker reconciliation, all of them currently make the reader go and find the record by hand.

OLIVER'S WRITE INSTINCT MATCHES WHAT IS ALREADY BUILT, worth confirming rather than re-deciding. Nothing gets entered from the Lovable side by an agent; writes go through Supabase under the write guard, which runs proposals into a Data Review Board, waits for Oliver's approval, then applies one primary key scoped statement at a time. That is the design as of 16 September and it is at its most cautious setting. So read only linking is exactly the right scope for this item.

IF A LOVABLE MCP DOES EXIST, the question to ask before adopting it is what it gives that Supabase does not. Supabase already has the data. A Lovable layer would mostly add app concepts, routes and views, which matter for links but are simpler to hard code as a URL pattern than to depend on another connector, another auth and another thing that can return unauthorized. Given this week, that last point is not theoretical.

WORTH DOING WHEN IT LANDS: put the record link on the item itself in both logs, as a small button, rather than pasting URLs into the text where they age badly and cannot be checked.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i088$il$, $il$A New message button, so Oliver can start a conversation himself$il$, $il$Outreach & drafting$il$, $il$Both$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-16T12:31:58.000Z'::timestamptz, 3, '{}'::text[], array[$il$i052$il$]::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Everything Lovable sends today comes out of a sequence. There is no way for Oliver to simply message someone because he has decided to. Add a New message button on the contact, with a channel choice: LinkedIn DM, InMail, or email.

It should let him write it himself OR generate a draft. He must be able to type two lines without waiting for a model.

THE GUARDS STILL RUN. This is the obvious way to build a hole in the side of the system: a manual send button is exactly the route that skips the cooldown, the do not contact flag, the Monday suppression, the group collision check and the daily connection request budget. So the button runs the same gate as everything else, shows what the gate says, and allows an override only with a reason and only by Oliver.

Same channel rules as i052: connected means a free DM, not connected means an InMail and a credit, email only where the market allows it. Preselect the right one rather than offering four equal options.

And it is a touch like any other. Written at the moment of sending, and it gets a follow up, defaulting to automatic per i063.$il$,
$il$THE SEQUENCE COUNTER IS THE TRAP. An off sequence message has to not corrupt message 1 of 3. Decide explicitly whether a manual send advances the sequence, sits outside it, or starts a new one, and show which on the card. This matters more than it sounds because the counter is already wrong in at least one place: a draft on 16 September read logged as chaser 3 of 2, which is i053. Adding an untyped manual touch on top of that makes the position meaningless.

WHAT IT IS ACTUALLY FOR, worth writing down so the design serves it. Oliver has just met someone at an event. Someone has been recommended by a partner. A company has posted something that makes today the day. A reply came in somewhere else and the thread needs restarting. None of those are sequence events, and all of them are the highest value messages he sends, because they carry a real reason.

SO THE WHY THIS NOW FIELD SHOULD BE WRITABLE HERE. For a sequenced message the system explains itself. For a manual one, Oliver knows the reason and nothing else does. Capturing it in one line at the point of sending is what keeps the record readable in three months, and it is the input for the follow up logic deciding what to do when there is no reply.

IT SHARES EVERYTHING WITH i052 EXCEPT THE STARTING POINT. Same composer, same channel selector, same guard check, same touch write, same follow up setter. One is replying inside a thread, the other is opening one. Build the composer once.

ONE LIMIT WORTH KEEPING: one person at a time. A New message button that can be pointed at a filtered list is a bulk sender, and that is a different thing with a different risk profile, especially while the LinkedIn account is throttled. See i071 and i019.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i089$il$, $il$Hard block on cold email where it is not permitted, with a recorded consent exception$il$, $il$Guards$il$, $il$Both$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-16T12:32:55.000Z'::timestamptz, 2, '{}'::text[], array[$il$i005$il$]::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Cold email is not permitted in several of our markets. The system needs to refuse it rather than warn about it, with one exception: where the contact has opted in or agreed, email is allowed and the agreement is recorded.

Oliver is right that the rules still need defining. That is the first task, and it is a decision rather than a build.

THE WORKING RULE TODAY, for reference and to be confirmed rather than assumed: cold email is permitted for France, Belgium, Netherlands and Switzerland-targeted contacts. Germany, Austria, Spain, Luxembourg and Czechia are LinkedIn led. Italy is recorded inconsistently in our own notes, listed as LinkedIn led in one place and as unruled in another, so it needs settling explicitly.

IT READS THE CONTACT'S COUNTRY, NOT THE COMPANY'S. Coolblue is the worked example: Dutch company, German country manager. Company country would clear the email. Contact country stops it. Same point as i038 and i054.

FAIL CLOSED. Unknown country means no email. An unknown must never default to permitted on a control like this.

Oliver flagged it as for later. I have put it as a must, because the email channel is being built now in i026 and i052, and a compliance block designed in is a different job from one retrofitted onto a live channel. Knock it back if you disagree.$il$,
$il$THE CARVE OUT THAT MATTERS MOST: A REPLY IS NOT COLD EMAIL. Someone who emails us first has opened the conversation, and replying is plainly legitimate. A naive country block would have stopped today's reply to Zuzanna Nowak at refurbed, who is in Austria and wrote to Oliver. If the guard cannot tell an inbound thread from a cold approach it will block the most valuable email we send. So the rule is about INITIATING, and the check is whether they contacted us first.

CONSENT NEEDS ITS OWN RECORD, not a tick box. If email is allowed because someone agreed, the record has to say when, how, and where the evidence is. Verbally on a call, in writing in a thread, through a form, at an event. A bare consent equals yes field is worth very little if it is ever questioned, and it is the kind of thing that gets questioned precisely when it matters.

QUESTIONS THE DEFINITION HAS TO ANSWER, worth listing so the conversation is short:
  Which countries, confirmed rather than inherited from a note.
  Does an existing business relationship count as a basis, since several jurisdictions allow a soft opt in to an existing customer, and we are not their supplier.
  Does a B2B business address change anything, since some regimes treat business contacts differently from consumers.
  Does a personal email at a company domain differ from a role address like info at.
  How long consent lasts, and whether it survives the person changing employer.

THIS IS A LEGAL QUESTION WITH A PRODUCT IMPLEMENTATION, not the reverse. Worth someone qualified confirming the country list and the consent basis before it is coded, because getting it wrong is a regulator matter rather than a wasted message. Oliver and Brad should agree the mechanism; somebody else should sign off the rule.

THE UNSUBSCRIBE SIDE COMES WITH IT. Whatever is built has to honour an opt out immediately and permanently, which the lake already models as status Opted out plus the do not contact flag with the next action cleared. Lovable needs the same, and it needs to be the one thing no override can get past.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i090$il$, $il$Monday-only contacts can never be matched, so their messages recur in the queue forever$il$, $il$Integrations$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Claude$il$, '2026-09-16T12:36:07.000Z'::timestamptz, 2, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Oliver asked why Patrick Bruecker is not in Lovable. The answer: he is not in the lake either. Searched on 9 September across Contacts and Companies, there is no Bruecker under any spelling. He exists only in monday, on the asgoodasnew account.

That is not an import bug. asgoodasnew is C290, a live monday deal, and its contacts are deliberately blocked from the lake with the note worked in Monday, not the Lake. Patrick was never a lake contact, so there was nothing for Lovable to receive.

THE PROBLEM IS WHAT HAPPENS NEXT. Every message to or from a monday-only contact arrives in Reconciliation with nothing to match it to. Oliver dismisses it, and the next one appears. There is no state in which the queue is clean, because the matching target does not exist by design.

Two ways out, and it is worth choosing rather than drifting:
  Import monday contacts as suppressed, read only records purely so messages can attach to them, clearly marked worked in monday and excluded from every worklist, draft and count.
  Or teach Reconciliation to recognise a monday company and route the message there with a label, instead of offering it for assignment to a Growth Engine contact.

The first keeps the message history complete in one place. The second is less work. Either beats the current state, which is a queue that cannot be emptied.$il$,
$il$THIS IS THE SECOND HALF OF i044. That item is about monday suppression being applied inconsistently across screens. This is the case where suppression is working correctly at the company level and still produces a permanently dirty queue, because the contact does not exist to be suppressed. Worth fixing together.

IT IS NOT ONE CONTACT. Every contact on every monday deal is in this position, and monday deals are the accounts with the most conversation, because they are the ones actually progressing. So the volume of unmatchable messages grows with success, which is the wrong way round.

THE REAL QUESTION UNDERNEATH: WHERE DOES A MONDAY CONVERSATION LIVE. Today a message to Patrick sits in LinkedIn, is picked up by the watcher, arrives in Lovable with nowhere to go, and the deal it belongs to is in monday. Three systems, no owner. The clean sheet answer in i069 is one system; until then, at minimum decide which of the three is supposed to hold it so the other two can stop asking.

AND IT AFFECTS THE NUMBERS. Unmatched messages from monday contacts inflate the reconciliation count and depress the apparent match rate, so neither figure means what it looks like while this is unresolved.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i091$il$, $il$Companies shows page 1 of 23 with no way to turn the page$il$, $il$Lovable UI$il$, $il$Brad$il$, $il$nice$il$, $il$open$il$, $il$Oliver$il$, '2026-09-16T12:36:36.000Z'::timestamptz, 5, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$The Companies list ends at the bottom of the first page. The footer reads 1,137 companies, page 1 of 23, so the pagination exists and knows there are 22 more, but there is nothing to click.

Contacts has Previous and Next buttons in the same footer. Companies does not, or they are not visible.

ONE CHEAP THING TO CHECK FIRST: the Edit with Lovable badge sits in the bottom right corner, which on Contacts is exactly where the Previous and Next buttons are. They may be there and covered rather than missing. Worth looking before building anything.

Oliver marked this very low priority and it is.$il$,
$il$PAGINATION IS NOT REALLY THE ANSWER HERE, which is why the low priority is right. Twenty three pages of 1,137 companies in no useful order is not something anyone pages through. Nobody is going to click Next twenty times looking for a company. What makes this list usable is the ranked, score sorted view in i071, plus search and filters. Once those exist, page 2 is somewhere you almost never need to go.

SO IF IT IS A QUICK FIX, DO IT, and if it is not, it can wait behind i071. The only case where paging genuinely matters is working systematically through a filtered set, for instance every company that is Untouched in Germany, and that is a case where the filter has already cut 1,137 down to something small.

WHILE IN THERE, the same footer inconsistency is worth a glance across the other lists. Contacts has the controls, Companies appears not to, and an interface where the same footer behaves differently in two places is the kind of thing that makes someone doubt the whole screen.$il$);

-- exactness gate: every item in this part must hash to the value computed from the source file
do $verify$
declare bad text;
begin
  select string_agg(e.item_key, ', ' order by e.item_key) into bad
  from (values
    ('i082', '0f23236cca9082ed8c8c8abf98dd5067', 3),
    ('i083', '3bbf0f401dbb0d8720d99288e0e2ade8', 0),
    ('i084', '6bf2a739267aed26e95207f34c1f1db2', 2),
    ('i085', '0420dc5b0aacb9e62619d86bc3110f12', 0),
    ('i086', '84277c5d83290eafdf9d5eb0b333be95', 0),
    ('i087', '9a3e8fa60a77d9b8f51bc91c407159a0', 0),
    ('i088', 'b835e3cfcc84b79d968a1e69c18c2af4', 0),
    ('i089', '19124119f2b19ecbd65058a27963532b', 0),
    ('i090', '48d6e4d8245030ddeb210d49de81b47c', 0),
    ('i091', 'e7c401129dad517742ba2b956bd9620f', 0)
  ) as e(item_key, src_md5, n_comments)
  left join public.improvements i
    on i.item_key = e.item_key and i.team_id = (select id from public.teams limit 1)
  where i.id is null
     or e.src_md5 is distinct from md5(concat_ws(chr(31),
      i.title, i.category, i.owner, i.priority, i.status, coalesce(i.raised_by,''), i.detail, i.notes,
      coalesce(i.done_by,''), array_to_string(i.blocks,','), array_to_string(i.blocked_by,','),
      coalesce(i.build_wave::text,''), i.pinned::text, i.hidden::text,
      to_char(i.created_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), coalesce(to_char(i.done_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),''), i.seen_by::text,
      coalesce((select string_agg(concat_ws(chr(31), c.who, to_char(c.at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), c.text), chr(30) order by c.at)
                from public.improvement_comments c where c.improvement_id = i.id), '')));
  if bad is not null then
    raise exception 'F18.5 import: rows differ from the source export: %', bad;
  end if;
end
$verify$;
