-- 118b_f18_5_improvement_log_import_p12_tail
-- F18.5(b)(d): legacy activity carried over verbatim, the three contact links, then the
-- activity triggers (created last so the import wrote no activity of its own), then counts.
-- GENERATED by scripts/gen_improvement_log_import.py - do not edit by hand.

-- the only activity_log entries present in the export (2 rows); `action` is the export's `what`
insert into public.improvement_activity (team_id, improvement_id, item_key, who, at, action, before, after)
select i.team_id, i.id, i.item_key, $il$Oliver$il$, '2026-09-15T13:06:14.708Z'::timestamptz, $il$reopened it$il$, null, $il${"imported_from": "artifact activity_log", "who": "Oliver", "at": "2026-09-15T13:06:14.708Z", "what": "reopened it"}$il$::jsonb
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i001$il$;
insert into public.improvement_activity (team_id, improvement_id, item_key, who, at, action, before, after)
select i.team_id, i.id, i.item_key, $il$Oliver$il$, '2026-09-09T11:55:16.754Z'::timestamptz, $il$reopened it$il$, null, $il${"imported_from": "artifact activity_log", "who": "Oliver", "at": "2026-09-09T11:55:16.754Z", "what": "reopened it"}$il$::jsonb
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i021$il$;

-- links (F18.5d)

-- i094 -> Florian Pfeiffer
do $link$
declare n int; cid uuid;
begin
  select count(*) into n from public.contacts where team_id = (select id from public.teams limit 1) and contact_id = 'P706';
  if n <> 1 then raise exception 'F18.5 link i094: expected exactly 1 contact for (contact_id = P706), found %', n; end if;
  select id into cid from public.contacts where team_id = (select id from public.teams limit 1) and contact_id = 'P706';
  update public.improvements set linked_contact_id = cid where team_id = (select id from public.teams limit 1) and item_key = 'i094';
  if not found then raise exception 'F18.5 link: item i094 not found'; end if;
end
$link$;
-- i053 -> Urs Moeller
do $link$
declare n int; cid uuid;
begin
  select count(*) into n from public.contacts where team_id = (select id from public.teams limit 1) and contact_id = 'P703';
  if n <> 1 then raise exception 'F18.5 link i053: expected exactly 1 contact for (contact_id = P703), found %', n; end if;
  select id into cid from public.contacts where team_id = (select id from public.teams limit 1) and contact_id = 'P703';
  update public.improvements set linked_contact_id = cid where team_id = (select id from public.teams limit 1) and item_key = 'i053';
  if not found then raise exception 'F18.5 link: item i053 not found'; end if;
end
$link$;
-- i100 -> Frank Pelzer
do $link$
declare n int; cid uuid;
begin
  select count(*) into n from public.contacts where team_id = (select id from public.teams limit 1) and last_name = 'Pelzer';
  if n <> 1 then raise exception 'F18.5 link i100: expected exactly 1 contact for (last_name = Pelzer), found %', n; end if;
  select id into cid from public.contacts where team_id = (select id from public.teams limit 1) and last_name = 'Pelzer';
  update public.improvements set linked_contact_id = cid where team_id = (select id from public.teams limit 1) and item_key = 'i100';
  if not found then raise exception 'F18.5 link: item i100 not found'; end if;
end
$link$;

-- who is acting: the signed-in user's email, else 'system'
create or replace function public.fn_improvement_log_actor()
returns text
language sql
stable
security definer
set search_path to 'public', 'pg_temp'
as $fn$
  select coalesce((select u.email::text from auth.users u where u.id = (select auth.uid())), 'system');
$fn$;
revoke all on function public.fn_improvement_log_actor() from public;
revoke all on function public.fn_improvement_log_actor() from anon;

-- improvements -> improvement_activity. before/after hold only the columns that changed.
-- updated_at and seen_by are ignored: opening a card is not a change to the item.
create or replace function public.tg_improvements_activity()
returns trigger
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $fn$
declare
  v_before jsonb;
  v_after  jsonb;
  v_action text;
begin
  if tg_op = 'INSERT' then
    insert into public.improvement_activity (team_id, improvement_id, item_key, who, action, before, after)
    values (new.team_id, new.id, new.item_key, public.fn_improvement_log_actor(), 'insert', null, to_jsonb(new));
    return new;
  elsif tg_op = 'DELETE' then
    -- the row is gone, so improvement_id stays null; item_key carries the identity
    insert into public.improvement_activity (team_id, improvement_id, item_key, who, action, before, after)
    values (old.team_id, null, old.item_key, public.fn_improvement_log_actor(), 'delete', to_jsonb(old), null);
    return old;
  end if;

  select coalesce(jsonb_object_agg(o.key, o.value), '{}'::jsonb), coalesce(jsonb_object_agg(o.key, n.value), '{}'::jsonb)
    into v_before, v_after
  from jsonb_each(to_jsonb(old)) o
  join jsonb_each(to_jsonb(new)) n on n.key = o.key
  where o.value is distinct from n.value
    and o.key not in ('updated_at', 'seen_by');

  if v_after = '{}'::jsonb then
    return new;
  end if;

  v_action := case
    when old.status is distinct from new.status and new.status = 'done' then 'done'
    when old.status is distinct from new.status and new.status = 'open' then 'reopened'
    else 'update'
  end;

  insert into public.improvement_activity (team_id, improvement_id, item_key, who, action, before, after)
  values (new.team_id, new.id, new.item_key, public.fn_improvement_log_actor(), v_action, v_before, v_after);
  return new;
end
$fn$;

create or replace function public.tg_improvement_comments_activity()
returns trigger
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $fn$
begin
  insert into public.improvement_activity (team_id, improvement_id, item_key, who, action, before, after)
  values (new.team_id, new.improvement_id,
          (select i.item_key from public.improvements i where i.id = new.improvement_id),
          public.fn_improvement_log_actor(), 'comment', null,
          jsonb_build_object('comment_id', new.id, 'who', new.who, 'at', new.at, 'text', new.text));
  return new;
end
$fn$;

revoke all on function public.tg_improvements_activity() from public;
revoke all on function public.tg_improvements_activity() from anon;
revoke all on function public.tg_improvement_comments_activity() from public;
revoke all on function public.tg_improvement_comments_activity() from anon;

create trigger tg_improvements_activity
  after insert or update or delete on public.improvements
  for each row execute function public.tg_improvements_activity();

create trigger tg_improvement_comments_activity
  after insert on public.improvement_comments
  for each row execute function public.tg_improvement_comments_activity();

-- final gate
do $final$
declare ni int; nc int; na int; nl int;
begin
  select count(*) into ni from public.improvements;
  select count(*) into nc from public.improvement_comments;
  select count(*) into na from public.improvement_activity;
  select count(*) into nl from public.improvements where linked_contact_id is not null;
  if ni <> 109 or nc <> 34 or na <> 2 or nl <> 3 then
    raise exception 'F18.5 import totals wrong: items % (want 109), comments % (want 34), activity % (want 2), links % (want 3)', ni, nc, na, nl;
  end if;
end
$final$;
