-- 118b_f18_5_improvement_log_import_p09
-- F18.5(b) improvement log import, part 9 of 12: i092..i099 (7 items, 7 comments).
-- GENERATED by scripts/gen_improvement_log_import.py from 260920_lovable_improvement_log_export.json - do not edit by hand.
-- Text is dollar-quoted and must stay byte-for-byte; the DO block at the end rolls the part back if not.

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i092$il$, $il$The drafting agent is reading unsent drafts as if they were sent messages$il$, $il$Outreach & drafting$il$, $il$Both$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-16T13:16:17.000Z'::timestamptz, 4, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Florian Pfeiffer, P706. The whole thread so far is ONE connection request, sent 28 August. Nothing else has gone out. The footer knows this and says logged as message 1 of 3.

The agent does not. The draft it has just written opens Hallo Florian, eine Sache noch zu dem Geraetekauf ohne Tarif. One more thing, to somebody who has received nothing.

The reason is visible directly underneath: PREVIOUS DRAFTS 2. A first message written 4 September and a follow up written 8 September, neither sent. The agent has read them as history and written a third touch on top.

THE FIX: drafts are drafts. They must be labelled as unsent and must never count as messages in the history the drafting agent reads, or in the sequence position.

Do not hide them from the model though. Showing prior drafts stops it regenerating the same thing twice. Show them clearly marked as UNSENT DRAFTS, never as part of the conversation.$il$,
$il$IT IS NOT COSMETIC. Eine Sache noch to a person who has heard nothing from us reads as though we have lost track of who we are talking to, on the very first real touch. That is the opposite of the impression the whole opener is designed to create, and it is worse in German where the continuation is unmistakable.

IT IS THE SECOND WAY THE SEQUENCE POSITION IS BEING CORRUPTED, from a different direction than i053. There, a duplicated touch row made the counter read chaser 3 of 2. Here, unsent drafts are inflating what the agent believes has been said. Both come from the same missing definition: nothing states clearly what counts as a touch. A touch is a message that left the building. Not a draft, not a revision, not a row that got written twice.

THE FOOTER IS ALREADY RIGHT, which is useful. It says message 1 of 3 and it is correct. So the sequence logic and the drafting context are reading two different things. Point them at the same source and this closes.

A DRAFT ON THIS SCREEN IS SIGNED BRAD. The 8 September regenerated version ends with the name Brad rather than Oliver. That is not the Oli variant in i067, it is a different person's name on Oliver's outbound, and it could have been sent. Widening i067 accordingly.

THE LANGUAGE ALSO MOVES WITHIN ONE THREAD. The 4 September draft is English, the 8 September one German, the current one German. Whatever decides language is not stable per contact. Minor next to the rest, but worth a look while the drafting context is being fixed, since it points the same way: the agent is not being given a consistent view of the thread.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i093$il$, $il$Which channels are open is a different question from where the conversation is$il$, $il$Data & schema$il$, $il$Both$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-16T14:16:56.000Z'::timestamptz, 1, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Daniel Freudenberger at Rebuy cannot be sent a connection request: LinkedIn wants his email address first, because he has restricted who may invite him. Oliver asked whether Outreach Status should get a Blocked value, and then spotted the flaw himself. He might still email or call, so Blocked would say something untrue about the whole contact.

HE IS RIGHT, AND THE FIX IS NOT A NEW STATUS VALUE. Outreach Status answers where the conversation is: not started, ready, active, contacted, in conversation, cooldown. Channel availability answers something else entirely: which routes are open to this person. Putting one inside the other collapses two axes.

Record it per channel on the contact, with a reason:
  Connection request: available, or not available because LinkedIn requires their email
  InMail: available, and what it costs
  Email: available, no address on file, or not permitted in this market
  Phone: number on file or not

THEN IT STOPS BEING A DEAD END AND BECOMES A ROUTE. For this contact the conclusion follows automatically: the CR is closed, Rebuy is German so cold email is not permitted, which leaves InMail or the phone. The system can say that instead of leaving Oliver to work it out per contact.

Oliver suggested just listing it for now. I have made it a must because it feeds the next step logic and the connection request budget, both of which are live problems this week. Knock it back if you disagree.$il$,
$il$THIS IS THE THIRD TIME THE SAME MISTAKE HAS ALMOST BEEN MADE, which is why it is worth stating as a principle rather than fixing one field. Priority holds OoS, which is a status wearing a priority's clothes, see i041. Refurbished and SIM-free conflate condition with commercial model, see i086. And now a channel constraint is looking for a home inside a pipeline status. The rule: if two facts can be true independently, they are two fields. Oliver caught this one himself before it was built, which is the cheapest place to catch it.

IT FEEDS THE CONTACT LEVEL NEXT STEP, the one we sparred on and have not yet added. Send a connection request is the wrong next step for a person who cannot receive one. With channel availability recorded, the next step derives correctly on its own: CR unavailable, email not permitted, therefore InMail, one credit, or a call. Without it, the next step will keep proposing something impossible.

THERE MAY BE A QUIET SIGNAL IN IT WORTH USING. A profile that requires an email to receive an invitation is one whose owner has deliberately restricted invitations. Those people plausibly accept less often. With the daily allowance now rationed at twenty and the allowance itself keyed to acceptance rate, per i072, deprioritising them may be right regardless. Worth watching rather than assuming, but it argues for recording the flag rather than just working around it.

WHERE THE FLAG COMES FROM. Nobody should type this. It is learned at the moment Oliver tries and LinkedIn refuses, so the cleanest capture is at that point, either by hand in one click or through the extension in i045. A field that depends on somebody remembering to set it will be empty for most contacts and misleading for the rest.$il$);
insert into public.improvement_comments (team_id, improvement_id, who, at, text)
select i.team_id, i.id, $il$Oliver$il$, '2026-09-17T13:30:00.000Z'::timestamptz,
$il$SECOND INSTANCE, AND A HARDER ONE. Marcel de Groot, CEO Vodafone Germany, P-record under Vodafone Germany. He has disabled communication on LinkedIn entirely: no connection request possible and no message possible. Oliver's question was simply how to log it, and today there is nowhere correct to put it.

WHAT HAS HAPPENED INSTEAD IS THE PROBLEM THIS ITEM PREDICTS. His Outreach Status reads Not relevant. He is the chief executive of a target operator. He is extremely relevant and simply unreachable on one channel. A channel fact has been written into a relevance field, and the cost is that every future reader, human or agent, will skip him for the wrong reason and never revisit it.

SO THE ENUM NEEDS THE CLOSED CASE, not just the conditional one. Rebuy's Daniel Freudenberger could still be invited if we had his email. This profile accepts nothing at all. Two distinct values:
  Connection request: not available, profile does not accept invitations
  LinkedIn message: not available, profile has messaging disabled
With both set, the derived answer is LinkedIn closed, and the next step has to come from somewhere else rather than the contact being parked.

AND THE FALLBACK IS A COMPANY LEVEL ANSWER, NOT A CONTACT LEVEL ONE. For a CEO of an operator the right move was never a cold connection request anyway. When every channel on a contact is closed, the system should point at the company and ask who else there is worth approaching, which is the acceptance coverage rule. Closing a contact must not quietly close the company.$il$
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i093$il$;

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i094$il$, $il$Lovable says 1st degree and Accepted, LinkedIn says 2nd degree with the request still pending$il$, $il$Data & schema$il$, $il$Brad$il$, $il$blocker$il$, $il$open$il$, $il$Oliver$il$, '2026-09-17T09:40:09.000Z'::timestamptz, 1, '{}'::text[], '{}'::text[], null, null, false, false, $il${"Brad": "2026-09-20T14:40:50.058Z"}$il$::jsonb,
$il$Florian Pfeiffer, Head of Sales B2C at mobilezone Deutschland (Sparhandy), P706.

LOVABLE SAYS: Connection 1st degree, Connection Status Accepted. That implies a free direct message.

SALES NAVIGATOR SAYS: 2nd degree, Connection sent 8/28/2026, still pending. The timeline shows one event on 28 August, you sent Florian a connection request, and nothing since. There is no accept.

SO THE FREE DM DOES NOT EXIST. Oliver cannot message him without an InMail credit, and the system is telling him he can.

THE RECORD NAMES THE SOURCE OF THE BAD WRITE ITSELF. Next Action reads: CONNECTION STATUS CORRECTED, Request sent to Accepted, 2026-09-02, from Oliver's Sales Nav Recently Accepted Connections list. So something read that list on 2 September and flipped this contact to Accepted when he had not accepted. That means this is not a one-off typo. EVERY CONTACT TOUCHED BY THAT SAME IMPORT ON THAT DATE HAS TO BE RE-CHECKED, and we need to know how many there were.

THE RECORD IS ALSO SELF-CONTRADICTORY: Outreach Status reads To contact while Connection Status reads Accepted. Two fields describing the same person disagree, and nothing flagged it.

WHAT IS NEEDED
1. Correct this record: 2nd degree, connection request sent 2026-08-28, pending.
2. Find every record written by the 2026-09-02 Recently Accepted Connections import and re-verify each one against Sales Navigator.
3. Whatever wrote it must never again set Accepted without a positive accept signal. Absence from a list is not an accept.
4. Connection state needs a source and a date on it, so a wrong write can be traced and reversed without reading it out of a free text Next Action field.$il$,
$il$WHY THIS IS A BLOCKER AND NOT A DATA TIDY-UP. Connection degree is not a display field. Three things run off it: whether the DM is free or costs an InMail credit, which channel the next step proposes, and what the drafter assumes about the relationship. All three are wrong for this contact right now. With the daily connection request allowance rationed at twenty, see i072, and InMail credits finite, a field that says free when the answer is one credit spends real money.

SAME CONTACT AS i092. Florian Pfeiffer is also the record where two unsent drafts are being read as sent messages. So on one person the sequence thinks two messages have gone out and the channel logic thinks he is connected. Neither is true. Fixing one and not the other still leaves the record unusable, and it is worth Brad looking at both on this record together rather than separately.

HOW THE BAD WRITE PROBABLY HAPPENED. The Sales Nav Recently Accepted Connections list is a rolling view. If the importer treated presence in that view as accept and then wrote Accepted to everyone in the batch, or matched the wrong row, a pending invitation gets promoted. The safe version only ever moves a contact forward on an explicit accept event with its own date, and never infers state from a list membership.

RELATED: i053 covers touch identity, the same underlying problem of state being written without a verifiable event behind it. i093 covers channel availability as a separate axis from pipeline position, and this item is the argument for it, because a wrong degree quietly produces a wrong channel.

WHAT OLIVER IS DOING IN THE MEANTIME. Treating Lovable's connection state as unverified and checking Sales Nav before sending anything that depends on it. That is not sustainable across 130 leads, which is why it is a blocker.

EVIDENCE: two screenshots, the Lovable contact card and the Sales Navigator profile, both dated 17 September 2026.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i096$il$, $il$Approve says it worked and the database says duplicate key, so nobody knows which approvals saved$il$, $il$Outreach & drafting$il$, $il$Brad$il$, $il$blocker$il$, $il$open$il$, $il$Oliver$il$, '2026-09-17T10:20:00.000Z'::timestamptz, 0, '{}'::text[], '{}'::text[], null, null, false, false, $il${"Brad": "2026-09-20T14:40:52.761Z"}$il$::jsonb,
$il$THREE INSTANCES ON 17 SEPTEMBER, ALL WITHIN A COUPLE OF HOURS.

Frederic Gandon at Largo, P566. Hartmut Baumann at Electronic Partner, P675. Leonard Coen at topi, P707. Every time, Approve returns a green Draft approved next to a red duplicate key value violates unique constraint draft_revisions_outreach_log_id_revision_number_key.

WHAT THE ERROR MEANS. The draft_revisions table has a unique constraint on the pair outreach_log_id and revision_number. Something tried to insert a revision whose number already exists for that touch.

THE THIRD SCREENSHOT SHOWS THE THING WORTH CHASING: TWO GREEN DRAFT APPROVED TOASTS, stacked, for one card, next to the one error. Two successes and one failure from a single approval is not one write going wrong, it is the approval running more than once. If it fires twice, both runs work out the same next revision number, the first insert takes it and the second collides. That explains the error without needing anything else to be wrong, and it is the first thing to check.

THE OTHER CANDIDATE, STILL OPEN. All three failing cards read PREVIOUS DRAFTS 1. If the next revision number is computed from the count of PREVIOUS drafts and ignores the current one, it lands on a number already in use and collides every time from the first revision onward. That would also fit.

HOW TO TELL THEM APART, CHEAPLY. Look at the server log for one approval click: two requests means the double fire, one request means the number is being computed wrong. Then approve a draft that has never been revised, PREVIOUS DRAFTS absent. If that one fails too, it is the double fire. If it succeeds, it is the count.

EITHER WAY THE WRITE HAS TO BE SAFE TO REPEAT, which is the real fix and is the same for both causes.

THE CARDS HAVE LITTLE ELSE IN COMMON. Largo is French, P1, five touches, message 1 of 3. Electronic Partner is German, P0, one touch, message 1 of 3. topi is German, P1, two touches, message 2 of 3. So it is not the language, the priority, the sequence position or the depth of the history.

NOT LOST APPROVALS, CORRECTING MY FIRST READ. The tab counters balance at every step: 74 pending, 7 approved, 17 rejected, then 69, 10, 19, then 64, 13, 21, then 63, 14, 21. Every drop out of Pending Review is matched by the rise into Approved and Rejected. The status change IS saving. What fails is the revision snapshot written alongside it.

CONFIRM IT IN A MINUTE: open the Approved tab and look for Gandon, Baumann and Coen. All three there means nothing has been lost and this is a false alarm over a real bug. Any missing and it is worse than described.

WHAT IS NEEDED

1. Make approve idempotent. Disable the button on submit, and make the write safe to run twice, so a repeat updates rather than inserts.

2. Stop computing the revision number in application code. Assign it inside the insert statement itself, or drop the column and order revisions by timestamp, keeping the unique constraint only as a guard.

3. Ask whether approving should write a revision at all. If the text has not changed, approving is a status change on the revision that already exists. If every approval forks a new row, the table grows for nothing and every approval is another chance to collide.

4. A failed write must never show a success toast, and a success must never show an error toast. Right now both appear together and neither can be trusted.

5. Decide what a half completed approval leaves behind. If the status saves and the revision does not, the revision history is missing the version that was approved, which is the one that matters when asking later what exactly Oliver signed off.$il$,
$il$THIS IS NOT THE SAME FAULT AS i070 AND i082, and it would be easy to file it with them. Those return unauthorized, which is a credential or token problem. This is the database refusing a write because of a constraint, which is a schema and code problem. Different fix. If they get bundled together, the constraint will still be there after the token is renewed.

IT IS RELATED TO i085 BUT NOT THE SAME. There, the approvals had saved and a filter contradiction made them invisible. Here an approval genuinely did not save. Both leave Oliver asking the same question, did that approval stick, which is why the honest toast in point 3 matters more than either fix taken alone.

THE TIMING MAKES IT WORSE. Send is broken, see i082, so the approved pile is where everything is accumulating. If approvals are also failing silently, that pile is not merely unsent, it is incomplete, and nobody knows by how much.

WHILE IT IS BROKEN. The tab counter is the only trustworthy signal on the screen, because it comes from the database rather than from the toast. Approved read 10 at the time of the screenshot. If Oliver approves ten more and it reaches 20, they all landed. If it lags, some did not.

SEEN ON THE SAME CARD, SEPARATELY. The connection request note to Frédéric is logged twice, two touch rows T503 and T817 both dated 5 Aug 26, and the conversation shows the same text twice as two Sent messages. That is recorded on i053, which now has two instances rather than one.$il$);
insert into public.improvement_comments (team_id, improvement_id, who, at, text)
select i.team_id, i.id, $il$Claude$il$, '2026-09-17T11:05:00.000Z'::timestamptz,
$il$Second instance within the hour, Hartmut Baumann at Electronic Partner, P675. Same two toasts. Also corrected the earlier claim that an approval was lost: the tab arithmetic balances, so the status change is saving and it is the revision insert that fails.$il$
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i096$il$;
insert into public.improvement_comments (team_id, improvement_id, who, at, text)
select i.team_id, i.id, $il$Claude$il$, '2026-09-17T11:45:00.000Z'::timestamptz,
$il$Third instance, Leonard Coen at topi, P707. This one shows TWO green Draft approved toasts for one card alongside the error, which is the strongest lead so far: the approval is running more than once and the second run collides on the revision number it has already used. Detail rewritten around it, with the check that separates it from the count hypothesis.$il$
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i096$il$;
insert into public.improvement_comments (team_id, improvement_id, who, at, text)
select i.team_id, i.id, $il$Claude$il$, '2026-09-17T15:00:00.000Z'::timestamptz,
$il$FOURTH INSTANCE, Kristjan Nemvalts at Upgreat, P694, Estonia. It reads PREVIOUS DRAFTS 1, which makes it four out of four. That correlation is now strong enough to test directly, and it should be tested before anything is changed: approve a draft that has NEVER been revised, so PREVIOUS DRAFTS is absent. If it succeeds, the revision number is being counted from previous drafts only and that is the bug. If it fails too, it is the double invocation seen on the topi card. Five minutes either way.

The counters still balance: 63 pending and 14 approved becomes 61 and 16, with Rejected unchanged at 21. So approvals are still saving and only the revision snapshot is failing. Four instances in, nothing has been lost.$il$
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i096$il$;
insert into public.improvement_comments (team_id, improvement_id, who, at, text)
select i.team_id, i.id, $il$Claude$il$, '2026-09-17T15:20:00.000Z'::timestamptz,
$il$FIFTH INSTANCE, Louis Salzman-Le Goff at WeFix, P657, France. PREVIOUS DRAFTS 1 again, so it is five out of five. Counters 61 and 16 become 60 and 17, Rejected unchanged, still balanced. No new information beyond the correlation hardening, so the test in the previous comment is the only thing left worth doing before a fix is chosen.$il$
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i096$il$;
insert into public.improvement_comments (team_id, improvement_id, who, at, text)
select i.team_id, i.id, $il$Claude$il$, '2026-09-17T16:10:00.000Z'::timestamptz,
$il$SIXTH INSTANCE, Alexander Peretti at 0815, P595, Austria. PREVIOUS DRAFTS 1 again, six out of six. Counters 60 and 17 become 50 and 20 with Rejected 21 to 28, so ten left Pending Review against three approved and seven rejected: still balanced, still nothing lost. The correlation is as proven as it can get from the outside now, and the only remaining question is the one in the comment above, which needs one approval on an unrevised draft to answer.$il$
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i096$il$;

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i097$il$, $il$Approve should queue and drip, Send now should mean now, on LinkedIn and on email$il$, $il$Outreach & drafting$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-17T10:45:00.000Z'::timestamptz, 6, array[$il$i107$il$]::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$TWO BUTTONS, TWO MEANINGS, AND RIGHT NOW THEY BOTH MEAN THE SAME THING.

APPROVE puts the message in a send queue. The queue releases it later, at an irregular interval, inside the day's allowance for that channel. Oliver approves a batch in one sitting and the system spreads it out.

SEND NOW sends it immediately, straight past the queue. That is what the button says and it should be what it does.

SAME MECHANISM FOR EMAIL. Different limits and different reasons, deliverability and warm-up rather than account safety, but one queue and one set of controls, not two systems.

WHAT THE QUEUE NEEDS

1. A DAILY BUDGET PER CHANNEL, not one number for everything. Connection requests, currently throttled at twenty, see i072. DMs. InMail, which is a credit count rather than a daily cap. Email. The queue stops when a channel's budget is spent and says so, rather than trying and failing.

2. IRREGULAR GAPS, NOT A FIXED CADENCE. A message every eleven minutes on the dot is a more obvious pattern than sending them all at once. Randomise the interval, and keep it inside working hours in the recipient's own country, weekdays, nothing at three in the morning.

3. ORDER BY VALUE, BECAUSE THE BUDGET RUNS OUT. If twenty of forty approved requests go today, they should be the best twenty. That is the same argument as i071, score first and spend from the top, applied at the moment of sending rather than the moment of sourcing.

4. VISIBLE AND REVERSIBLE. A Queued state on the touch, the time it is expected to go, and the ability to pull it back before it does. Approving forty messages that then leak out over three days is only safe if Oliver can see the queue and cancel from it.

5. SEND NOW OVERRIDES THE PACING, NEVER THE GUARDS. Do not contact, cooldown, the market rules on cold email in i089, the duplicate approach guard in i004: those still apply. Now means skip the queue, not skip the checks.

6. A FAILED SEND STAYS IN THE QUEUE AND RETRIES. It must never be dropped quietly. This matters more than usual given i082: an outage during a queued run would otherwise lose the whole batch with nothing on screen to say so.

7. THE BUDGET SPLITS BY PRODUCT. Pier Protect and Ticketplan draw on the same LinkedIn account and the same daily twenty. Oliver has to be able to say how much of today goes to each. That is i039, and it lands in this queue.$il$,
$il$WHY THIS IS THE RIGHT SHAPE. Approving and sending are two different decisions and they have been collapsed into one. Approving is a judgement about the message: is this good enough to go. Sending is a question about timing and budget: should it go now, and is there room today. Separating them is what makes it possible to review forty drafts in one sitting, which is how Oliver actually works, without sending forty messages in one sitting, which is how accounts get restricted.

IT IS ALSO THE ONLY WAY THE TWENTY A DAY BECOMES MANAGEABLE. At the moment the allowance is enforced by LinkedIn refusing, which is the worst place to find out, see i071. A queue that knows the budget turns a refusal into a schedule.

WHAT TO BE CAREFUL OF. An approved message goes stale. i085 already asks for the age of an approved draft to be visible; with a queue it matters more, because the delay is deliberate and could run to days when a backlog is draining. The queue should refuse to release anything older than a set age and put it back for a re-read instead. A message that opens on something that has since moved is worse than a message sent a day late.

AND THE QUEUE MUST NOT BECOME A PLACE THINGS GO MISSING. Every queued item needs to be reachable from the contact, not only from a queue screen, so that opening a contact shows there is something pending for them. Otherwise it is a second hidden pile next to the approved one.

DEPENDENCY. Nothing here can be tested until send works at all, i082 and i070. Worth building the queue behind it rather than in front of it, because a queue over a broken send will simply accumulate silently, which is the failure mode in point 6.

ONE OPEN QUESTION FOR BRAD. Does the queue release on a server side job or only while the app is open. It has to be server side, otherwise the spread only happens while Oliver has the tab open, which defeats the point. Worth confirming early because it decides where this gets built.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i098$il$, $il$Drafts carry typos and grammar errors in both German and English, and the lint does not check for them$il$, $il$Outreach & drafting$il$, $il$Both$il$, $il$must$il$, $il$open$il$, $il$Claude$il$, '2026-09-17T11:05:00.000Z'::timestamptz, 4, '{}'::text[], '{}'::text[], null, null, false, false, $il${"Brad": "2026-09-18T09:03:25.680Z"}$il$::jsonb,
$il$The draft to Hartmut Baumann, Director Purchasing at Electronic Partner, P675, a German P0 contact. LINT 100.

WHAT IS IN IT
  unsere monatliches Versicherungsabo. Abo is neuter, so it is unser monatliches Versicherungsabo.
  Ich bin dabei Partnerschaften ... auszubauen. The infinitive clause needs a comma: Ich bin dabei, Partnerschaften ... auszubauen.
  idR. for in der Regel.
  im vgl. zu for im Vergleich zu, and lower case where it is a noun.
  standard "opt-in" Produkten, with an English term in straight quotes and a lower case adjective where German wants Standard.
  A double space after the closing bracket.

IT IS NOT ONE DRAFT. The German exit message to Hermann-Wilhelm Wantia on the same day reads für unsere partner, lower case, in a language that capitalises every noun. Two German drafts on one morning, both with basic errors.

WHY IT MATTERS MORE THAN IT LOOKS. This is a cold first message to a purchasing director in Germany. Abbreviations like idR. and vgl. belong in an internal note, not in a first approach, and a wrong article is the kind of thing a German reader registers immediately even if they could not say why. The whole point of the opener is to read as though a person who knows the market wrote it.

WHAT IS NEEDED
  A language correctness pass on every draft before it reaches the review queue, in the language the draft is written in, not only in English.
  A ban on abbreviations in outbound. Write in der Regel, im Vergleich zu, and so on, in full.
  German nouns capitalised, which is mechanical and catchable.
  And the lint number must reflect it. A draft with a grammar error should not read 100.$il$,
$il$FOURTH AND FIFTH SIGHTINGS, AND ONE OF THEM HAS ALREADY GONE OUT. On the Leonard Coen card at topi, P707, 17 Sep. The pending draft reads für ähnliche vermieter, lower case, and Ich teile da gerne auch mal einen Case Study, where Studie is feminine so it is eine Case Study. Worse, the DM ALREADY SENT on 2 September reads Wie du weißt sind abo Modelle kommerziell sehr stark: Abo-Modelle takes a capital and a hyphen, and the clause needs a comma after weißt.

THAT CHANGES THE URGENCY. Every earlier example was sitting in the review queue where Oliver could still catch it. This one went to a Vice President of Strategic Partnerships in Germany with two errors in one sentence. The problem is already in the record of what Pier has said, not only in what it is about to say. Worth a sweep of what has been sent in German, not just what is queued.

THIS IS A DIFFERENT GAP FROM i084 AND THE TWO SHOULD NOT BE MERGED. There, guardrails were displayed and then not checked against the text. Here, nothing is checking the text for correctness in the first place. Both surface as LINT 100 on a draft that should not have scored 100, which is exactly why the score has to say what it actually tested, as i084 argues.

IT IS ALSO CHEAP TO FIX RELATIVE TO THE REST. Capitalisation and a fixed list of banned abbreviations are mechanical checks. Article agreement is not, but a second model pass in the draft language would catch all of it, and it can run once at generation rather than on every keystroke.

WORTH A LOOK AT WHERE THE GERMAN COMES FROM. If the drafts are being generated in English and translated, or generated by a model prompted in English, that would explain both the article slips and the English terms surviving in the text. If so the fix is upstream of any lint rule: prompt and generate in the target language.

AND IT COMPOUNDS WITH i037. If line breaks are already being lost somewhere between the draft and the send, a message that is both badly broken up and grammatically off is a poor first impression twice over.$il$);
insert into public.improvement_comments (team_id, improvement_id, who, at, text)
select i.team_id, i.id, $il$Claude$il$, '2026-09-17T15:20:00.000Z'::timestamptz,
$il$17 Sept, THIS IS NOT A GERMAN PROBLEM, IT IS A DRAFTING PROBLEM. The English draft to Louis Salzman-Le Goff at WeFix contains we can give all your clients ON month of free insurance cover, for ONE month, and which is a great USB to buy on your website, for USP. A wrong word and a wrong acronym in consecutive lines, in English, on a P2 contact in France.

Neither was caught. The lint on that card scored 85 and did flag a terminology rule, Use Partner not client, so it is checking something. It is not checking whether the words are the right words. Title and scope of this item widened accordingly.

USB for USP is the kind of error that reads as careless rather than as a typo, because the reader cannot tell which word was meant. Worth saying because it argues for a spell and sense pass on every draft in whatever language it is written, not a German specific rule.$il$
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i098$il$;

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i099$il$, $il$A contact cannot be moved to a different company from the front end$il$, $il$Lovable UI$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-17T12:50:00.000Z'::timestamptz, 5, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Oliver cannot move a contact to a different company from the front end. When a contact is attached to the wrong company, there is no way to correct it where he is standing.

THE RECORD HE FOUND IT ON IS A GOOD EXAMPLE OF WHY IT MATTERS. Ben Beasley sits under Vodafone Germany. His country is UK, his city is London, and his own background note reads Global Director of Partnerships at Vodafone, group level UK, linked to C307 Vodafone Germany. So a UK group level person is filed under the German operating company.

THAT IS NOT A TIDINESS PROBLEM. The company a contact hangs off decides several things that then run automatically:
  Territory and owner. UK is Jack's, DACH is Oliver's. A wrong company puts a contact in the wrong person's book.
  Monday suppression. If the company is worked in monday, the contact should not appear in a lake worklist at all.
  Scoring and prioritisation. The company carries the devices, the category and the score that decide whether its people are worth a connection request.
  Grouping and duplicate detection, which read the parent company.

WHAT IS NEEDED

1. A Company field on the contact that can be changed, with a type to search picker. The same picker as the new contact dialog in i046, so there is one way to choose a company in the app rather than two.

2. The picker must show every company, including ones worked in monday. i046 found it silently hides them, which is how spusu looked missing. If a company is suppressed, show it and label it suppressed rather than leaving it out.

3. Moving a contact keeps its history. Touches, drafts, notes and next action travel with the person, not with the old company link.

4. Record the move. Who changed it, from what, to what, and when, on the contact timeline. This is the same gap as i076, where notes are saved undated and unattributed.

5. Warn before a move that changes something consequential: a different country or owner, or a move into a company that is worked in monday. Do not block it, say what will follow.

BUILD THE SIMPLE MOVE FIRST. i058 asks for a contact to belong to more than one company, which is the fuller answer. Even with that, one company has to be the primary, and this is the control that sets it. It is also a prerequisite for the group work in i047, because fixing a group is mostly moving people between its members.

AND THE DESTINATION MAY NOT EXIST YET. Oliver's point on Ben Beasley is that he works at Vodafone GROUP level, not at Vodafone Germany. If there is no Vodafone Group record in the lake, a reassignment control on its own does not solve his case: he needs a parent entity to be moved to. So this lands next to i047. The picker must therefore be able to create a company inline, as i046 already asks for the new contact dialog, otherwise the answer to a wrong parent is a second wrong parent.

THE GENERAL RULE UNDERNEATH IT. A person who operates at group level should hang off the group, with the operating companies as its children, not off whichever subsidiary happened to be in the lake first. Getting that right is what makes the group rollup in i047 mean anything, because otherwise a group's contacts are scattered across its subsidiaries by accident of import.$il$,
$il$THE WORKAROUND TODAY IS TO ASK BRAD OR EDIT THE DATABASE, which means a correction that takes five seconds to see takes a day to apply, and most of them simply do not get made. That is how a lake fills with contacts filed under the wrong entity.

IT WILL COME UP OFTEN WITH GROUPS. Vodafone Germany against Vodafone group, mobilezone against Sparhandy, asgoodasnew against Save Group: every one of those is a case where the right company for a person is a judgement, and the first guess is frequently wrong. i047 and i068 are both about getting the group structure right, and neither is much use if the people cannot be moved once the structure is fixed.

TWO OTHER THINGS ON THE SAME CARD, NEITHER RAISED BY OLIVER, BOTH WORTH A GLANCE.
  The next action date reads 19 May 2026, four months in the past, while Outreach Status reads Parked and the cooldown runs until 25 February 2027. Three fields describing the same plan and none of them agree. Nothing surfaces an overdue next action, so it just sits there.
  Connection Status reads Withdrawn, which under the six month re-invite cooldown means this contact cannot be re-approached until February 2027 anyway. Worth confirming the cooldown date is derived from the withdrawal rather than typed, because if it is typed it will drift.$il$);

-- exactness gate: every item in this part must hash to the value computed from the source file
do $verify$
declare bad text;
begin
  select string_agg(e.item_key, ', ' order by e.item_key) into bad
  from (values
    ('i092', '45d410ea655379c69d8f45b1e2c157fa', 0),
    ('i093', 'cf5f70637091f3c702339abdb27ea9dc', 1),
    ('i094', 'bf6420af2726603ee15e3ffa8aae020e', 0),
    ('i096', '11b42a746df516d1245829f6fcebc531', 5),
    ('i097', 'bf5efe460427dcb8fed84c5a40a70022', 0),
    ('i098', 'a650633ea0da42addfeb1c0fc60d0a16', 1),
    ('i099', 'd87e6be502d7b9157ca5926fc016c0b2', 0)
  ) as e(item_key, src_md5, n_comments)
  left join public.improvements i
    on i.item_key = e.item_key and i.team_id = (select id from public.teams limit 1)
  where i.id is null
     or e.src_md5 is distinct from md5(concat_ws(chr(31),
      i.title, i.category, i.owner, i.priority, i.status, coalesce(i.raised_by,''), i.detail, i.notes,
      coalesce(i.done_by,''), array_to_string(i.blocks,','), array_to_string(i.blocked_by,','),
      coalesce(i.build_wave::text,''), i.pinned::text, i.hidden::text,
      to_char(i.created_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), coalesce(to_char(i.done_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),''), i.seen_by::text,
      coalesce((select string_agg(concat_ws(chr(31), c.who, to_char(c.at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), c.text), chr(30) order by c.at)
                from public.improvement_comments c where c.improvement_id = i.id), '')));
  if bad is not null then
    raise exception 'F18.5 import: rows differ from the source export: %', bad;
  end if;
end
$verify$;
