-- 118b_f18_5_improvement_log_import_p07
-- F18.5(b) improvement log import, part 7 of 12: i071..i081 (11 items, 1 comments).
-- GENERATED by scripts/gen_improvement_log_import.py from 260920_lovable_improvement_log_export.json - do not edit by hand.
-- Text is dollar-quoted and must stay byte-for-byte; the DO block at the end rolls the part back if not.

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i071$il$, $il$Score the company BEFORE sourcing its leads, then spend the day's 20 from the top$il$, $il$Research agent$il$, $il$Both$il$, $il$blocker$il$, $il$open$il$, $il$Oliver$il$, '2026-09-15T13:38:22.000Z'::timestamptz, 0, '{}'::text[], '{}'::text[], null, null, false, false, $il${"Brad": "2026-09-20T14:40:43.685Z"}$il$::jsonb,
$il$LinkedIn cut Oliver off at 20 connection requests today, with You're out of invitations for now. Whether 20 is permanent is i072. Either way it is far below the 30 a day the counter is set to and nowhere near the 80 Oliver assumed, and it changes what the bottleneck is.

Until now the scarce thing was leads. From today the scarce thing is the 20. A hundred requests a week, and at roughly one in three accepting, about 33 conversations a week. A request spent on a company that would have scored badly is a conversation that does not happen, and it cannot be bought back.

AGREED WITH BRAD, 15 SEPTEMBER: the order inverts. A company is RESEARCHED AND SCORED FIRST, and only then are leads sourced for it. Sourcing a lead at an unscored company is how a scarce request ends up spent on a low value target.

WHAT IS NEEDED:
1. Sourcing gated on score. No lead sourcing for a company that has not been researched and scored. Not a warning, a gate.
2. A Companies view sorted by score, highest first, so it is obvious where the next leads and the next 20 requests should go.
3. The counter corrected to 20 a day and enforced rather than advisory, with today's remaining count visible.
4. Sourcing and sending both driven from that ranked list, not from whichever board is open.

Oliver's words: finding the leads is fine, but having the company priority and the research done first, which is what allows us to score them, is much more important.$il$,
$il$THIS RULE ALREADY EXISTS AND IS NOT BEING FOLLOWED, which is the more useful framing for Brad. The engine's operating model already says, in strict terms: add company, light triage, deep research with the IPID test and the checkout walk, dedup and freeze check, and ONLY THEN source leads. Never hand over an unresearched company. So this is not new logic to invent, it is an existing rule that Lovable does not enforce. That matters because a rule living only in prose gets skipped, and the fix is to make the system refuse rather than to remember harder.

THE CURRENT QUEUE IS THE EVIDENCE. The Lovable Master List holds 130 leads added on 9 September, all showing no activity. Brad flagged the same thing on the call: there are contacts sitting against companies that have not been researched, and drafts cannot be built for them. Those 130 were sourced ahead of the research, which is exactly the order this item reverses.

SO THERE IS AN ACTION BEFORE ANY BUILD: score the companies behind those 130 before spending another day's requests on them. Otherwise the first 20 tomorrow go out in the old order regardless of what gets built later.

IT PUTS A DAILY PRICE ON i001. The score needs research, research needs the agent, the agent needs the Supabase connector Oliver still cannot log into. The login failure is no longer just delaying a feature, it is the reason 20 requests a day go out against an unranked list. That is the argument for getting the screenshare done rather than waiting.

ON AUTOMATICALLY SENDING THE REQUESTS, the one part to be careful with. Queueing them in score order, yes. Firing them from the tool is what i019 parks as an account risk, and Oliver has just BEEN throttled, so the account is already under scrutiny. Losing Sales Navigator would cost more than every hour of clicking this saves. Suggested split: the system decides who and in what order and puts the profile one click away, a human sends. Revisit once out of throttle.

A RANKED LIST IS ONLY AS GOOD AS ITS DENOMINATOR. Unassessed is removed from the scoring denominator, never scored zero, so a thinly researched company can score high on three components of four and outrank a fully assessed one. Show confidence next to the score or the 20 a day get spent on whichever companies are least researched. Same trap as i039.

WHAT ELSE THE RANKED VIEW SHOULD CARRY: how many decision makers are sourced, their CONNECTION DEGREE, whether a request is already pending there, the country, and whether the company is frozen. Degree matters more than it looks: second degree accepts materially better than third, the allowance keys off acceptance, so sorting by score AND degree protects the budget. A good share of the current 130 are third degree.

THE FLOOR STILL APPLIES LOOSELY. Oliver confirmed on 15 September that roughly 1,500 devices a month is fine for Germany and the funnel should not be narrowed further, because scoring handles prioritisation. That holds. The 20 a day does the rationing now, not the floor.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i072$il$, $il$The 20 a day is a throttle, not a ceiling. Work out what caused it$il$, $il$Outreach & drafting$il$, $il$Oliver$il$, $il$question$il$, $il$open$il$, $il$Claude$il$, '2026-09-15T13:39:22.000Z'::timestamptz, null, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$LinkedIn's own wording settles most of this. The dialog reads: You're out of invitations FOR NOW. We encourage sending fewer, more thoughtful invitations to people you know to keep LinkedIn a trusted community.

That is behavioural throttling language, not a published cap. For now means it can come back, and the sentence about people you know is LinkedIn saying the acceptance rate is the problem. So before the whole engine is designed around 20 a day, work out what pushed it down.

The likely cause is the pile of unaccepted invitations. In August the account carried 255 pending. A large pending stack with a low acceptance rate is the textbook trigger for exactly this.

If that is it, the fix is not to throttle harder. Withdraw the stale invitations, which is already a defined monthly process, and watch the allowance over the next fortnight.

The ranking work in i071 goes ahead regardless. This only decides how tight the ration has to be, and whether it is permanent.$il$,
$il$HOW TO ANSWER IT, cheaply: count the invitations still pending in Sales Navigator and how many are older than 28 days. The monthly cleanup rule already withdraws anything unaccepted at 28 days in one batch, and a withdrawal resets the three week re-invite clock, so there is no cost beyond the clicking.

WATCH IT AFTER, not immediately. LinkedIn does not restore the allowance instantly. Note the daily cap for two weeks after a cleanup. If it recovers, we know the lever and keeping the pending pile small becomes routine rather than monthly.

THE 130 IN THE LOVABLE MASTER LIST ARE PART OF THE PICTURE. All added 9 September, all showing no activity. That is a queue, and if it goes out as 130 requests to people who mostly do not accept, the throttle gets worse rather than better. Which is the i071 argument: send fewer, better aimed.

DEGREE IS A FREE PREDICTOR AND IT IS ALREADY IN THE DATA. On that same screen Christian Haid, Thomas Fugmann and Sebastian Stangenberg are 3rd degree; Alejandro del Valle and Marc Mumm are 2nd. Second degree means a shared connection, which accepts materially better than a cold third degree. Since the allowance keys off acceptance, sorting the queue by degree as well as by score costs nothing and protects the budget. Worth adding to the ranked view in i071.

IT ALSO MAKES THE BLANK CONNECTION REQUEST A THROUGHPUT DECISION, not only a voice one. Anything that lifts acceptance lifts the allowance, so the existing blank-by-default rule is now worth measuring rather than assuming.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i073$il$, $il$Cooldown says In cooldown but never says until when$il$, $il$Lovable UI$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-16T08:28:33.000Z'::timestamptz, 5, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$On Morten Jensen the Cooldown field reads In cooldown. That is a yes or no, and the useful part is the date. Show when it ends: In cooldown until 2 March 2027, with the months remaining next to it.

The date is not something new to calculate. A withdrawn connection request sets Cooldown Until at six months, and that value already exists in the lake as a date. Lovable is displaying the boolean and dropping the date it came from.

Make it sortable and filterable too, so it is possible to ask what comes free next month rather than finding out by accident.$il$,
$il$THE HEADER TILE IS ALREADY THE RIGHT IDEA. Ready to re-engage, cooldown expired, currently 0. That is the queue this feeds, and it only works if every contact carries a real date. A boolean cannot produce that count correctly, it can only produce it by re-deriving the date somewhere else, which is how two places end up disagreeing.

SHOW THE REASON WITH THE DATE. Six months from a withdrawn request is a different thing from a cooldown set after a not right now reply. One is a rule, the other is something a person or a prospect said. When Oliver decides whether to override, the reason is what he needs, not just the date.

OVERRIDE IS OLIVER ONLY, per the standing rule. A cooldown that anything can clear is not a cooldown. Showing the date makes overriding easier, so the control needs to stay deliberate.

SAME TREATMENT ANYWHERE A STATE HIDES A DATE. Next action, research stage outdated in i029, follow ups in i063. A state without its date tells you that something is true but not whether it is today's problem, which is the only question being asked.$il$);
insert into public.improvement_comments (team_id, improvement_id, who, at, text)
select i.team_id, i.id, $il$Claude$il$, '2026-09-17T13:30:00.000Z'::timestamptz,
$il$17 Sept, a worse version of the same fault. On Marcel de Groot the Cooldown field reads NOT IN COOLDOWN, while the record's own Next Action reads DECIDED: CR WITHDRAWN 2026-08-25 by Oliver, no re-CR before 2027-02-25, and Next Action Date is set to 25 February 2027. So a six month re-invite block is in force and the field that exists to say so reports the opposite.

That is not a missing date, it is a false negative on a guard, and it is the direction that costs something: a contact who looks free to approach and is not. Same pattern on Ben Beasley, see i099, where Cooldown reads Not in cooldown next to a cooldown running to 25 February 2027.

Worth establishing whether the Cooldown field is derived from the withdrawal date at all, or whether it is a separate value that has to be set by hand. If the latter, it will be wrong on every contact withdrawn in the August cleanup, which was roughly 138 records.$il$
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i073$il$;

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i074$il$, $il$Replies needing an answer cannot be cleared, so the queue is becoming noise$il$, $il$Lovable UI$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-16T08:29:33.000Z'::timestamptz, 3, '{}'::text[], array[$il$i048$il$]::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Two entries sit in Replies needing an answer, one waiting 54 days and one 16 days, and there is no way to clear either. Neither actually needs a reply: TELEFUNKEN Licenses and Dataxis are not potential clients.

Three routes out are needed:
1. Ignore, with a reason. Not a prospect, not relevant, handled elsewhere, no reply needed.
2. Automatically cleared when a reply is sent, which is the normal path.
3. Manually marked as replied, for when the reply went out somewhere else.

A queue that cannot be emptied stops being read. Waiting 54 days is only useful as a number if clearing it is possible; otherwise it is a reproach, and the whole panel gets ignored along with the entries that do matter.$il$,
$il$THE IGNORE REASON SHOULD FIX THE ROOT, NOT THE SYMPTOM, and this is the part worth building properly. Both of these are marked Positive interest and both are companies that should never have been in the funnel. TELEFUNKEN Licenses is a brand licensor and Dataxis is a market research and media business. Neither sells devices to consumers, which is the B2C knockout rule, already written down after the Boettcher case.
So when Oliver picks not a prospect, the action should offer to mark the COMPANY out of scope with that reason, not just dismiss the reply. Otherwise the same company produces another contact, another draft and another entry in this list next month, and he clears it again.

IT IS ALSO A CLASSIFICATION SIGNAL. Both are labelled Positive interest, and both are wrong in the sense that matters: interested is not the same as a prospect. Every ignore with a reason is a labelled example of the classifier being wrong, which is the only training data this thing will ever get for free. Store it, do not just delete the row.

ONE OF THESE IS NOT REALLY IGNORABLE. Ishnav Thakooree wrote that he would love to have a testimonial. That deserves a human answer even though he is not a buyer, which is why the options need replied outside the system as well as ignore. A binary of reply or dismiss would push Oliver into dismissing something he should answer.

BOTH ARE ALSO BLOCKED FOR A SECOND REASON: company not deep researched, per i055. So they are stuck twice, once behind research they will never justify and once behind a queue with no exit. Clearing them is the fastest proof that i055 and this item are both needed.

AUTOMATIC CLEARING DEPENDS ON KNOWING A REPLY WENT OUT, which is i048 and i052. If sends are recorded at the moment they happen, route 2 is free. If they are not, this list will keep showing conversations Oliver answered days ago.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i075$il$, $il$Who the company sells to, as a field with three values, not a B2B checkbox$il$, $il$Data & schema$il$, $il$Both$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-16T08:38:39.000Z'::timestamptz, 1, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$There is nowhere to record that a company is pure B2B, so B2B only businesses keep entering the funnel and are only caught when somebody notices by hand.

WHERE IT GOES: on the company, in the Product Offerings block, next to Refurbished and SIM free. Those are already the yes or no facts about what the business actually sells, and this is the same kind of fact.

DO NOT MAKE IT A B2B CHECKBOX. There are three states and the middle one is where the mistakes happen:
  Sells to consumers. In scope.
  B2B led, consumer share unverified. Do not source yet, verify the consumer side first.
  B2B only. Out of scope.
A tick box collapses the middle case into one of the outer two, and the middle case is exactly what the rule was written for after Boettcher.

B2B only should then act, not just label: it sets the company Out of Scope with that as the reason, and the sourcing gate refuses it.$il$,
$il$THE RULE ALREADY EXISTS, same pattern as i071. B2C or B2B is a knockout criterion, written into the research prompt on 3 September after Boettcher: B2B only is out of scope, B2B led means verify the consumer share before anything else. So this is not a new policy, it is the field that lets the policy be enforced instead of remembered.

IT IS A RESEARCH OUTPUT. The agent should set it during deep research, in the same pass as the IPID test and the checkout walk, because walking the checkout is how you find out whether a consumer can actually buy a device. Which means it arrives free once the research agent runs, and does not need to be typed.

SHOW IT WHERE A MISTAKE WOULD BE MADE, not only on the company record. A chip on the outreach card and in the lead list when the value is B2B led, because that is the case where a draft would otherwise get written and sent to somebody who cannot buy.

IT IS ALREADY BEING RECORDED, IN THE WRONG PLACE, which is the clearest evidence the field is missing. AB Gsmshop.at GmbH in Austria carries a company note whose entire content is the word B2B, and the company is marked OoS. So somebody has already made this judgement and had nowhere to put it except free prose, where nothing can filter it, no guard can read it, and it is undated on top, see i076. Whatever the sweep finds, expect more of these hidden in notes.

MAKE IT FILTERABLE AND RUN IT ONCE. The immediate value is not the future, it is sweeping what is already in there. Yesterday's two Replies needing an answer were TELEFUNKEN Licenses, a brand licensor, and Dataxis, a market research and media business. Neither sells a device to a consumer, both were sourced, both got contacted, both produced a reply that then sat in a queue for weeks. A filter would have surfaced them before any of that.

PAIRS WITH i074. When Oliver clears a reply with the reason not a prospect, this is the field that should be set, so one click closes the loop rather than clearing the symptom.

ONE HONEST EDGE CASE. Some B2B businesses are still worth a conversation, just not through Pier Protect: a fleet or rental operator sells to businesses and still has devices worth covering, which is the Grover case. So Out of Scope should carry the reason rather than being a dead end, and B2B only should not mean delete.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i076$il$, $il$Notes are saved undated and unattributed$il$, $il$Data & schema$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-16T08:39:41.000Z'::timestamptz, 1, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$On the company Notes tab every entry reads Undated. No date, no author. On AB Gsmshop.at GmbH the whole note is the word B2B, and there is no way to tell whether that was learned in May or last week, or by whom.

Every note needs a date and a name, written when it is saved, and it should be an appended entry rather than one editable block that two people overwrite.

ONE WARNING ON THE BACKFILL, and it matters more than the feature. Do NOT stamp the existing undated notes with today's date. That would make every old observation look like it was made this week, which is the exact opposite of what i029 is trying to achieve. Mark them as imported, original date unknown. An honest gap is usable; a wrong date is not.$il$,
$il$WHY A NOTE WITHOUT A DATE IS WORSE THAN NO NOTE. It still gets believed. Somebody reads B2B, accepts it, and acts on it, without being able to ask whether the business has changed since. Research decays: ElectronicShop24 has switched carrier twice, DiTech turned out to hold a Wertgarantie policy the research had missed. The date is what lets a reader decide whether to trust the line, and it is the input i029 needs to call something outdated.

APPEND, DO NOT EDIT. One editable block means the second person to type loses the first person's text, and neither of them knows. Separate entries, each with its author and timestamp, is also what makes the note useful later: you can see the sequence of what was learned rather than a flattened paragraph.

WHERE THE UNDATED ONES CAME FROM is worth a minute. They arrived through the migration from the lake, where notes were often free prose in a single cell with the date written inside the text if at all. So the fix has two halves: stamp new notes properly, and mark the migrated ones honestly. The second half is the one that is easy to get wrong.

SAME PRINCIPLE AS i073. A state or a fact shown without its date tells you something is true but not whether it is still true, and that is usually the question being asked.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i077$il$, $il$Split annual devices sold into phones, laptops and tablets, and accessories$il$, $il$Data & schema$il$, $il$Both$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-16T08:44:38.000Z'::timestamptz, 1, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Annual Devices Sold is one box. It needs to be three, the same three monday already uses:
  Phones a year
  Laptops and tablets a year
  Accessories a year

It is not presentation. The three carry different attachment rates in the sizing heuristic, roughly 8 percent on phones and 6 percent on laptops and tablets, and accessories are excluded from the calculation entirely. One blended number cannot produce a correct figure, and it will be wrong in both directions depending on the mix.

Keep accessories as a field even though they score zero. Capturing them stops somebody counting accessory volume as device volume, and the mix itself says something about the business.

Each of the three needs its own Evidence and Stated by, or one shared evidence note that says which of the three it actually covers. Otherwise a stated phone figure and an estimated laptop figure end up looking equally solid.$il$,
$il$WHY IT BLOCKS THE SCORE RATHER THAN JUST IMPROVING IT. The ranking in i071 decides where the 20 connection requests a day go, and the ranking is driven by the opportunity size. A refurbisher selling 50,000 accessories and 2,000 phones is a small opportunity; a blended field makes it look like a large one. Until the split exists, the ranked list will systematically favour whoever sells the most low value units.

THE EVIDENCE FIELDS ALREADY ON THAT SCREEN ARE THE GOOD BIT, and they should survive the change. Evidence in the partner's own words, plus Stated by, is exactly the discipline the sizing standard asks for: a stated figure and an estimate are not the same input and must never look the same. Three numbers with one undifferentiated evidence box would quietly lose that.

USE THE INTERNAL HEURISTIC FOR RANKING, NOT PARTNER FACING NUMBERS. The phones-at-8 and laptops-at-6 heuristic is for internal ranking only. Anything shown to a partner comes from the canonical partner calculator, which is a different model and does not always agree. Worth being explicit in the build about which of the two any given figure came from, or the wrong one ends up in an email.

THE SAME ARGUMENT APPLIES TO ONLINE VERSUS IN STORE, which Oliver raised earlier. Attachment online runs far below attachment at a counter, so a company with physical shops is worth materially more than the same volumes sold online only. That is a second split, on the same field, for the same reason. Worth deciding whether to do both at once rather than migrating this field twice.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i078$il$, $il$Say what belongs in each field, and stop ambiguous fields collecting the wrong thing$il$, $il$Lovable UI$il$, $il$Both$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-16T08:47:43.000Z'::timestamptz, 5, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Oliver's ask: a small info icon next to any field whose meaning is not obvious, explaining what goes in it and when, readable on hover.

It is worth more than convenience, because an ambiguous field does not stay empty, it fills up with the wrong thing. Live example on the same screen: Evidence, partner's own words, currently contains a pasted volume breakdown that reads like a model output, and Stated by reads Google - Gemini. Nobody stated that. It is an estimate, filed in the field reserved for what the partner actually said.

That distinction is not cosmetic. The sizing standard ranks a figure by how it was obtained, stated by the partner at the top, then derived from revenue, then modelled. A modelled number sitting under partner's own words makes a weak figure look like the strongest kind.

So two things. Help text where a field is ambiguous. And where the ambiguity is really a missing choice, offer the choice: Stated by should carry a source TYPE, partner stated, our estimate, third party source, public filing, alongside the name.$il$,
$il$FIELDS THAT MOST NEED THE EXPLANATION, from what has already gone wrong:
  Evidence and Stated by. See above. The strongest case.
  Country versus Countries selling in. One drives the legality guard, the other does not, and confusing them makes a German contact look emailable. That is i038 and i054.
  Annual devices, once split in i077. Which number includes what, and whether refurbished and new are both counted.
  Research stage versus Outreach status versus Priority. Three states that sound like each other and answer different questions, which is the confusion i003 exists to clear.
  Parent group, once i047 lands. Whether it means ownership or just a shared brand.

WRITE THE HELP FROM THE FAILURE, not from the field name. Useful help says what to do in the awkward case: if the partner has not given you a number, put your estimate here and set the source to our estimate. Help that restates the label, annual devices sold means the devices sold annually, is worse than none because it trains people to stop reading the icons.

THE TOOLTIP CANNOT BE THE ONLY ROUTE. Hover does not exist on a tablet and is not reachable by keyboard, the same argument as i028. Make it a button that toggles the text open, not a pure hover tooltip.

A FIELD THAT NEEDS A PARAGRAPH OF HELP IS USUALLY TWO FIELDS. If the explanation is long, that is the signal to split it or make it a picker rather than to write better help. Worth applying that test while doing the i049 review, since both passes are looking at the same fields.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i079$il$, $il$Record whether research was done by a person or by the agent$il$, $il$Research agent$il$, $il$Both$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-16T09:52:36.000Z'::timestamptz, 1, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Research Stage says Light triage or Deep research done. It does not say who did it. A company the agent read off a website and a company Oliver walked the checkout of are not the same thing, and right now they look identical.

Record the source on the research: agent, person, or both, with the name where it was a person.

PER FACT, NOT JUST PER COMPANY. A company can be agent researched overall and still have one human verified fact, typically the insurance provider, because somebody actually walked the checkout. A single company level Researched by would flatten exactly the distinction that matters, since the checkout walk is the part the agent cannot do reliably.

This is the third version of the same need this week. i076 wants a date and an author on notes, i078 wants a source type on a stated figure, and this wants agent or human on a research finding. They are one thing: every fact carries where it came from and when. Build one stamp and reuse it, rather than three fields that do not quite line up.$il$,
$il$THE REAL PAYOFF IS THE AUTONOMY DIAL, and it is worth stating because it is not obvious. The only way to answer how far the research agent can be trusted unsupervised is to measure how often its findings turn out wrong. That requires knowing which findings were its. Without the attribution the question can never be answered, and the agent stays permanently on a leash because nobody can prove it should come off. The trust ledger already exists for exactly this purpose on the verification side; this is the same idea applied to research.

IT IS ALREADY MEASURABLE TODAY, IN THE WRONG DIRECTION. On 4 September Oliver walked eight checkouts and two overturned a confident desk verdict, both optimistically: DiTech carried a Wertgarantie policy the research had missed, and BA-Computer could not be shown to sell a device at all. That is two corrections in eight, and it is only a known number because he happened to do them in one batch. With attribution it becomes a running figure instead of an anecdote.

IT CHANGES WHAT RE-RESEARCH DOES, which matters for i029. An agent produced verdict going stale can simply be re-run. A human verified one, especially a checkout walk, is expensive to reproduce and should be preserved and flagged rather than silently overwritten by a fresh agent pass. Without knowing which is which, re-research will quietly destroy the most reliable data we have.

AND IT FEEDS THE SCORE'S CONFIDENCE. i071 needs confidence shown next to the score so thin research does not outrank thorough. Agent versus human is one of the inputs to that confidence, alongside how many components were assessed and how old the research is.

SUGGESTED SHAPE, small: on every research derived field, a source of agent or person, the name if a person, and the date. Displayed as a quiet marker rather than a column, and filterable. Then Research Stage stops carrying two meanings and just says how far the research got.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i080$il$, $il$A two line summary at the top of a company, so you know what it is in one glance$il$, $il$Lovable UI$il$, $il$Both$il$, $il$nice$il$, $il$open$il$, $il$Oliver$il$, '2026-09-16T09:53:49.000Z'::timestamptz, 5, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Opening a company record currently means reading fields to work out what the business actually is. A short generated summary at the top, two or three sentences, would orient you before you read anything else.

SHAPE IT TO THE DECISION, NOT TO AN ABOUT US PAGE. The question being answered when Oliver opens a record is always the same four: what do they sell, to whom, at roughly what scale, and do they already have insurance. A summary that answers those is useful. One that says leading provider of innovative solutions is worse than blank.

GENERATE IT FROM THE RECORD, NOT FROM THE WEB. It has to be written from the fields already held, so it can never contradict the structured data sitting directly underneath it. A blurb calling them a consumer retailer while the B2B field says B2B only is how people stop trusting the whole screen.

There is already a good version of this in the app: the AI state of play panel on the contact view. This is the company equivalent.$il$,
$il$THE REAL RISK IS FLUENCY OVER THIN RESEARCH. A well written two line summary reads as authoritative whether or not anything is behind it. If a company is Untouched, the summary must SAY that, plainly: nothing researched yet, name and website only. It must never generate something plausible from the company name and a homepage, because that is indistinguishable from real research at a glance and will be acted on as though it were.
Same discipline as the size field, which already does this properly: No size recorded, UNSIZED, not small. That is the tone to copy.

IT IS A READING AID, NEVER A SOURCE. Nobody should cite the summary as evidence and nothing downstream should read it. If it disagrees with the fields, the fields win. Without that rule it becomes a laundering route for unsourced claims, which is exactly what happened when a model generated volume estimate ended up filed under Evidence, partner's own words. See i078.

DATE IT AND REGENERATE IT, per i079. A summary written in May about a company that has since changed carrier is worse than none. Show when it was generated, and regenerate whenever the research behind it is refreshed, which is the i029 trigger.

KEEP IT SHORT ENOUGH TO BE READ. Two or three sentences. The moment it becomes a paragraph it gets skipped, and a skipped summary is just a slower page.

CHEAP ONCE THE RESEARCH AGENT RUNS, which is why it is worth queueing behind that rather than building a separate generation step now. The inputs are the same research pass.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i081$il$, $il$Show the job title on the company Contacts tab$il$, $il$Lovable UI$il$, $il$Brad$il$, $il$nice$il$, $il$open$il$, $il$Oliver$il$, '2026-09-16T09:55:41.000Z'::timestamptz, 5, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$The Contacts tab on a company shows Name, Function, Seniority and Outreach Status. Add the job title. It is the thing that tells you who these people actually are, and it is the column you look for when deciding which of six contacts to work.

On Duttenhofer that tab lists six people and the only one you can tell anything about is Marcel Tully, because he is the only one with Function and Seniority filled in.$il$,
$il$THE MORE USEFUL FINDING ON THAT SCREEN: five of the six contacts have BLANK Function and Seniority. So the tab is currently showing two derived fields that are mostly empty, while the raw job title, which is far more likely to be populated, is not shown at all. Adding the title does not just improve the table, it is the only column that would carry information for five of those six rows.

AND BLANK SENIORITY IS NOT COSMETIC. The sourcing floor reads Seniority: it exists to stop junior contacts entering the pipeline. A blank value means the gate has nothing to read, so it either passes everyone or blocks everyone, and neither is the intended behaviour. Worth counting how many contacts across the whole base have no Seniority before deciding whether that is a display problem or a derivation that is not running.

IF IT IS A DERIVATION PROBLEM, the title is also the fix. Function and Seniority can both be derived from the job title, which is how they were populated in the lake. Six contacts with titles and no seniority suggests the derivation did not run on import rather than that the data is missing.

One caution from i020, already parked: title matching alone picks the wrong people at scale. So derive Seniority from the title by all means, but keep it correctable by hand, and treat a derived seniority as weaker evidence than one a person confirmed. Same provenance argument as i079.$il$);

-- exactness gate: every item in this part must hash to the value computed from the source file
do $verify$
declare bad text;
begin
  select string_agg(e.item_key, ', ' order by e.item_key) into bad
  from (values
    ('i071', 'cb606b30797e9b22f18a70248bb6f6c3', 0),
    ('i072', 'cbf4b0542b4a2f7c6af2c52919176c37', 0),
    ('i073', '27804e2246ee4c9be68b2b53a88015b6', 1),
    ('i074', 'b0d204a6f4409d63eb219e7dbb77a447', 0),
    ('i075', 'fd5cdeb6725c3ec41a1a4e5fadb539d7', 0),
    ('i076', 'bda206b9434b87c103515c3400a331b7', 0),
    ('i077', 'b97def02c076dabe0f0ba61e7d86c999', 0),
    ('i078', 'ad76b1187a52bac7ef83314bcf72e95f', 0),
    ('i079', 'a0c7d469ec9d48eae44bed124383bced', 0),
    ('i080', 'd6cfef1ad48f55529bbdd2a985818fcd', 0),
    ('i081', '8e2ebb9c4dae626e88e26c8a86ca0d31', 0)
  ) as e(item_key, src_md5, n_comments)
  left join public.improvements i
    on i.item_key = e.item_key and i.team_id = (select id from public.teams limit 1)
  where i.id is null
     or e.src_md5 is distinct from md5(concat_ws(chr(31),
      i.title, i.category, i.owner, i.priority, i.status, coalesce(i.raised_by,''), i.detail, i.notes,
      coalesce(i.done_by,''), array_to_string(i.blocks,','), array_to_string(i.blocked_by,','),
      coalesce(i.build_wave::text,''), i.pinned::text, i.hidden::text,
      to_char(i.created_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), coalesce(to_char(i.done_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),''), i.seen_by::text,
      coalesce((select string_agg(concat_ws(chr(31), c.who, to_char(c.at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), c.text), chr(30) order by c.at)
                from public.improvement_comments c where c.improvement_id = i.id), '')));
  if bad is not null then
    raise exception 'F18.5 import: rows differ from the source export: %', bad;
  end if;
end
$verify$;
