-- 118b_f18_5_improvement_log_import_p02
-- F18.5(b) improvement log import, part 2 of 12: i026..i035 (10 items, 10 comments).
-- GENERATED by scripts/gen_improvement_log_import.py from 260920_lovable_improvement_log_export.json - do not edit by hand.
-- Text is dollar-quoted and must stay byte-for-byte; the DO block at the end rolls the part back if not.

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i026$il$, $il$Claude writes the subject line, and chasers thread instead of starting a new email$il$, $il$Outreach & drafting$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-09T08:40:00.000Z'::timestamptz, 4, '{}'::text[], array[$il$i007$il$]::text[], null, null, false, false, $il${"Brad": "2026-09-15T13:07:24.136Z"}$il$::jsonb,
$il$The Subject field sits empty next to a finished body. Claude must draft the subject alongside the body, in the same card, editable and regenerable the same way.

WHERE A SUBJECT IS NEEDED, settled by Oliver on 16 September:
  Every InMail, new and chaser alike. An InMail always carries a subject, so every one needs a written subject, not just the first.
  The FIRST email only.
  Email chasers do NOT get a new subject. They continue the existing one, the way a reply does.
  DMs need no subject field at all and it should not be shown.

EMAIL REPLIES GO TO EVERYONE ON THE THREAD by default, not just the sender.

One correction worth building around rather than discovering later: writing RE or AW in front of the subject does not make an email thread. Threading is done by headers. Details below.

Note this is not only wiring. There is no subject line rule anywhere in the EA bundle, so the rule has to be written. A house pattern taken from Oliver's real sent mail is in the background.$il$,
$il$RE AND AW ARE COSMETIC. A mail client threads on the In-Reply-To and References headers, not on the subject text. If a chaser goes out as a fresh message with RE prepended, it will NOT sit in the thread in the recipient's client, it will be a separate email that merely looks like a reply, which is worse than either doing it properly or not pretending. So: send the chaser as a real reply carrying those headers, and let the subject follow.

DO NOT STACK PREFIXES. German Outlook writes AW, English writes RE, and a thread that has crossed both produces AW: RE: AW: if each side adds its own. Rule: carry the existing subject through unchanged, and if a prefix has to be added, add exactly one, matching the language already used in the thread. Never append a second.

REPLY ALL, WITH ONE CAUTION FROM OLIVER'S OWN THREAD. Default to everyone on the thread, yes. But it must not resurrect people who were deliberately dropped: on the refurbed thread Oliver moved Matteo Ferraris to BCC to save his inbox after the introduction, and added Mark to CC. A blind reply all against the original recipient list would put Matteo back in. So reply all means everyone on the LAST message, not everyone who has ever been on the thread, and the recipient list should be visible and editable before sending.

THE HOUSE PATTERN, observed across Oliver's recent sends:
  Pier Protect fuer Revendo - Erste Unterlagen und Preisstaffelung
  Pier x notebooksbilliger - Zusammenfassung und naechste Schritte
  Very x Pier, introduction via Mark Harrison-North
  Retech: where we stand and next steps
The shape is: name the two parties, then a dash, then plainly what is inside. Either Pier x Partner or Product fuer Partner. No hooks, no curiosity gaps, no questions. It tells the reader what the email contains before they open it.

RULES THAT FALL OUT OF THAT:
1. Name the partner. A subject with no company name in it is wrong.
2. Say what is inside, not why they should care. Erste Unterlagen und Preisstaffelung beats A quick idea for Revendo.
3. Where there is a route in, name it. Introduction via Mark Harrison-North does more work than any hook.
4. Match the language of the body. A German body takes a German subject.
5. On a reply, keep their subject. Never rewrite a live thread's subject.
6. Roughly 40 to 70 characters so it survives a phone inbox.
7. No exclamation marks, no em dashes, sentence case. Same rules as the body.

INMAIL SUBJECTS ARE A DIFFERENT PROBLEM FROM EMAIL SUBJECTS and the house pattern above does not transfer cleanly. An InMail subject is shown in a LinkedIn notification next to the sender's name and photo, not in a crowded inbox, and Pier x Partner reads like a mailshot there. Worth writing the InMail rule separately rather than reusing the email one, and worth testing before it is fixed in the prompt.

WORTH CHECKING BEFORE BUILDING: the email pattern is right for warm and mid thread mail, which is most of what Oliver sends. Nobody has tested it on genuine cold first touch, where a named parties subject may read as a mailshot. Ask Mark, or A/B it, rather than assuming it transfers.$il$);
insert into public.improvement_comments (team_id, improvement_id, who, at, text)
select i.team_id, i.id, $il$Oliver$il$, '2026-09-09T08:41:00.000Z'::timestamptz,
$il$Spotted on a DE InMail draft to Antonius Fromme: full body, guardrails, lint 100, and an empty Subject field.$il$
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i026$il$;
insert into public.improvement_comments (team_id, improvement_id, who, at, text)
select i.team_id, i.id, $il$Oliver$il$, '2026-09-09T10:05:00.000Z'::timestamptz,
$il$Refinement: if it is a DM we do not need the subject line at all, that is only for InMail. For future email campaigns we need it on the first email, and all chaser emails after that should reuse the previous subject the way Outlook does a follow up. Needs sorting once we look at email functionality.$il$
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i026$il$;
insert into public.improvement_comments (team_id, improvement_id, who, at, text)
select i.team_id, i.id, $il$Claude$il$, '2026-09-09T10:06:00.000Z'::timestamptz,
$il$Adding Oliver's refinement here rather than as its own nice-to-have item, because the rule has to ship WITH the feature. If it were separate, this item could get built as a must and the refinement skipped as a nice to have, and the result is a subject box on DMs.

WHICH MESSAGE TYPES CARRY A SUBJECT:
  Connection request note  no subject, and blank by default anyway
  DM after CR accepted     NO SUBJECT. Hide the field entirely, do not show it empty
  DM chaser                no subject
  Sales Nav InMail         SUBJECT REQUIRED. Confirm LinkedIn's character cap rather than assuming one
  Cold email, first touch  subject required, new subject
  Email chaser             reuse the thread subject, see below

ON THE EMAIL CHASER, one correction worth having before it gets built. Oliver is right that it should behave like an Outlook follow up, and the prefix is 'Re:'. But the prefix is not what makes it a follow up. Threading is done by the In-Reply-To and References mail headers, not by the subject text. An email that merely copies the old subject and prepends 'Re:' arrives as a NEW conversation in the recipient's client, sitting apart from the original.

So the requirement is: send the chaser as a genuine reply within the existing thread, carrying the original message id. The 'Re:' then comes along for free. Two details that follow: never stack prefixes, one 'Re:' only and never 'Re: Re:', and note that German Outlook renders it 'AW:'. That is only cosmetic since threading is header based, but it is worth knowing when reading a German thread back and wondering why the prefix changed.$il$
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i026$il$;

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i027$il$, $il$Countries Selling In should be a multi-select, not free text$il$, $il$Lovable UI$il$, $il$Brad$il$, $il$nice$il$, $il$open$il$, $il$Oliver$il$, '2026-09-09T08:55:00.000Z'::timestamptz, 5, '{}'::text[], array[$il$i049$il$]::text[], null, null, false, false, $il${"Oliver": "2026-09-15T13:06:39.809Z"}$il$::jsonb,
$il$Company level. Countries Selling In is a plain text field and needs a picker with multiple selection, restricted to the canonical country list the scoring model already uses. Keep it separate from the single Country field, which is what the legality guard reads. Wiring the multi-select into that guard would make a German company emailable because it also sells into France.$il$,
$il$Oliver marked this nice to have and as UI work it is. But the field is currently unusable as DATA, and two things downstream want to read it:

1. TERRITORY SCORING. Territory is 15 of the 100 points and reads a country name. Free text means a typo, an abbreviation or a German spelling silently scores as 'not in the sequence table, rank 0'. The scoring model already has the canonical list, so the picker should use exactly these values and nothing else:
   Rank 1, 15 pts: Germany, Austria, Switzerland
   Rank 2, 11 pts: France, Spain, Italy
   Rank 3, 7 pts: Netherlands, Belgium, Luxembourg, Ireland
   Rank 0, 3 pts: Poland, Sweden, Denmark, Norway, Finland, Hungary, Czechia, Portugal, Estonia
   Rank -1, 0 pts: United Kingdom (Jack's territory)

2. MULTI-MARKET PROSPECTS ARE A REAL PATTERN, and this is the field that surfaces them. getgoods.com is VAT registered in AT, NL, FR, ES, IT and CH, six markets from one relationship. Otto Austria Group trades in AT, DE and CH. Once this is structured you can filter for partners who span markets, which is a different and better conversation than a single-country attach.

KEEP THE TWO COUNTRY FIELDS DISTINCT. 'Country' is the single home country and is what the legality guard reads, because cold email is permitted for FR, BE, NL and CH-targeted only while DE, AT, ES, LU, IT and CZ are LinkedIn led. 'Countries Selling In' is the multi-select and must not be wired into that guard, or a German company that also sells into France becomes emailable, which it is not.

Same treatment is worth considering for any other field the scoring reads. A picker is not a nicety where a number depends on the string matching.$il$);
insert into public.improvement_comments (team_id, improvement_id, who, at, text)
select i.team_id, i.id, $il$Claude$il$, '2026-09-09T09:00:00.000Z'::timestamptz,
$il$Flagging why this is more than cosmetic, for whoever picks it up. Territory is 15 of the 100 score points and it reads a country NAME. As free text, 'Deutschland', 'DE' or a typo all fall through to 'not in the sequence table, rank 0' and score 3 instead of 15, silently. Nobody sees a wrong score, they see a plausible one. So the picker should emit exactly the strings in the list above and nothing else. The same argument applies to any other field the scoring reads: where a number depends on a string matching, a picker is not a nicety. And keep Country and Countries Selling In apart, because the cold-email legality guard reads Country, and a German company that also sells into France must not become emailable.$il$
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i027$il$;

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i028$il$, $il$Long text is cut off in fields and cannot be read$il$, $il$Lovable UI$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-09T09:02:00.000Z'::timestamptz, 5, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Text is cut off across the company record and cannot be read without clicking into the field. Fix it by how long the field actually gets: auto-growing textareas for short overflow, auto-grow to about ten lines then scroll plus an expand control for long prose, and wrap plus fade in table cells. Hover tooltips are a supplement, never the mechanism, because they fail on touch and on keyboard. General rule worth adopting: no field should hide content at rest.$il$,
$il$WHY NOT HOVER ONLY: it fails completely on a tablet or any touch input, it is not reachable by keyboard so it fails accessibility, the text cannot be selected or copied out of a tooltip, and a long Coverage Summary in a floating box is harder to read than in place. Fine as a supplement, wrong as the answer.

RECOMMENDED, by how long the field actually gets:

1. SHORT OVERFLOW, one to three lines. Distribution, Insurance Product Types, Insurance Provider. Make these auto-growing textareas rather than single line inputs. The field grows to fit its content on load, so nothing is ever hidden and no interaction is needed at all. This is the main fix and it covers most of the screenshot.

2. LONG PROSE. Coverage Summary, Evidence, Notes. Auto-grow to a sensible maximum, roughly 8 to 10 lines, then scroll inside the field, with a small expand control that opens it full width for reading and editing. Never a fixed two-line box.

3. TABLE CELLS, where growing is not an option. Wrap to two lines, then a text fade rather than an abrupt cut so it is visibly truncated, and the whole row opens the record on click. Add title text on hover as a supplement, not as the mechanism.

ONE GENERAL RULE WORTH ADOPTING: no field should ever hide content at rest. If it is on the screen it should be readable without an interaction. That is the efficiency point Oliver keeps making, and it is cheaper to honour at build time than to retrofit.$il$);
insert into public.improvement_comments (team_id, improvement_id, who, at, text)
select i.team_id, i.id, $il$Claude$il$, '2026-09-09T09:03:00.000Z'::timestamptz,
$il$Worth knowing what is hiding in those fields, because it is the evidence that decides the verdict. The Coverage Summary on this record reads 'GREENFIELD (verified 2026-08-05, checkout walked + IPID test + adversarial verify)' and then carries the walked product, the price and the live URL. That is the audit trail behind a greenfield call. If it is clipped to two lines, the one thing a person needs in order to trust or challenge the verdict is the thing they cannot see.$il$
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i028$il$;

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i029$il$, $il$Research stage goes Outdated on age, and Outdated offers two routes$il$, $il$Research agent$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-09T09:15:00.000Z'::timestamptz, 3, array[$il$i003$il$]::text[], array[$il$i001$il$,$il$i041$il$]::text[], null, null, false, false, $il${"Oliver": "2026-09-09T11:17:48.570Z"}$il$::jsonb,
$il$A company whose research is older than three months moves to Research Stage = Outdated. Clicking Outdated offers two routes: queue it into the next automated research batch, or update manually. Outdated is DERIVED from the research date, never a status someone sets, and it must not reduce the score, only lower confidence and flag the row. Align the three month threshold with the two staleness constants already in lead_score.py rather than inventing a third.$il$,
$il$WHY IT MATTERS, with evidence from this batch. Research decays and the decay is not theoretical. ElectronicShop24 has switched insurance carrier TWICE, AmTrust and Generali before 2016, then Allianz Global Assistance 2016 to 2017, now Ostangler. DiTech.at was recorded as self-funded greenfield and turned out to carry a Wertgarantie policy. electronova-luzern.ch was researched off Internet Archive captures up to fourteen months old. A greenfield verdict has a shelf life, and right now nothing expires.

ALIGN THE THRESHOLD, DO NOT INVENT A THIRD ONE. There are already two staleness constants in lead_score.py:
  LEAD_STALE_DAYS  = 90   three months, contacts
  WEDGE_STALE_DAYS = 180  six months, the checkout walk

The code comment on the 180 is worth reading before setting this: 'TP's own procedure says findings go stale at roughly three months; six is used here because retail checkouts change more slowly than ticketing, and it is a choice worth arguing with rather than a fact.' So Oliver's three months matches the contact constant but is half the walk constant. Pick one number for company research and make all three consistent, or say explicitly why they differ. Three defensible definitions of stale is two too many.

SUGGESTED SHAPE:
1. Outdated is DERIVED from the research date, not a status someone sets. It cannot drift out of sync that way.
2. Outdated does NOT reduce the score. The scoring rule is that unassessed is removed from the denominator, never scored zero, and stale evidence should behave the same way: it lowers CONFIDENCE and flags the row, it does not silently demote the company. The wedge component already does exactly this, discounting a stale walk by 4 points and saying so in the reason string.
3. The queue needs a reason on it, 'outdated, last researched 14 Mar', so the agent knows what it is re-checking rather than starting from scratch.
4. Order the batch by what it unblocks. A company with contacts already sourced and outreach sitting in the refused queue is worth re-researching before one with no contacts. Same ordering principle as the refused queue itself.
5. Re-research should DIFF, not overwrite. If the insurance state has changed since last time, that is the single most valuable output and it should be surfaced, not quietly written over the old value.

SAME PLUMBING AS ITEM i025. The comments and instructions field routable to research needs an identical queue with a reason attached. Build one queue that takes jobs from both sources rather than two.$il$);
insert into public.improvement_comments (team_id, improvement_id, who, at, text)
select i.team_id, i.id, $il$Claude$il$, '2026-09-09T09:16:00.000Z'::timestamptz,
$il$One thing to decide before building: does a company go Outdated on the date of the last research run, or on the date of the last CHECKOUT WALK? They are different and the walk is the one that decays meaningfully. Of eight checkouts Oliver walked on 4 September, two overturned a confident desk verdict, both in the optimistic direction. Desk research ageing matters less than an unverified or long-ago walk. If only one date can drive the status, use the walk date.$il$
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i029$il$;

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i030$il$, $il$Sending a message must move the status to Contacted automatically$il$, $il$Guards$il$, $il$Brad$il$, $il$must$il$, $il$done$il$, $il$Oliver$il$, '2026-09-09T09:30:00.000Z'::timestamptz, 2, array[$il$i003$il$]::text[], array[$il$i005$il$]::text[], $il$Brad$il$, '2026-09-14T18:43:36.619Z'::timestamptz, false, false, $il${}$il$::jsonb,
$il$When a message goes out, Opportunity Status moves to Contacted without anyone setting it, derived from the touch history rather than typed. This is a fix as well as a feature: ten companies with touches on record still read Untouched, including Currys, Samsung and Carphone Warehouse. Three rules must ship with it. Forward only, never demote. Out of Scope flags a contradiction rather than flipping. A company becomes Contacted when any of its contacts has an outbound touch, and that does not cross group boundaries.$il$,
$il$IT IS ALREADY WRONG IN THE IMPORTED DATA, so this is a fix as well as a feature. 195 companies in the lake have at least one touch on record. TEN of them still sit below Contacted, all reading Untouched: Carphone Warehouse C223, Currys C229, Samsung C263, iStore C241, Fairphone C067, Magenta Telekom Austria C312, Drei C313, HoT C328, Congstar C330, haym.infotec C432. Those are not small names. Any worklist that filters on Untouched is offering them up as fresh.

DERIVE IT, DO NOT SET IT. Same principle as the Outdated status in item i029: if a touch record exists, the system already knows, so a human should not be maintaining it. Status should be computed from the touch history rather than typed.

THREE RULES THAT MUST GO WITH IT, or the automation causes damage:

1. FORWARD ONLY, NEVER DEMOTE. The ladder runs (none), To Review, Prospect, Contacted, Active Lead, Partner. A send advances a company to Contacted ONLY if it currently sits below Contacted. Sending a message to an Active Lead or a Partner must never knock it back down to Contacted. This is the obvious way to break it.

2. OUT OF SCOPE IS STICKY AND MUST FLAG, NOT FLIP. If a company is marked Out of Scope and a message goes out, do not quietly set it to Contacted. That hides a contradiction that someone needs to look at, either the send was a mistake or the Out of Scope call was. Raise it instead.

3. COMPANY STATUS DERIVES FROM ITS CONTACTS. A message goes to a person. The company becomes Contacted when ANY contact at that company has an outbound touch. Note this does not cross group boundaries: contacting getgoods does not mark Conrad as contacted, which is correct, and it is why the group level duplicate guard in item i004 is a separate control rather than something this rule can cover.

WORTH DOING AT THE SAME TIME: a one off reconciliation pass over the imported data, so the ten above and anything similar get corrected on the way in rather than being fixed one at a time later.$il$);
insert into public.improvement_comments (team_id, improvement_id, who, at, text)
select i.team_id, i.id, $il$Claude$il$, '2026-09-09T09:31:00.000Z'::timestamptz,
$il$A theme worth naming, because three of the last four items are the same shape. Outdated research (i029), Contacted status (i030) and next_step replacing P0/P1/P3 (i003) are all cases where a human is asked to maintain a value the system can already work out from its own records. Every one of them drifts, and the drift is invisible because a stale value looks exactly like a correct one. The general rule for the build: if it can be derived, derive it, and make the derived value read only in the UI so nobody can set it by hand and desynchronise it.$il$
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i030$il$;

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i031$il$, $il$Message history is incomplete, and LinkedIn vs Sales Nav URLs must be two fields$il$, $il$Integrations$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-09T09:50:00.000Z'::timestamptz, 1, array[$il$i032$il$,$il$i015$il$,$il$i033$il$,$il$i042$il$,$il$i045$il$,$il$i046$il$,$il$i048$il$]::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Catherine Meng P571 is missing the 20 August message and her plain LinkedIn URL. The gap originates upstream in the lake, so this is not a Lovable import bug. Two jobs. Split LinkedIn URL from Sales Nav URL, mirroring the two columns the lake already holds, and backfill. Then make record at send time a hard rule, because LinkedIn's own export is DMs only and an unlogged InMail is gone for good. For Brad to confirm: are both InMails and DMs captured by the integration?$il$,
$il$WHAT I CHECKED IN THE SOURCE LAKE:
- Her last touch on record is 10 August, T678, a LinkedIn DM. The 20 August message Oliver sent is NOT in the lake either. So Lovable imported faithfully and this is NOT a Lovable bug. The gap originates upstream.
- Her Sales Nav URL is present. Her plain LinkedIn URL is EMPTY, exactly as Oliver found.
- Her next action was Chaser #1 due 17 August, which fits a send around the 20th that then never got logged.

THE URL GAP IS SYSTEMIC, not one contact. Across 665 contacts: 437 have a LinkedIn URL, 423 have a Sales Nav URL, 314 have both, and 119 have NEITHER. So 228 are missing the plain LinkedIn URL and 242 are missing the Sales Nav one.

ON SEPARATING THE TWO URLS: agreed, and worth knowing the lake ALREADY holds them as two distinct columns, 'LinkedIn URL' and 'LinkedIn URL (Sales Nav)'. They are different things, a /in/ profile versus a /sales/lead/ record, and only the /in/ form is usable for enrichment lookups. If Lovable has collapsed them into one field, that is the fix. Do not invent a new scheme, mirror the two that exist.

THE DEEPER PROBLEM, AND IT DOES NOT GET FIXED BY BETTER SYNCING. There is a standing rule in the engine that connection state is a cheap snapshot and reconstructable, but message history is NOT: it has to be written at the moment of sending or it is gone. The reason is that LinkedIn's own export is DMs only and contains NO InMails, ever. So if the 20 August message was an InMail, no sync, no scrape and no reconciliation will ever recover it. It exists only in Oliver's Sales Nav inbox.

That makes 'record at send time' a hard requirement of the Lovable build rather than a nicety, and it is the single most important thing about the outreach module. A missing touch is worse than no data because the guards read it: a contact with no logged touch looks like a fresh prospect, which is how someone gets messaged twice.

FOR BRAD TO CONFIRM, Oliver's question: are ALL messages, InMails and DMs both, sent through Sales Nav and captured by the integration? The standing operating rule is that Sales Nav is the default channel even for first degree connections, so the intent is yes. What needs confirming is whether the 4-hourly watcher actually captures both, or only one of them.$il$);
insert into public.improvement_comments (team_id, improvement_id, who, at, text)
select i.team_id, i.id, $il$Claude$il$, '2026-09-09T09:51:00.000Z'::timestamptz,
$il$Two concrete asks that fall out of this. First, a backfill: 119 contacts have neither URL and cannot be actioned or enriched at all until they do, so that is a worklist in its own right. Second, a guard: refuse to draft to a contact whose message history was last synced before a given date, rather than assuming silence means nothing was sent. Oliver has been bitten by this before, when seven outreach cards were produced on the basis of an incomplete Outreach Log and every one of them was wrong. The rule that came out of it was to prove the thread before drafting. Lovable should enforce that rather than rely on remembering it.$il$
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i031$il$;

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i032$il$, $il$Jump straight out of the review card: Sales Nav, LinkedIn, and the company website$il$, $il$Lovable UI$il$, $il$Brad$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-09T10:15:00.000Z'::timestamptz, 5, array[$il$i017$il$,$il$i035$il$]::text[], array[$il$i031$il$]::text[], null, null, false, false, $il${}$il$::jsonb,
$il$CONFIRMED FROM USE, 16 September. The arrows next to the name and the company on the outreach card do NOT go to LinkedIn. Oliver has to open the person in Lovable first and jump from there, which is a step and a page load on every card he reviews.

Three destinations, all reachable from the review card itself:
  The lead's Sales Navigator profile, next to their name. That is where the message is actually sent from.
  Their plain LinkedIn profile, on the lead view.
  The COMPANY WEBSITE, next to the company name.

The website matters for the same reason as the profile: the review decision often needs a ten second look at the site. Does the checkout still show what the guardrail claims. Do they actually sell the device. Is the incumbent still named on the product page. Today that means leaving the card, opening the company, and finding the URL.

Make the website clickable on the company record too. It is currently a plain text field there.

Raised to must. It was a nice to have at one extra click; at review volume it is a step on every card, and the review queue is already the bottleneck.$il$,
$il$THE OPEN QUESTION IN THIS ITEM IS NOW ANSWERED. It previously said: there are already arrow icons next to the name and the company, worth confirming what they open before building a second one. Oliver has confirmed they do not reach LinkedIn. So either repoint those arrows or add the buttons, but do not end up with two arrows doing different things.

SALES NAV, NOT THE PLAIN PROFILE, on the outreach card. The standing rule is that Sales Nav is the default channel even for first degree connections, so the sales lead record is the working destination and the /in/ profile is the fallback.

EVERY ONE OF THESE WILL BE DEAD FOR SOME RECORDS, so handle it the same way in all three cases. 242 of 665 contacts have no Sales Nav URL and 119 have neither LinkedIn URL. The website field is empty on a large share of companies too. Fallback order for the person: Sales Nav URL, then the plain LinkedIn URL, then a Sales Nav people search on name and company, then grey the button out and say no link on file. For the company: the website, then nothing, greyed out with the same message. A greyed button that explains itself is a prompt to fix the record; a dead button that does nothing is just broken.

OPEN IN A NEW TAB, per i035, with rel noopener noreferrer. Oliver works across tabs, and losing the card to a navigation is the opposite of saving a step.

NOT IN CONFLICT WITH i019. That parks automated outbound LinkedIn deep links in a scripted flow at volume. A human clicking through from a CRM to one profile is ordinary behaviour and every CRM does it. Different thing, and the caution should not block this.$il$);
insert into public.improvement_comments (team_id, improvement_id, who, at, text)
select i.team_id, i.id, $il$Oliver$il$, '2026-09-09T10:25:00.000Z'::timestamptz,
$il$That same button should be in the lead view for the profile, for both LinkedIn and Sales Nav.$il$
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i032$il$;
insert into public.improvement_comments (team_id, improvement_id, who, at, text)
select i.team_id, i.id, $il$Claude$il$, '2026-09-09T10:26:00.000Z'::timestamptz,
$il$Extending this item rather than raising a new one, since it is the same control on a second surface and it shares the dependency on i031.

SO THE FULL ASK IS: a jump button next to the lead name on the OUTREACH card, and a jump button on each URL in the LEAD view, one for the plain LinkedIn profile and one for Sales Nav. Same on the company, opening the Sales Nav account page.

THE LEAD VIEW SCREENSHOT IS DIRECT EVIDENCE FOR i031. Christiaan de Groot's contact record shows a single field labelled LINKEDIN holding https://www.linkedin.com/in/christiaan-de-groot-a23613153, which is the /in/ profile. There is no Sales Nav field on that view at all. Catherine Meng, by contrast, has a Sales Nav URL and no /in/ URL. So the one field is holding whichever of the two happens to exist, which is exactly the collapse described in i031. Two labelled fields, two buttons, is the fix for both items at once.

SMALLER POINT ON THE SAME SCREEN: the URL is rendered as plain selectable text rather than a link. Even before any button exists, a URL field should be clickable.$il$
from public.improvements i where i.team_id = (select id from public.teams limit 1) and i.item_key = $il$i032$il$;

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i033$il$, $il$LinkedIn URLs are wrong in the record, and there is no trusted source for them$il$, $il$Data & schema$il$, $il$Both$il$, $il$must$il$, $il$open$il$, $il$Oliver$il$, '2026-09-09T10:44:55.000Z'::timestamptz, 1, '{}'::text[], array[$il$i031$il$]::text[], null, null, false, false, $il${}$il$::jsonb,
$il$The LinkedIn URL held for Mirco Krebs does not resolve, and there is no trusted source for these anywhere. Oliver runs the full LinkedIn data export and hands Brad the archive; Brad loads Connections and Invitations into the contact records, writing the URL as LinkedIn itself holds it. This has to come after i031 has split the two URL fields, or the load overwrites the wrong column. Flag mismatches rather than silently correcting them, and validate a URL on save.$il$,
$il$Oliver can export his full LinkedIn data, which gives Connections, Invitations sent and received, and Messages, each carrying the profile identifier as LinkedIn itself holds it. That export is the trusted source, and it should be loaded rather than trusted to typing.

What we need from this:
1. Oliver runs the LinkedIn data export and hands Brad the archive.
2. Brad loads Connections and Invitations into the contact records, writing the URL from the export and never overwriting a Sales Nav URL with it. This depends on i031 having split the two fields first, otherwise the load overwrites the wrong column.
3. Every contact whose URL did not match the export gets flagged, not silently corrected, so we can see how big the problem was.
4. A URL should be validated on save. A profile URL that does not resolve is a data defect, and the record should say so rather than look fine.

Open question for Brad: whether Phantombuster can keep this current on a schedule, or whether the export stays a periodic manual load. Worth knowing before we build around it.

Note on the export, so nobody expects too much of it: it carries DMs only. InMails are not in it and never will be, so it fixes URLs and connection state but it cannot repair the missing message history in i031.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i034$il$, $il$Reject in the top corner skips the reason dialog that Reject at the bottom shows$il$, $il$Lovable UI$il$, $il$Brad$il$, $il$nice$il$, $il$open$il$, $il$Oliver$il$, '2026-09-09T10:45:55.000Z'::timestamptz, 5, '{}'::text[], '{}'::text[], null, null, false, false, $il${}$il$::jsonb,
$il$Reject at the foot of the draft opens the Reject dialog with a reason picker. The Reject control in the top right corner does not, it just rejects. Point the top control at the same dialog. The bottom behaviour is the correct one.$il$,
$il$Worth saying why the reason matters beyond tidiness. Reject reasons are the only structured record of what is wrong with the drafting, so a silent reject is a lost training signal for the draft stack in i007. Anywhere a draft can be rejected, the reason should be captured.$il$);

insert into public.improvements (team_id, item_key, title, category, owner, priority, status, raised_by, created_at, build_wave, blocks, blocked_by, done_by, done_at, pinned, hidden, seen_by, detail, notes)
values ((select id from public.teams limit 1), $il$i035$il$, $il$External links on lead and company names should open in a new tab$il$, $il$Lovable UI$il$, $il$Brad$il$, $il$nice$il$, $il$open$il$, $il$Oliver$il$, '2026-09-09T11:10:08.000Z'::timestamptz, 5, '{}'::text[], array[$il$i032$il$]::text[], null, null, false, false, $il${}$il$::jsonb,
$il$The lead name and the company name on the outreach card should open in a new tab, target blank with rel noopener noreferrer. Only OUTWARD links: LinkedIn, Sales Nav, the partner site, a policy document. Links that navigate inside Lovable stay in the same tab. Low priority and open to debate.$il$,
$il$One distinction to hold, or this gets annoying fast. Only OUTWARD links open in a new tab: LinkedIn, Sales Nav, the partner website, a policy or IPID document. Links that move around INSIDE Lovable, such as a lead name that opens the lead record, should stay in the same tab, because a new tab per record turns into twenty tabs by lunchtime.

Worth Brad checking one thing first: if these are already real anchor tags then Cmd click, or middle click, already opens them in a new tab today and this is a default preference rather than a missing feature. If they are click handlers in script, Cmd click does nothing and that is the real defect, in which case make them proper anchors rather than adding a new tab call to the handler. Proper anchors also give us hover preview of the destination and copy link address, which the handler version silently loses.

Oliver logged this as low priority and open to debate.$il$);

-- exactness gate: every item in this part must hash to the value computed from the source file
do $verify$
declare bad text;
begin
  select string_agg(e.item_key, ', ' order by e.item_key) into bad
  from (values
    ('i026', 'db8861567f6b37f257c580ff01d8cb87', 3),
    ('i027', '7129ac6860aaab5c1f171cc3c21f851e', 1),
    ('i028', '471bb8d58497ea0e5af9de11ee9b5df3', 1),
    ('i029', 'f495c450af5c1799677038ac83a4d300', 1),
    ('i030', '09e5bf2ca13d422e4b3f86a295d2c1fa', 1),
    ('i031', '73730702a646d1470ac0e7e474ed1f82', 1),
    ('i032', '12e7f1ff3f03a13e34ed2744801bae56', 2),
    ('i033', 'a696b37b2428a4de5ad5ea199f929edf', 0),
    ('i034', '6bd7c8c411699767a479d7d5d9ba13ef', 0),
    ('i035', '257e89c7203e123c32ee8add5367fee3', 0)
  ) as e(item_key, src_md5, n_comments)
  left join public.improvements i
    on i.item_key = e.item_key and i.team_id = (select id from public.teams limit 1)
  where i.id is null
     or e.src_md5 is distinct from md5(concat_ws(chr(31),
      i.title, i.category, i.owner, i.priority, i.status, coalesce(i.raised_by,''), i.detail, i.notes,
      coalesce(i.done_by,''), array_to_string(i.blocks,','), array_to_string(i.blocked_by,','),
      coalesce(i.build_wave::text,''), i.pinned::text, i.hidden::text,
      to_char(i.created_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), coalesce(to_char(i.done_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),''), i.seen_by::text,
      coalesce((select string_agg(concat_ws(chr(31), c.who, to_char(c.at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), c.text), chr(30) order by c.at)
                from public.improvement_comments c where c.improvement_id = i.id), '')));
  if bad is not null then
    raise exception 'F18.5 import: rows differ from the source export: %', bad;
  end if;
end
$verify$;
